### ISSUE TITLE
Boards get into inconsistent state

### ISSUE THREAD

**Issue by smondet** [ZenHubIO/support#1016]
And there is no visual clue telling whether it is updating or whether something failed.
After a few minutes & page reloads it converges to an OK state.

![zen-nuts](https://cloud.githubusercontent.com/assets/617111/22039661/25087c36-dcce-11e6-9550-94f93d7da4f1.png)

It's on Firefox.

**Comment by Mathieuu** [comment]
We are aware of the issue, it comes from an incorrect internal state of the react components. Refreshing the board fixes the inconsistency because we refetch the correct data from the board.

We should have a fix deployed to production in the following days and a mechanism to prevent these cases from happening in the future.

Thanks for reporting it.

**Comment by kendramoroz** [comment]
@smondet Circling back here to let you know this issue is now fixed! Please let us know if you encounter the inconsistent state again :)
