### ISSUE TITLE
Pull Requests tab count not updated after merging PR

### ISSUE THREAD

**Issue by josescgar** [ZenHubIO/support#1020]
*Preconditions: There is at least one opened PR*
*Device: MacBook Pro/MacOS Sierra*
*Browser: Chrome Version 55.0.2883.95*

## Steps to reproduce
1. Navigate to the "Boards" tab
2. Navigate to the "Pull Requests" tab
3. Select one existing PR
4. Merge and delete the branch
5. Go back to the "Boards" tab

## Expected result
The count next to the "Pull Requests" text in the tab is decreased by one

## Actual result
The count is not updated until the "Pull Requests" tab is clicked again

**Comment by kendramoroz** [comment]
Hey @josescgar thanks for sending this in! The navigation tab behaviour you see here is actually the result of GitHub behaviour! Until you click back on a GitHub tab, it won't update. Unfortunately we can't influence this count here at ZenHub since PRs belong to GH. I'd suggest shipping this off to GitHub as a feature enhancement around how their syncing works! If there's anything else I can help with, let me know 🎉
