### ISSUE TITLE
Why does the Pipeline move when linking PR to issue?

### ISSUE THREAD

**Issue by tsub** [ZenHubIO/support#1029]
Release of cooperation function between issue and PR was wonderful! Thanks a lot!

However, if you link issue and PR, the pipeline will move.
Why does the Pipeline move when linking PR to issue?

I'm glad that the pipeline does not move.

**Comment by azenMatt** [comment]
Hi @tsub 

We have the pipeline set to move so that if the issue and PR are in different pipelines, they can both be in just one pipeline rather than two. 

The flow will aim to move the issue along to meet the PR - so if you use the 'default PR pipeline' setting, you should be able to keep the board accurate

**Comment by tsub** [comment]
Surely you are right. I was convinced. 😄 

Many thanks for @azenMatt !
