### ISSUE TITLE
PR to issue connection gets lost

### ISSUE THREAD

**Issue by hectorj** [ZenHubIO/support#1043]
Not sure what triggers it, but some connections from PRs to issues seems to sometimes get dropped:

The historic shows "{colleague} connected this pull request to {organization}/{repo}#{issue number} {issue title}".

No sign of disconnection in the historic, but the link is gone.

**Comment by kendramoroz** [comment]
@hectorj thanks for reporting this 🕵️ ! Not an intended part of the feature—To have our team dig into this, would you mind passing over the **organization name, repo name, and a few examples of pairings with the issue number and pull request number** so we can look into what's happening?

Feel free to send this over to support@zenhub.com if you don't want to paste it in the issue here :) 

(Same goes for @mnapoli and @KuiKui! I noticed you 👍 the original issue, if you're having the same thing happen please let us know)

**Comment by mnapoli** [comment]
Hi @kendramoroz, thanks for looking into this. We all work in the same organization (and we've all experienced it on separate pull requests so it doesn't seem to be an isolated issue). Here is an example of a pull request which required us to connect it twice with the issue: https://github.com/wizaplace/wizaplace/pull/1088 (private github repository).

The first link with the issue was at 2017-02-16 10:18:15, the second time was at 2017-02-17 10:22:30.

In between those dates there was:

- title change
- assignment to a user
- a review of the PR with comments
- new commits
- comments

I hope that helps.

**Comment by kendramoroz** [comment]
@mnapoli Thanks for sending this over! With 1088, what was the issue ID you were connecting it to?

**Comment by mnapoli** [comment]
@kendramoroz it is connected to https://github.com/wizaplace/wizaplace/issues/961

**Comment by hectorj** [comment]
Happened again with https://github.com/wizaplace/wizaplace/issues/1184 and https://github.com/wizaplace/wizaplace/issues/1022

**Comment by kendramoroz** [comment]
@mnapoli @hectorj thanks for your help in debugging here! Thanks to your support we've been able to track the 🐛  and squash it. The latest extension version, [2.29.19 ](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)will have this fix. Once you're on this version if you notice anything happen again please ping us so we can jump back into 🕵️  mode. 

🚀

**Comment by mnapoli** [comment]
Awesome thanks!
