### ISSUE TITLE
Feature Request: set reminders

### ISSUE THREAD

**Issue by cshunger** [ZenHubIO/support#1052]
Feature Request:

I would like to be able to set a reminder on a zenhub issue to in order to check up on that issue frequently. 

ex. I comment on an issue, I can set a reminder to check on that issue in 1 day, 1 hour, 1 week, etc.

**Comment by kendramoroz** [comment]
@cshunger great suggestion here! Are you currently using the To-Do feature? While there's no specific reminders associated with ToDo items yet, it's a great way to bundle work together that you need to circle back to. You're able to create custom lists so you can bucket work into today, next week, etc. The shortcut `Z` will take you to ToDos as well for easy access. 

![image](https://cloud.githubusercontent.com/assets/11036230/23235499/95fbaef6-f90a-11e6-9df8-31f762568bac.png)

**Comment by cshunger** [comment]
This is really helpful. Is this part of Zenhub Enterprise?

**Comment by cshunger** [comment]
I did not even know about that. I will give it a try 👍

**Comment by kendramoroz** [comment]
@cshunger It is! You can add any issue to the ToDo section through the shortcut `shift+z` or clicking the ⚡️ at the top of any issue

![image](https://cloud.githubusercontent.com/assets/11036230/23236029/8a4fe980-f90c-11e6-811e-62d46ea50fcc.png)

This is currently at the user level so whatever customizations you do to your ToDo page won't impact the issues and or anyone else :D

**Comment by kendramoroz** [comment]
PS! Once an issue is added to the ToDo section, the same shortcut `shift+z` will complete to do and remove it from your list 👯

**Comment by cshunger** [comment]
That is fantastic @kendramoroz thank you for opening my 👀

**Comment by kendramoroz** [comment]
My pleasure @cshunger! Let me know if you have any other questions I can help. Feel free to get in touch anytime here or through support@zenhub.com

In the mean time, I'm going to leave this issue open as a reminder about notification enhancements in general! Feel free to drop any other comments here once you've given ToDo a go.

**Comment by kendramoroz** [comment]
Hey @cshunger Kendra here from the ZenHub Team - I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
