### ISSUE TITLE
New label not appearing on Boards "Labels" filter

### ISSUE THREAD

**Issue by aensley** [ZenHubIO/support#1064]
I added a label to our repo yesterday: **[Type] QUICKFIX**

I immediately went to the Boards to filter by this label but it didn't show up in the list.

![labels](https://cloud.githubusercontent.com/assets/95717/23712653/2873cdb6-03e9-11e7-9d10-4a012cbc1973.png)

I figured I needed to wait for some caches to clear or possibly a scheduled task on ZenHub's end for the label to appear. Here I am a day later and still no label. Ideas?

**Comment by kendramoroz** [comment]
@aensley Thanks for reporting this 🐛 ! I've issued this up for our team to squash. I'll post an update once a fix is released.

**Comment by kendramoroz** [comment]
Circling back to this! You can disregard my previous comment—Not a bug, but rather expected behaviour for the label filter when no issues have that label attached to them! Once you add this label to an issue you should see it populated in the filter you have shared. 

If you'd like to add this label to issues enbulk you can select the issues from the board by clicking on the avatar image and leveraging the add labels button, where your new label should appear :) 

![image](https://cloud.githubusercontent.com/assets/11036230/23722162/40666806-03f9-11e7-8ab4-a4a9e49d3dfb.png)

If it's not appearing in this dropdown or once it's added to any issue, please let me know!

**Comment by aensley** [comment]
D'oh! Sorry about that. Makes perfect sense.

**Comment by kendramoroz** [comment]
🙊  No trouble at all! Always reach out with questions—we're here to debug together 💪 . 

Enjoy the rest of your day and let me know if I can help with anything else!
