### ISSUE TITLE
Is it possible to request to change rate limit of Zenhub API

### ISSUE THREAD

**Issue by tri-duong-vn** [ZenHubIO/support#1071]
Zenhub API now has rate limit 100 calls per minute but it seems a bit low rate for our usage.
Is it possible to grant higher limit for us? Does the rate limit increase if we upgrade to Enterprise Zenhub?

**Comment by kendramoroz** [comment]
@tri-duong-dena Kendra here from ZenHub! No immediate plans to change the rate-limit on .com for the API, but something we've heard from others as well. ZenHub Enterprise is available if your team is using GitHub Enterprise. When you use GitHub Enterprise and ZenHub Enterprise, because it's an on-premise solution you're able to change the rate limit to meet your team's needs as no one else externally is impacted by the change. 

If you'd like to learn more, feel free to drop us a line at support@zenhub.com!

Let me know if I can help with anything else here :).
