### ISSUE TITLE
Rate limit error is not handled

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1099]
See the following screenshot:

![image](https://cloud.githubusercontent.com/assets/490562/25461344/9726b7c6-2b3c-11e7-8f5f-d5f487f3c8bd.png)

It looks like the API is returning a rate limit error, which is not handled and displayed as is in the dropdown.

**Comment by kendramoroz** [comment]
@adamreisnz thanks for reporting this! Looks like this is a GitHub bug in how they're rendering issue titles when the rate limit is exceeded. As a next step here I'd recommend sending this off to support@github.com so they can dig deeper into the root cause and issue up a fix :). 

Let me know if you have any questions about this!

**Comment by adamreisnz** [comment]
Ok I can do that, and it may very well be an issue originating at Github, but given how it affects *your* software and the user experience of *your* users, I think it should be *you* who knocks on Github's door with this issue rather than your users. I think this will have much more leverage and impact than a single random person contacting them.

Anyway, I will send them an email
