### ISSUE TITLE
Issue belonging to multiple milestones

### ISSUE THREAD

**Issue by fabriziocucci** [ZenHubIO/support#1117]
I searched across all issues and I wasn't able to find anything similar but it may very well be that I missed it, so apologies in advance if that's the case. 

I just finished to read [Better Software & Stronger Teams](https://www.zenhub.com/book/github-project-management) and I couldn't find the answer I was looking for regarding a specific use case. 

According to the book, `Sprint`s map to `Milestone`s and issues with a milestone associated become part of the sprint backlog. So far so good, that worked for me so far.

But what if there is a **real** milestone with a broader scope and a fixed date, e.g. an external commitment to deliver the version 2.0 of the product X by Q3? Currently, if an issue belongs to the sprint milestone it can't belong to the broader milestone, which means that there is no way to explicitly tell if that issue is also relevant for the other and it's kind of difficult to keep track of the progress of the wider milestone. If an issue could belong to the current sprint but also to the broader milestone it would be easier to have a view of the very short term (current sprint) but also the long term (external commitment). Moreover, it would help to prioritize issues that should fall into the sprint milestone by taking all, or most of them, out of the broader milestone.

It's also worth mentioning that the same feature request has been raised to [GitHub](https://github.com/isaacs/github/issues/441) and [GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/26408). Going through those may provide additional use cases for which this could come in handy.

Please feel free to close this if there is a simpler way to model my use case and/or achieve the same results.

**Comment by fabriziocucci** [comment]
I guess the ZenHub concept of `Release` is the closest solution to cover my use case, even though it may be the cause of a bit of confusion (e.g. an issue cannot belong to more than one milestone but it can belong to more than one release).

IMHO, there a few things a bit off around the ZenHub `Release` concept overall:

* it doesn't seem to be possible deleting releases (as reported [here](https://github.com/ZenHubIO/support/issues/1118));

* the concept of release seems to be a first class citizen in the ZenHub experience but it doesn't seem to be fully inline with the GitHub experience, i.e. I would have expected something similar to the `Milestones` tab under the `Issues` tab: 
<img width="1029" alt="releases-tab" src="https://cloud.githubusercontent.com/assets/8156463/26034353/22acb754-38b3-11e7-808c-87bee177d31e.png">

* as a consequence of the previous point, it is not super intuitive being forced to go into the `Report` tab to edit a release, e.g. :
<img width="1021" alt="zenhub-edit-release" src="https://cloud.githubusercontent.com/assets/8156463/26034608/245941a4-38b7-11e7-90c3-8233c4b8df01.png">

* there seems to be a bit of a clash between the ZenHub concept of `Release` and the native GitHub concept of `Release`. They are close but not exactly the same and this can cause a bit of confusion, e.g. I've a ZenHub release but I can't see anything under the GitHub releases page: 
<img width="1006" alt="github-release-hyperlink" src="https://cloud.githubusercontent.com/assets/8156463/26034480/11ddd140-38b5-11e7-84ad-aa21c6d65565.png">
<img width="763" alt="github-release-page" src="https://cloud.githubusercontent.com/assets/8156463/26034492/37c04244-38b5-11e7-8638-a2eb2e91dc05.png">

* I've slightly touched this at the beginning but I actually believe this is the most crucial point. The concept of `Milestone` is pretty generic, so generic that we are even able to map sprints to it. I believe that long-term business goals, external commitments or anything really that spans across multiple sprints **is** indeed a `Milestone`. Introducing the ZenHub concept of `Release` does seem a bit redundant and it feels more like a workaround to avoid introducing a many-to-many relationship between issues and milestones (which probably isn't super easy considering that milestones are first class citizens in GitHub). I'm probably seeing only black and white here but maybe a more consistent user experience could be achieved by one of these mutually exclusive solutions:
  * making issues assignable to multiple milestones and discarding the ZenHub `Release` concept;
  * renaming the ZenHub `Release` concept into something more generic like `Scope` and mapping both sprints and anything that spans across multiple sprints to it (this also means detaching from the GitHub milestones concept).

I hope those comments will help to make ZenHub even better!

**Comment by kendramoroz** [comment]
@fabriziocucci Thanks for the detailed feedback here! I've made a few notes below, but please keep the feedback coming—insights on how our users are leveraging Release reports is valuable as we continue to ship enhancements over time 💪 

> it doesn't seem to be possible deleting releases (as reported here);

Currently you can edit or close a Release, but the ability to archive/remove a Release is on our radar! In your workflow, under what circumstances would you choose to hard-delete a Release over having it closed for reference? With removal of information comes complex workflows around permissions, so the more insight we have from teams on this workflow the better we're able to implement additional functionality here without the potential lose of information for teams!

> the concept of Release doesn't seem to be a first class citizen in the documentation, i.e. I was expecting its introduction alongside with Milestones and Epics here.

Great point! Agree it should be treated as first class and featured here. The guides is a recent launch from the team here, so Releases aren't yet in the agile concepts guides, but will be very shortly 👍 . 

> there seems to be a bit of a clash between the ZenHub concept of Release and the native GitHub concept of Release.

Good spot! The concept of a Release by GitHub is more in alignment with that of `deployment` and code. With the launch of Release reports, we wanted to be less restrictive on the purpose of Release as it relates to Release reports since not all users of ZenHub are developers or those who ship code. ZenHub Releases allow organizations to track against long-term goals or deliverables across multiple deployments, teams, repos, and milestones irrespective to where they live within the GitHub environment of the team's organization. This allows better project planning long-term leveraging issues. This is a great point of discussion so I'll be sure to add this as a more in-depth FAQ on our guide page as I'm sure others have similar questions around the differences in terminology and use case. Thanks for bringing this up! 

>  Introducing the ZenHub concept of Release does seem a bit redundant and it feels more like a workaround to avoid introducing a many-to-many relationship between issues and milestones (which probably isn't super easy considering that milestones are first class citizens in GitHub).

Great feedback! Releases is one step in the direction of supporting long-term project planning that span multiple-milestones. While Milestones is as you mentioned, native to GitHub, I'll be sure to send the multiple-milestone per-issue feedback to the team. 

Let me know if there's anything else I can touch on here or answer to help you get more acquainted with Releases! Keep the feedback coming 💥

**Comment by kendramoroz** [comment]
👋  Hey everyone - closing this issue as there hasn't been movement since early last year. While we don't have plans to build additional functionality on top of GitHub's Milestone behaviour to allow Issues to be added to more than 1 Milestones at a time, we're really stoked about work in progress to help with scope changes during and at the end of Sprints to help teams more accurately report against what changes are occurring mid-Sprint. Subscribe to #791 or #357 for updates as they become available!
