### ISSUE TITLE
Add support for navigating Epics dropdown with tab / arrow keys

### ISSUE THREAD

**Issue by noahmanger** [ZenHubIO/support#1119]
Small UI enhancement request: when viewing a single issue, it would be really useful to be able to navigate the Epics dropdown with keyboard, rather than needing to use the mouse. This would be a win for a11y as well as general usability, as it would make it consistent with the native Github dropdowns and the Zenhub dropdowns on the board view.

I see this has been touched on in https://github.com/ZenHubIO/support/issues/957 as well, so feel free to mark as a duplicate if this is too redundant. 

Thanks!

**Comment by kendramoroz** [comment]
Hey @noahmanger Thanks for the feedback here! Bumping this over to discussion as well as to the design team here :). 

Keep the feedback coming!

**Comment by kendramoroz** [comment]
Hey @noahmanger this Issue should now be resolved! We've also even launched a suite of 35 new keyboard shortcuts alongside the ability to use arrow keys to navigate dropdowns 😊  - you can check out the full suite of shortcuts here: https://www.zenhub.com/guides/keyboard-shortcuts

Feel free to re-open if the problem is persisting for you!
