### ISSUE TITLE
Story points of epics not shown in Release Report view

### ISSUE THREAD

**Issue by fabriziocucci** [ZenHubIO/support#1139]
### Steps to reproduce
1. create a new release `My Release`;
2. create a new epic `My Epic` and attach it to the release `My Release`;
2. create a couple of issues, estimates them and attach them to the epic `My Epic` and the release `My Release`;

![board-annotated](https://cloud.githubusercontent.com/assets/8156463/26760109/d743db58-4910-11e7-809c-47cac57c8ff6.jpg)

3. go in `Reports` -> `Release Report`, select the release `My Release` and then scroll down till the section `Issues in this Release` -> `Remaining issues and pull requests`;
4. for the epic `My Epic`, the column `Story Points` **should** contain the sum of the story points of the issues contained in that epic but instead `Not estimated` is shown.

![release-report-annotated](https://cloud.githubusercontent.com/assets/8156463/26760118/1b08d848-4911-11e7-809e-5bebd854f41d.jpg)

Ultimately, it seems a bit misleading that the estimate reported for epics in the `Release Report` differs from the estimate reported in the standard epic view:

![epic-annotated](https://cloud.githubusercontent.com/assets/8156463/26760220/47b21dd0-4913-11e7-8b75-805de745c4b6.jpg)

### Notes
* verified with ZenHub for GitHub Enterprise 2.16.2 on Chrome.

**Comment by kendramoroz** [comment]
@fabriziocucci Thanks for writing in! 

The Epic points that you're mentioning represent the sum of all estimated Issues and sub-Epics within a Epic. However, unless the Epic itself gets a story point value, it's an unestimated Epic. This means that when added to a Release, it's not going to be estimated since it's only the Epic Issue itself that's been added, which is unestimated. ([Here's a guide](https://www.zenhub.com/guides/getting-started-with-epics-in-zenhub#epic-points-vs-story-points) we have that covers Epic points vs. Story points if you're interested!) 

Adding an Epic to an Issue doesn't automatically add it's sub-tasks: You still need to add these to the Release itself. Best route here would be to filter the Board by the Epic, use the **select all functionality** and then leverage the multi-action bar to **add to release**. 

Here, for example we've filtered by the Milestone to have select all pop-up:

![image](https://cloud.githubusercontent.com/assets/11036230/26747638/f872dd76-47ab-11e7-8b53-060b185aa933.png)

Let me know if this helps answer your question or if there's anything else I can help with :).

**Comment by fabriziocucci** [comment]
@kendramoroz thanks as usual for your prompt reply! :)

I believe my verbose description was not clear enough to highlight the issue. I've just updated it with a couple of screenshots that should make more clear my original intent.

I look forward to receiving your feedback.

**Comment by kendramoroz** [comment]
Hey everyone! We're working on improvements to how Epics are handled within Releases :) - bumping this over to in progress. We'll have more to share shortly!

**Comment by kendramoroz** [comment]
👋 We have launched updates to the Release report that no longer add an average estimate to Epics, and give them a much clearer dedicated home at the top of the Issues list. Unless an Epic is explicitly estimated, the report will no longer double count an average estimate! Closing for now, but feel free to drop in feedback or open up further issues for other feedback requests!
