### ISSUE TITLE
ToDo dropdown hidden behind UI elements on Pull request 'Files Changed' tab

### ISSUE THREAD

**Issue by h2oboi89** [ZenHubIO/support#1140]
The other two tabs for a Pull Request do not have this issue.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/5531999/26765992/ace00d56-4955-11e7-8c16-783619a00b9e.png)

**Comment by h2oboi89** [comment]
Browser: Chrome Version 58.0.3029.110 (64-bit)

**Comment by kendramoroz** [comment]
@h2oboi89 Thanks for submitting this! I'll ship this 🐛  off to our product team.

**Comment by erikhuizinga** [comment]
This bug continues to exist.

Chrome v60.0.3112.113 (64-bit). ZenHub extension v2.35.10.

**Comment by kendramoroz** [comment]
Hey @erikhuizinga - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
