### ISSUE TITLE
Why burndown chart calculates story points day by day.

### ISSUE THREAD

**Issue by kimwz** [ZenHubIO/support#1166]
In the past, each story point was applied to burndown chart when closed an issue. But now it applies to the burndown chart as the sum of the day's day. 
It's a confusing change. Is this a bug or an intention?

**Comment by kendramoroz** [comment]
@kimwz Thanks for getting in touch! This was a recent intentional change to make the Burndown easier to use for long-duration Milestones that otherwise would be cluttered with many dots. Making the change to day-by-day allows teams to see collectively how they're burning down towards a Sprint as the Milestone gets closed to completed and allows teams to easier consume what happened over the course of a day without having to interact with many data points on the chart. 

Would you be able to give a bit more insight on how your team is finding this change confusing? I'd love to pass this back to our design team for further review :)

**Comment by kimwz** [comment]
Thanks. I understand. you are right but our team is a small team and team's milestones are not long-duration Milestones. so, we didn't have many dots.
now, more precise tracking is difficult than before, but it does not seem to matter much.
I will try to adapt. 
thank you.
