### ISSUE TITLE
Add ToDo feature to web version

### ISSUE THREAD

**Issue by cemsbr** [ZenHubIO/support#1182]
There's no bolt icon and I couldn't find a way to view the ToDo list using the web version. I can only access it using the browser extension.

**Comment by kendramoroz** [comment]
Hey @cemsbr - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.

**Comment by Chris2011** [comment]
I really loved this feature and as you said a lot of people used it, so why removing it? Today I was wondering, where my todo link is, because I didn't follow your changelog. Now I see that you removed it.

The thing is, that the todo for me was only to pin a bug from an other repo. So nothing todo with my personal project or repo. I only wanted to pin some bugs, where I mentioned/commented etc. to find it later.

I know the Issues section from github, but there are bugs which are not relevant anymore.

Please rethink your decision of removing it. It was such a great feature. Thx.

**Comment by kendramoroz** [comment]
@Chris2011 That's an interesting use case for ToDo, thank you for sharing! As we work to enhance ZenHub and empower teams to be more collaborative and productive, we've seen widespread community adoption and support for other areas of the product that bring teams together that we've decided to focus on and continue to improve. While ToDo is no longer supported, we're working diligently to ensure workflows and workspaces continue to be enhanced to help teams move forward, faster. 

I'll be sure to Issue up your use case internally so if there's other areas of the product that can help with this similar 'pin' type functionality we'll keep you updated. 

If there's anything else I can help with, don't hesitate to drop us a line!

**Comment by Chris2011** [comment]
Yeah pin/todo whatever :). Would be great. Thx. Not yet If I have smth, I will create a new ticket.

**Comment by Laurix1983** [comment]
Our company also loved the feature 👍

**Comment by shenghu** [comment]
@kendramoroz is there alternative for ToDo?
