### ISSUE TITLE
In mobile, website comes up blank in safari/chrome incognito.

### ISSUE THREAD

**Issue by jdejesus007** [ZenHubIO/support#1183]

**Comment by kendramoroz** [comment]
👋  Hey @jdejesus007 thanks for getting in touch-I see that the Issue is now closed, but for reference private browsing isn't supported but you should see the following screen:

![screen shot 2017-07-13 at 1 29 16 pm](https://user-images.githubusercontent.com/11036230/28186272-5b8e5136-67cf-11e7-807c-203c55ebf63b.png)

Let me know if you're having any trouble getting started!
