### ISSUE TITLE
New swimlanes appearing without (probable?) cause

### ISSUE THREAD

**Issue by drkknght00** [ZenHubIO/support#1193]
Our company has many repos - one of which I use to track major issues.  I have a zenhub view that includes only that repo.  However, I've noticed a bunch of new columns and swimlanes appearing (or others getting renamed).  I would like to delete those, but now I'm unsure who else this would be impacting.  

I've asked the wider org to help solve the mystery, but figured I'd ask here as well, in case there's something obvious I'm missing.

**Comment by kendramoroz** [comment]
Hey @drkknght00 great question! If this Board is merged with another Board, deleting pipelines will cause it to be removed across both Boards. But if the view only includes that one repo, no other workspaces should be impacted. Pipelines can only be created by users adding them, or the Board having been merged (then unmerged) with another Board. So if anyone else in your team was using either of these functionalities this is what could have caused the pipelines to appear. 

Let me know if you have any other questions about this!

**Comment by drkknght00** [comment]
Hi Kenra - thanks for the response

So is the likely scenario, someone added my repo to their view, which then got it to add the columns?  But now that my view only has my repo, I can change them without impacting the other...?

**Comment by kendramoroz** [comment]
> So is the likely scenario, someone added my repo to their view, which then got it to add the columns? But now that my view only has my repo, I can change them without impacting the other...?

That's correct! If you merge a repo, but then un-merge, it'll leave the "new" pipelines there since they became part of your Board during the merge. But if they're no longer connected you can make an update without worrying about hurting someone's view. 

When you go to remove a column, there will be a notification modal that confirms your action and will list out any other repos (if at all) that will be influenced so you'll be able to do a double confirmation. 

You can also check on the repo filter on the top left of the Board - if only your Board is listed you should be safe :) 

(For example in this one, there's 6 so actions influence all Boards, but if it states `1/1` you should be good!)
![image](https://user-images.githubusercontent.com/11036230/28585244-87fad934-7124-11e7-8f2f-b24dc8e9b621.png)

**Comment by drkknght00** [comment]
ahh, i see.  I was only looking at the "1" part, and ignoring the "6" part -- and, in my case, it says "13" :(

Is there any way to force separate?  Or do i have to find the other 12 and have them remove mine?

**Comment by kendramoroz** [comment]
> Is there any way to force separate? Or do i have to find the other 12 and have them remove mine?

You can hover over your repo in that list and a `disconnect` option will appear:

![image](https://user-images.githubusercontent.com/11036230/28652204-38c980dc-723b-11e7-9f49-20de41c5d18d.png)

This will disconnect your repo from the other 12 - after disconnection you'll be able to clean up your pipelines! I'd also recommend a chat with your team to make sure that the connection was an accident to ensure that no one re-connects and puts you into the same unwanted state once more. 

Let me know if there's any other questions about this, happy to help!

**Comment by drkknght00** [comment]
Thanks Kendra -- I'll go that route! :)
