### ISSUE TITLE
Stuck on "Loading issues in this Epic..."

### ISSUE THREAD

**Issue by iget-master** [ZenHubIO/support#1215]
I'm having this issue with a private repository. I've just converted an issue into epic, then it doesn't show the epic issue listing and buttons to add issues on epic.

I've tried to add an issue to this epic from outside, but it don't list too.

No errors are being thrown on console or network tab. 
Using Chrome 61.0.3163.31 (Versão oficial) beta 64 bits

**Comment by kendramoroz** [comment]
Hey @iget-master do you have time to jump on a support call today/Monday to walk through this? Since you're not seeing any errors, best next step is to jump to a debugging screen share so we can avoid  a bit of back-and-forth. Feel free to send me a note at kendra@zenhub.com with your timezone and a few times that work for you!

**Comment by iget-master** [comment]
It was solved by opening the epic on Zenhub's dashboard, then came back to github and the epic loaded fine.

**Comment by kendramoroz** [comment]
Thanks for the update @iget-master !
