### ISSUE TITLE
Links from Epics to issues mangled using Firefox (extension)

### ISSUE THREAD

**Issue by awborgland** [ZenHubIO/support#1233]
Seen on a Macbook Air MacOS 10.12.6 using Firefox v55.03:

Using the Firefox ZenHub plugin, all links from epics to issues are mangled. They contain an extra "/workspace/o" in the middle of the URL as in:
https://github.com/workspace/o/project/repo/issue/N

The correct link is:
https://github.com/project/repo/issue/N

This is a new behavior. I then realized that
https://app.zenhub.com/workspace/o/project/repo/issue/N

is a valid URL. So it looks like ZenHub using the Firefox plugin now is confused by the new app.Zenhub link syntax.

This is not seen using the Chrome ZenHub plugin.

**Comment by kendramoroz** [comment]
👍  Good spot! Issuing this 🐛  up with the team and I'll post once it's resolved.

**Comment by kendramoroz** [comment]
@awborgland all fixed in 2.35.12! Your extension should automatically update today, but if you'd like to force a download, uninstall and re-grab the extension from [zenhub.com/choose-platform](https://zenhub.com/choose-platform)

Thanks again for reporting this and let me know if it doesn't resolve for you!

**Comment by awborgland** [comment]
Just grabbed the new version and it works! Awesome! Thanks! That was quick.

**Comment by kendramoroz** [comment]
@awborgland great to hear! If anything else comes up, send a note our way - 🐞 👞
