### ISSUE TITLE
Is the ZenHub extension supported for Firefox v45?

### ISSUE THREAD

**Issue by awborgland** [ZenHubIO/support#1234]
For various reasons (none good), Linux desktop support where I work is stuck at RHEL6 which means I'm stuck at Firefox v45 on my desktop. With the latest version of the ZenHub extension (just updated, see #1233), when I click on it to authenticate it pops up a window, but it's all white except for a "ZenHub.com" banner at the top. Yesterday it sort of did allow me to authenticate (with a lot of errors), but the boards were not available so it was already broken

Is the extension supposed to work for such an old version of Firefox (or should I bite the bullet and just switch all my ZenHub work over to my Macbook)?

**Comment by kendramoroz** [comment]
@awborgland we recently updated the Firefox extension to support multiprocess (https://github.com/ZenHubIO/support/issues/1026#issuecomment-321049154) which means legacy Firefox versions are no longer compatible! If you'd like to stay in Linux desktop, you can access ZenHub via [app.zenhub.com](https://app.zenhub.com) but the Browser Extension unfortunately won't support Firefox 45 anymore since it doesn't support multiprocess. Hope this helps clarify things, but please let me know if I can help with anything else!

**Comment by awborgland** [comment]
Clear enough! And thanks for the quick reply!

**Comment by kendramoroz** [comment]
My pleasure! Always here to help 💪
