### ISSUE TITLE
unable to drag a issue from a pipeline to another with write permission

### ISSUE THREAD

**Issue by nerokapa** [ZenHubIO/support#1258]
I'm pretty sure I have write permission to a repo, I can push code to master branch, make new pipeline, edit the labels and even change other user's permission. But I got a permission error when I tried to drag a issue to another pipeline, is it an bug?

Here is the screenshot about the issue. 

![screen shot 2017-10-03 at 23 34 57](https://user-images.githubusercontent.com/8110087/31159016-e57239f8-a893-11e7-850c-9bd8fb6f6647.png)

![screen shot 2017-10-03 at 23 35 19](https://user-images.githubusercontent.com/8110087/31159021-eaa96f5e-a893-11e7-8fde-21704718b026.png)

**Comment by kendramoroz** [comment]
@nerokapa thanks for sending this through - can you confirm when you were granted write permissions? As well as open the developer console and let us know what errors appear?

**Comment by legshort** [comment]
I have the same problem, indeed I sent an invitation to collaborator and she clicked `Join Team` from the invitation email but status says `invitation pending` and she is not able to move any card to anywhere.

**Comment by kendramoroz** [comment]
@legshort thanks for following up here! Can you confirm if the permissions issue is still occurring? If permissions were provided right before your team member joined, but they didn't have permissions before authenticating, there might be a caching issue which caused a delay in the Board picking up that they should be able to edit the Board. Can you verify if the issue is still occurring and let me know?

**Comment by legshort** [comment]
@kendramoroz the problem had been solved automatically thanks!
