### ISSUE TITLE
can't create epics

### ISSUE THREAD

**Issue by a-laughlin** [ZenHubIO/support#1266]
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OSX 10.9.5

Steps to reproduce:
On a board click "new issue"
On "new issue" screen  (where #1264 is also happening), add a title and content text.  Click create epic button.
On create epic screen, select some issues.
Click the create epic button.
The button greys out, and its text changes to "Creating".

Then it sits there.  Indefinitely.

I opened my dev console and retried it.  No network request sent on click, so I'm unsure what it's waiting for.

This is pretty bad.  My first day trying out Zenhub.  The new issue button doesn't work.  The new epic button doesn't work.  Unsure how a release could go out with broken core features. Maybe it's an issue with the chrome version being incompatible with the latest extension version?

**Comment by kendramoroz** [comment]
@a-laughlin Hey Adam, sorry to hear your first day hasn't turned out so well! We're releasing a fix for the new Issue button not submitting so this should be live shortly. There was some recent UI changes to GitHub that impacted the modal and our team was able to jump on them today to ensure a same day fix got shipped! I'll add a note here once the new extension version is published so you can do a manual update to get the buttons functional once more. 

You can also head to app.zenhub.com where the Modal is working as expected to bypass the button issues in the extension while we get the fix released.

**Comment by kendramoroz** [comment]
Fix is live! To force an update, if you head to `manage extensions` and turn on Developer mode, you'll see an option to manual update your extension:

<img width="775" alt="screen shot 2017-10-11 at 4 37 25 pm" src="https://user-images.githubusercontent.com/11036230/31472307-c816ccba-aea2-11e7-9c9c-b34fb72aa21a.png">

Please let us know if you're experiencing any other issues!

**Comment by a-laughlin** [comment]
Ohhh.  Okay.  The extension depends on the structure of the github page.  That sounds stressful for you all on the ZenHub team!  Do you get any UI change warnings from Github?

Thank you for the quick turnaround!  I updated the extension per your instructions.  It's working perfectly.  Looking forward to the upcoming keyboard shortcuts!

**Comment by kendramoroz** [comment]
We work closely with GitHub and are always focused on ensuring the best experience possible for our community so we're happy to hear that everything is back up and running for you! Please do let us know if we can help with anything else as you navigate ZenHub 😊
