### ISSUE TITLE
Keep track of issues movements

### ISSUE THREAD

**Issue by hadrienl** [ZenHubIO/support#127]
When someone move a ticket from a pipeline to another, there is no tracking of this information. In Trello, there is a log which keep that "Untel moves #123 from ToDo to In Progress" for exemple. I think it's important to know who make changes on issues.

**Comment by azenMatt** [comment]
adding feedback from #234 that it would also be useful to see the story point estimates here

**Comment by Yog** [comment]
following discussion from #234 I think it would be also usefull to have all Pull Requests land in a specific column on the board. 
In my project we have a column specifically for tasks which are waiting to be merged in a pull request, so we manually drag the tasks there, while we could have this done automatically. 
Of course there are tasks and PRs tracked separately by the zenboard. It would be enough if the PRs landed automatically in a separate column, instead of the first one, then from this PR it would be easy to go to its task too. 

You can also go further and have a way of connecting tasks with pull requests.

**Comment by azenMatt** [comment]
Hi all, 

We just added this into v2.14.2 - so you can now see the pipeline and estimate changes in the body of an issue, like you can with milestone/label changes: 

![image](https://cloud.githubusercontent.com/assets/7584089/12186262/dba9cc34-b555-11e5-87b8-ed7d74963e88.png)

At the moment, this is only shown once the page has had a chance to re-load, but we will be making it real time as a next step (the same as how label changes are) 

enjoy!
