### ISSUE TITLE
Repositories using ZenHub

### ISSUE THREAD

**Issue by saketrule** [ZenHubIO/support#1281]
This is not an issue, but a query.  I'm trying to get a list of projects using ZenHub to show how It helps their development. Is it possible to identify if a project uses ZenHub? Or maybe if you have a list of repos using ZenHub, it would be great if you could share it with me. Thanks

**Comment by kendramoroz** [comment]
Replied to your email, @saketrule!

**Comment by fscheidt** [comment]
Hello, I also have the same question. Could you replay me the answer above? Thank you.

**Comment by kendramoroz** [comment]
Hi @fscheidt - To gather custom insights, you can leverage our API endpoints, paired with GitHub's to craft a custom report based on engagement with the endpoints. You can explore our API docs here if you're interested: https://github.com/ZenHubIO/API

**Comment by fscheidt** [comment]
Hello Kendra,
I am currently developing my phd thesis on mining public software
repositories hosted on github. I would like to know if zenhub provides
access to public data from repositories that are public in gihub? I've
checked the zenhub API and it's great because it delivers exactly the data
I need. In the meantime I need to know if the zenhub API gives me the list
of all the public repositories that have zenhub account and also access to
the data of the development process?
Thanks in advance
