### ISSUE TITLE
Drag and Drop functionality not working in Firefox

### ISSUE THREAD

**Issue by Npahlfer** [ZenHubIO/support#1308]
The drag and drop functionality is not working in Firefox 58.0b6 (64-bit) (Firefox Developer Edition).
It results in the issue being selected and grayed out.

<img width="272" alt="screen shot 2017-11-28 at 11 41 08" src="https://user-images.githubusercontent.com/1068840/33315586-62d2cf2a-d431-11e7-95ab-661592a692fd.png">

**Comment by kendramoroz** [comment]
Hey @Npahlfer thanks for the bug report! We currently don't officially support developer editions of Firefox or Chrome (Canary), which is why you might see some rendering issues like this appear. We currently support the latest official build of Chrome, Firefox (57), Edge (Web app only), and Safari (Web app only). Let me know if you are experiencing this on our supported browsers and we'll dig in to further debug 🕵️‍♀️
