### ISSUE TITLE
Can't set assignee, labels, pipeline, estimate, etc on any issue

### ISSUE THREAD

**Issue by kaitlynbrown** [ZenHubIO/support#1324]
Since today, I have been unable to change any of the values on the right-hand side for any issue, including when trying to create a new one. The image below is what I see when attempting to create a new issue from the board tab.
![image](https://user-images.githubusercontent.com/1388240/34698603-e282a2a0-f48d-11e7-9048-de03bf6ee79b.png)
When trying to create an issue from the Issues tab, nothing at all appears to the right of the text box
When inspecting existing issues, the existing values are there, but cannot be changed:
![image](https://user-images.githubusercontent.com/1388240/34698689-46fca730-f48e-11e7-803f-3666d13d0fee.png)

**Comment by kendramoroz** [comment]
Hey @kaitlynbrown thanks for getting in touch! Sounds like your access permissions might have changed from write to read. Can you confirm with the administrator of your GitHub account that you have pull/write access to the repository where these Issues belong?

When you have write permissions, you should see the cog icon appear next to each section, making it so that you can interact like this:

![image](https://user-images.githubusercontent.com/11036230/34698856-3624119a-f48f-11e7-88da-6b89ed57981c.png)

If your access got changed to read, but then gets re-updated to write, the permissions will cache for 3 hours. To force a refresh, you can revoke access to ZenHub [here in your Authorized oAuth settings](https://github.com/settings/applications) and then refresh via the web app, or refresh and click on the extension icon in your browser to log back in and re-authenticate.

Once you get confirmation of permissions, let me know! If nothing changed with your permissions, mind opening up the developer console and sharing any errors that come up (if at all?) If you're unfamiliar with the console, right click and select `inspect` from the dropdown, then navigate to `console` (second tab) in the in-browser window that appears. 

Let me know!

**Comment by kaitlynbrown** [comment]
It looks like my permissions were indeed changed somehow. The issue is resolved now. Thank you :)

**Comment by kendramoroz** [comment]
My pleasure, GGreat to hear it was just a permission change! If anything else comes up, you know where to find us 💯 !
