### ISSUE TITLE
Adding Additional Estimate (Complexity) Numbers

### ISSUE THREAD

**Issue by mjfarr** [ZenHubIO/support#1336]
Hi All - is there any way that we can add additional numbers to the Estimate or Complexity function for individual issues?  At the moment you're confined to the set of numbers that follow the Fibonacci series, but we'd like to be able to manipulate this for our teams if possible.

Please let me know,
Mike Farrell

**Comment by Startouf** [comment]
Hello I would like to highlight this issue as it would be a groundbreaking feature for us to have both time and complexity estimations.

We are working with kanban-like workflows, but in order to provide some estimates for our product owners, and schedule some realistic milestones, we need to time-estimate some of the issues in the TODO pipeline. We are currently using time-estimations instead of complexity estimations so we can quickly look at how long digging each pipe/series of issue would take.

During kanban retrospectives, our report graphs made using issue time estimation do not really reflect what we'd like to actually report : although time estimations are useful for project scheduling what we are also more is how well did we perform in terms of feature VS bug ratio.

**Comment by kendramoroz** [comment]
👋  Hey everyone! I have lovely news for you - you can customize Estimates to other numbers outside the Fibonacci sequence 💥 !

To add a new story point option, type the value you would like to add as an estimate. This will prompt you to create a new value.

![image](https://user-images.githubusercontent.com/11036230/35459037-885a38f6-0293-11e8-9954-99d25773459d.png)

If you don't use the default values at all, you can delete an existing story point option from the list by hovering over the story point. Clicking the trash can that appears on the right of the story point will remove it from the list. ⚠️  Deleting the story point **will permanently un-assign the estimate across all Issues where it has been assigned.** So if you've already used those values, be sure to talk with your team before permanently deleting a story point option.

![image](https://user-images.githubusercontent.com/11036230/35459139-d7120cb2-0293-11e8-9c45-1ab9ce38f297.png)

And if you didn't know about the sort by estimate option, you can also sort each pipeline on the ZenHub Board by story points. Click on the `Sort pipeline` option and select `Estimate` to get a complete picture of the estimates of most Issues in the workflow.

![image](https://user-images.githubusercontent.com/11036230/35459124-c1476efe-0293-11e8-9792-63e3dcb9934f.png)

---

@Startouf While this doesn't help with time estimation, you can follow along #69 for updates on time estimation. Kanban reporting is something we're exploring, so your feedback is really helpful here! 

---

Let me know if there's anything else on this Issue that I was missing based on the context above 🎉

**Comment by mjfarr** [comment]
THANK YOU @kendramoroz! You're a life saver!!!!

**Comment by kendramoroz** [comment]
🎉  Glad it was helpful!

**Comment by Startouf** [comment]
@kendramoroz should I open a new ticket regarding my specific comment about 2 estimations ?https://github.com/ZenHubIO/support/issues/1336#issuecomment-360720798

Basically the idea was to have 2 sets of estimations co-existing : one for a time-based estimation and one for a complexity estimation (or maybe an "added value estimation", whatever makes sense for the team).
