### ISSUE TITLE
Add issues to an Epic from a repository disconnected from the Board.

### ISSUE THREAD

**Issue by paulafei28** [ZenHubIO/support#1346]
I would like to know if it's possible to Add the issue to an Epic that is not connected to its Board. For example, I have an issue from the repository A and want to associate it to an Epic from the repository B, but the Board from this repository B is connected to a third Board.

**Comment by kendramoroz** [comment]
Hey @paulafei28 great question! Currently Epics are built from Issues within the multi-repo Board workflow. If Repos A and B are in a multi-repo Board, they can be combined under the same Epic. However, if the repos are disconnected, they can't yet be added under the same Epic. As part of #139 we're working on delivering project views, which can be built with multi-repo Boards where multiple Boards can exist and multiple projects views can be made using various filters, including Epics, so this might help with your use case once this is live! Check it out and let me know :). Otherwise, I'm bumping this over to discussion to ensure we don't lose track of this request!

**Comment by paulafei28** [comment]
Thank you very much, Kendra. Looking forward to have this enhancement live.

**Comment by kendramoroz** [comment]
Closing in favor of 139, please subscribe there for updates on the go-live date for workspaces!
