### ISSUE TITLE
Auto transition in pipeline

### ISSUE THREAD

**Issue by artigat1** [ZenHubIO/support#136]
Would be nice to automatically move an issue to the `In Testing` pipeline when the PR is merged to QA. Similarly, transitioning the issue to `Done` when the PR is merged into Master. Saves people (who usually aren't the developers) remembering to move issues, when release management aren't really using Zenhub.

**Comment by aupright** [comment]
Hey @artigat1 - Aaron here!

As it doesn't look like we're getting any more feedback on this one, I'm going to close this issue and re-direct the discussion over to #172. The functionality that you described above is something that we're hoping to offer support for in a publicly documented ZenHub API—a feature we're still exploring. 

Thanks again for your feedback here!

**Comment by joelhooks** [comment]
I'm going to add my comment here instead of on #172 because what I'd like is simpler (at least for me :stuck_out_tongue_winking_eye:).

My strong desire would be to have simple tags on commits trigger issues to transition.

`[(Finishes|Fixes|Delivers) #ISSUE_ID]`

To facilitate a workflow like the one [outlined in this article using Pivotal](http://pivotallabs.com/level-up-your-development-workflow-with-github-pivotal-tracker/)

**Comment by jakirkham** [comment]
Personally, I would find this nice for backlogging issues. In particular, if there is a PR that has stalled out for some fixed amount of time (e.g. a week), I want it automatically moved to the backlogged pipeline. This way, I can see what things need to attention and haven't been getting any.
