### ISSUE TITLE
Updated label names not reflected correctly in the board filters

### ISSUE THREAD

**Issue by toukoe** [ZenHubIO/support#1364]
I updated the names of a few labels, however still a few days later it's not reflected properly on the board. Both the old and the new name are visible in the label list & some issues have the old label, some the new.

**Comment by kendramoroz** [comment]
Hey @toukoe thanks for getting in touch - doesn't sound like normal behaviour! Do you have access to the `Settings` tab in the repository where you're noticing things not get updated? If so, can you head to Settings > Webhooks and make sure that you see a similar URL for ZenHub Webhooks and let me know if it's otherwise missing?

![screen shot 2018-03-01 at 10 47 42 am](https://user-images.githubusercontent.com/11036230/36863361-56df3360-1d3e-11e8-9ec8-a5ba59b316cd.png)

**Comment by toukoe** [comment]
@kendramoroz It's actually fixed now and works as should, 4 days later. I don't have access myself but will chase some folks who have so we can check if the settings are wrong. Anyways it seems to be working now so can close the issue.
