### ISSUE TITLE
Deleted Github Issue still showing in ZenHub Board

### ISSUE THREAD

**Issue by njsokol** [ZenHubIO/support#1396]
An issue was opened and placed into the WIP column.
It contained secrets that I did not want to share.
The issue was deleted in Github.
ZenHub is still showing the issue in the WIP column.

Can anyone provide insight on how this is still possible? GitHub shows no trace of the issue, but ZenHub still manages to "see" it?

**Comment by azenMatt** [comment]
Hi @njsokol - we also had a note from your GHE admin on this and are working with them on a resolution. 

It looks like as delete isn't an official GitHub issues event they don't send us an update for it so our cache is out of sync. 

This cache is only the information to display the issue on the board (issue number, title, etc) so any of the sensitive content mistakenly added to the issue is not saved. 

A workaround for this is to make an edit to a label (name, colour) from the same repo which will cause a cache refresh

**Comment by njsokol** [comment]
Awesome! Kind of a hack, but hey it works! Thank you for the quick response!
