### ISSUE TITLE
Old releases visible when creating new issue, not visible in filter

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1403]
Create new issue:

![image](https://user-images.githubusercontent.com/490562/38539578-e15c85d8-3cec-11e8-9483-d4bd9152aa74.png)

Filtering on home page:

![image](https://user-images.githubusercontent.com/490562/38539596-f39e10f4-3cec-11e8-896f-0149db9a3361.png)

The 1.5.2 release is not visible here.  Seems like a discrepancy.

**Comment by kendramoroz** [comment]
Hey @adamreisnz thanks for writing in - this is expected behaviour, as long as nothing on your Board currently that is open belongs to the 1.5.2 release. The filters on the Board will show only what is actually searchable - if there are no issues assigned to 1.5.2 that are still open, and on the Board, it won't show (unless you enter multi-action, where it becomes an assignable release, and should appear as an option in the assign modal). 

When creating a new issue, it's also an assignable option, as an open Release, which is why it shows here! 

Closing as this is expected behaviour, but don't hesitate to ping me back with any questions!
