### ISSUE TITLE
Pull request is shown as issue in zenhub application

### ISSUE THREAD

**Issue by inyee786** [ZenHubIO/support#1416]
i have found that pull request is shown as the issue in zenhub application

while i was seen github api, found that , all the issue and pull request are the issue come under issue

the solution might be check if   typeof pull_request == undefined then it is issue and if not then it is pull request

**Comment by azenMatt** [comment]
Hi @inyee786 

This is by design - so that teams who would like to run their PR's through the same workflow can. 

If you would like to see only Issues on your ZenHub board, you can turn filter them off here:

![image](https://user-images.githubusercontent.com/7584089/39140939-ff950366-46da-11e8-9562-33f5a7606c9e.png)

**Comment by inyee786** [comment]
thanks for the info @azenMatt
