### ISSUE TITLE
When creating a report, epic points aren't taken into account, only story points are

### ISSUE THREAD

**Issue by mgibson91** [ZenHubIO/support#1433]
I have seen this with multiple epics so far. They each have either nested issues with time estimates or nested epics which in turn have nested issues with time estimates.

When I add these epics to a release generate a report, I see the nothing but a message next to each epic saying 'Not estimated'. I go into each epic and the cumulative time estimate is indeed specified in epic points.

If I then, explicitly specify the same number of story points in the epic. It then displays correctly in the report.

Unfortunately, this reporting forecasting feature is one my primary using for using Zenhub. I could be missing something but yourself if you add an epic, you want the underlying sub epics and sub issues to be taken into account through the epic points?

The fact it says 'Epics, Issues and Pull Requests' makes it seem that Epics are expected to be added?

**Comment by mgibson91** [comment]
Is the intended usage to add each issue to a release?

**Comment by kendramoroz** [comment]
Hey @mgibson91 - Currently Epic points represent the sum of all estimated Issues, but isn't an actual estimate applied to the Epic Issue, which is why the Reports aren't picking up on the Epic. Since an Epic can contain many thematic Issues that aren't necessarily being prioritized and worked on, we originally left Epic points out of the reports when Epics get added as you may have Issues in that Epic that shouldn't actually count towards a Milestone or Release. Being able to add Epics for tracking of key projects to enhance the Release filtering is currently supported.

![image](https://user-images.githubusercontent.com/11036230/41883835-66a4d922-78a5-11e8-94fe-1e4d2cef4026.png)

Being able to customize this and leverage Epics more powerfully in reports by adding automatic syncs between epic points and the Release without having to add individual Issues is on our radar, but not currently in the hopper as we are diligently working on #139, which will enable us to move towards more robust automation features!

Let me know if you have any further questions on this one!

**Comment by kendramoroz** [comment]
Closing to consolidate with https://github.com/ZenHubIO/support/issues/1107 - feel free to subscribe there for any updates regarding automation coming down the hopper related to epic points 😊
