### ISSUE TITLE
Show milestone on a card

### ISSUE THREAD

**Issue by chibicode** [ZenHubIO/support#146]
On GitHub's issues page, the milestone for an issue is displayed:

![image](https://cloud.githubusercontent.com/assets/992008/4851243/d1d2eabe-6070-11e4-8ba1-32db09fc8f94.png)

I'd like to see this displayed on a card also.

![image](https://cloud.githubusercontent.com/assets/992008/4851265/04f7f59c-6071-11e4-8f14-5aa1365ffd10.png)

**Comment by ni-ka** [comment]
@roham any update on this? it's a feature we're used to from waffle.io

**Comment by roham** [comment]
@ni-ka no updates yet: many users like the compact nature of the cards because it gives a great overview of the project status. Filtering and the issue popup modal can be used to do deeper dives. That said, there are upcoming improvements over the next few months that you will enjoy – more performance, so you can jump in and out of issues faster, but also alternative board views that will let you slice and dice your workflow however you wish. When we tackle the latter we'll also take a look at the UX for displaying more information directly on the board itself.

**Comment by Tlvenn** [comment]
Any update on this ? Is there any chance that we could simply customize how much information we want to see on cards ? That would make everyone happy ;)

**Comment by azenMatt** [comment]
Hi @Tlvenn - no updates right now - we are currently working on a number of performance updates to load the board faster. Once we have these in place and are happy with the rendering time, we will be coming back to look at what other information we can add to these cards.

**Comment by RodneyTurnham** [comment]
:+1:

**Comment by Tlvenn** [comment]
Thanks for the udpdate @azenMatt

**Comment by azenMatt** [comment]
This has been added in v2.23.17

![image](https://cloud.githubusercontent.com/assets/7584089/17795647/11d4d762-656f-11e6-85c7-14a906f4b7b1.png)
