### ISSUE TITLE
Copy URL for issue results in "a minute ago" in clipboard

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1486]
![image](https://user-images.githubusercontent.com/490562/44287761-0ec5cf80-a2c2-11e8-8831-e1e0b244c8ee.png)

Paste: `a minute ago`

Looks like the wrong attribute is copied.

**Comment by kendramoroz** [comment]
👋 Hey @adamreisnz can you share more about in ZenHub where you're seeing this pasted wrong? Thank you!

**Comment by adamreisnz** [comment]
See screenshot, when you click on an issue in Zenhub and then on the right hand side on top you click on the 3 dots and select Copy URL, then paste anywhere.

**Comment by kendramoroz** [comment]
Thanks, @adamreisnz - the screenshot is from GitHub so just wanted to ensure that you're viewing this behaviour in ZenHub as well.

**Comment by adamreisnz** [comment]
No, it was taken from inside the Zenhub edit issue modal.

**Comment by kendramoroz** [comment]
Thanks for clarifying! I'm unable to replicate, unfortunately. It currently shows 'just now' on my end. I'd recommend testing if this still occurs for you without the extension installed—Because this is the GitHub UI and we port this in, rather than modify it, I suspect that this might be a GitHub bug! 

![image](https://user-images.githubusercontent.com/11036230/44416773-b93f2c00-a528-11e8-928d-91c3bdd57f02.png)
