### ISSUE TITLE
Closed issues should also be sortable

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1496]
For some reason, the sorting options are not available for Closed issues. That would be extremely useful to have. 
e.g. for seeing how much got done the last sprint or the last week.

**Comment by bengerson** [comment]
I agree, also having the multiple select of issues there would be good.

**Comment by bmunkholm** [comment]
Alternatively, add an option to display the close date in the issues, so I can see what got done since during the sprint.

**Comment by kendramoroz** [comment]
Hey all - At the moment, we do not have plans to make the closed pipeline sortable so I'll be closing this Issue for transparency. The closed pipeline only loads the last 50 closed Issues across all connect repos to manage the rate limit / performance of many, many closed Issues loading during Board load. Because of this, it makes it too complex to add meaningful sort that wouldn't further break the experience to this pipeline. 

For viewing Issues closed in the Sprint, the Burndown chart is a great place to look! It breaks out closed Issues within the Milestone :) Here's an example:

![image](https://user-images.githubusercontent.com/11036230/47688055-b142de80-dba0-11e8-81d3-6471009f5a87.png)

Hope this helps add clarity!

**Comment by bengerson** [comment]
ok @kendramoroz just that you know my use case: I would somehow like to search for issues (that are closed) by release, select all of them at once and label them.

Maybe you can consider this function for the release report. Generally a list view of all the issues would be very helpful for some quick filtering, selecting and relabeling. The issue search provided by GH sadly does not help as I cannot search/filter by Zenhub releases there.
