### ISSUE TITLE
Burndown Chart Question

### ISSUE THREAD

**Issue by katetcro** [ZenHubIO/support#1504]
Hi! I am having trouble generating the Burndown Chart for our last sprint (Killeen) starting on August 22 - September 4. When I filter one repo (TBoxTour for example) and select burn pipelines to "done" - the chart looks the same as showing all repos. I've attached two screenshots of the issue below:

![screen shot 2018-09-05 at 5 36 42 pm](https://user-images.githubusercontent.com/42621838/45123092-c4eb3f00-b133-11e8-94f9-6f782652c91c.png)
![screen shot 2018-09-05 at 4 56 48 pm](https://user-images.githubusercontent.com/42621838/45123093-c4eb3f00-b133-11e8-935a-563d05f42e94.png)

Thanks in advance for your help!

**Comment by kendramoroz** [comment]
Hey @katetcro we have a known bug that causes the label filter to not work on the burndown! We have a fix in code review at the moment :) - I'll post back once it's live!

**Comment by katetcro** [comment]
Hey! Great, thank you so much for getting back to me so quickly.

Separately - I have a question about generating a report. I’m wondering if possible to create a burndown report (or something similar) for each individual throughout the sprint - so we can track everyones progress every day. 

Thanks again!
Kate

**Comment by annabelleglass** [comment]
Hi @katetcro 👋 

Good news! The release is now live and ready to go 🚀. Please try updating the extension to see if your burndown charts are now behaving as expected. If you are running into issues after this update please let us know and we would be happy to help. 

In regards to your second question: Currently, the Burndown in ZenHub is team-oriented and doesn't drill down by individual. Best practices when using estimation is to look at Burndowns and Velocity by team, not by individual as story points should be the same regardless of who in the team is looking at them (which is why they are often preferred over time estimation!). Looking at team velocity and completion within the Sprint helps conversations focus on continuous improvement, where everyone can head together, and areas of bottlenecks that might be impacting everyone, or process hiccups that might be slowing everyone down. 

At the moment we don't have any immediate plans to modify this workflow to include individual reporting, but understand that this might not make sense to all team's workflows. If there are any other questions we can help with, or if anything else crops up please feel free to give us a shout at support@zenhub.com 😄 

Best, 

Annabelle
