### ISSUE TITLE
Cumulative flow bug: blank window when selecting repos

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1545]
When clicking the repo selector in the new Cumulative flow view, the window just blanks.
Try clicking "Repos" in this repo: https://github.com/realm/realm-cocoa#reports?report=cumulative

![image](https://user-images.githubusercontent.com/1215687/47432727-27a9a000-d79f-11e8-9a32-71b1535c81a1.png)

**Comment by kendramoroz** [comment]
Hey @bmunkholm this is unexpected! Would you be able to book some time: https://calendly.com/zenhub/quick-chat so we can walk through this? In the meantime, mind also sharing a console screenshot?

**Comment by kendramoroz** [comment]
👋 Because this is a public repo, we're going to debug on our end in the meantime. We'll post back once we have more prior to a call!

**Comment by bmunkholm** [comment]
Thanks Kendra. I'm in Europe, so a tad inconvenient now with a call. Can you repro?
Unfortunately there is no option to see Cumulative flow on this repo for some reason :-)

I'm using latest Chrome Version 70.0.3538.77 (Official Build) (64-bit).

**Comment by kendramoroz** [comment]
👋  We were able to lock-in a cause! The team can access the repo because it's public :) - if the chart doesn't load, we've identified a bug that if any one of the connected repos you don't have access to, it prevents loading - it should still render, but exclude those where permissions don't exist. 

On the repo switcher side, we were also able to repo. 

No need for a call just yet! We will post back once a fix is live.

**Comment by rupachup** [comment]
@kendramoroz is this Cumulative Flow report not available to everyone yet? I can't find it...

**Comment by kendramoroz** [comment]
@rupachup It's currently only available to select organizations in a smaller beta launch. if you share your GitHub organization name I can have it enabled for your team 😊

**Comment by rupachup** [comment]
@kendramoroz our ZenHub board has ten GitHub orgs on it - creative-commoners, silverstripe, silverstripeltd, open-sausages, dnadesign, tractorcow-farm, symbiote, bringyourownideas, firesphere & elliot-sawyer

**Comment by kendramoroz** [comment]
@bmunkholm we fixed the issue 🎉 You should now be able to use the repo switcher without it breaking. 

You're going to want to clear your local storage otherwise if you don't have permissions to all repos you'll see UI behaviour that looks like this:

![image](https://user-images.githubusercontent.com/11036230/47467617-2fbc0c80-d7ac-11e8-9d4a-d7c04172206c.png)

**Here's the steps to clear your storage:**
Open up the chrome dev tools, head to `Application` click on the github link on the left side, then click on the do not enter looking icon (step 3). Then, refresh the page.

![image](https://user-images.githubusercontent.com/11036230/47467599-1915b580-d7ac-11e8-87c2-215feb41ac4a.png)

---

@rupachup enabled across all those organizations 🎉

**Comment by bmunkholm** [comment]
@kendramoroz Thanks for the quick fix! That helped!.
