### ISSUE TITLE
Cannot add milestone to issue.

### ISSUE THREAD

**Issue by jasonwyatt** [ZenHubIO/support#1557]
This seems new today. I'm having trouble setting the milestone on an issue. I set it, everything looks fine in the UI, then it never updates the kanban board nor is it there if i hard-refresh the page.

**Comment by kendramoroz** [comment]
👋 Hey @jasonwyatt GitHub is having delays with data (https://status.github.com/messages) which is causing this. Because we rely on the GitHub API for Milestone updates, we've isolated this to the status outages occurring. You should see this behavior go away once GitHub green lights once more! I'll leave this open until we are able to confirm after everything gets green-lit on GitHub's side.
