### ISSUE TITLE
Disconnected from the board after 30 seconds

### ISSUE THREAD

**Issue by jrochel** [ZenHubIO/support#1589]
I've had this problem for months now. When I'm on the board I have something between 30 seconds and 3 minutes before I get disconnected. This is indicated by a small popup in the bottom right corner of the screen that says "Disconnected." Otherwise I don't receive any errors on the console.

This occurs with Firefox 57 on Linux with a fresh user profile.

**Comment by gconan** [comment]
Firefox v 63.0.3
Happens to me too, but consistently every 10-30 seconds. One repo, 41 total issues

**Comment by kendramoroz** [comment]
👋 To ensure this support ticket gets properly assessed and triaged, please submit a support ticket to support@zenhub.com with the following details:

- Your GitHub organization name:
- The URL of the repo that this is occuring on, from the ZenHub Board:
- Your GitHub username:
- A screenshot of the console when this is occurring (ideally in Chrome), alongside any failed network requests (to troubleshoot both of these and understand what screenshots will help us debug, [you can follow this guide here](https://help.zenhub.com/support/solutions/articles/43000457957-troubleshooting-in-zenhub-gathering-info-in-the-console-network-tab)):
- Confirm that you do not have any ad blockers or extension that otherwise block webhooks, like Ghostery (best to try ZenHub in a clean profile where there's no other extensions to rule out interference)
- And confirm that you do not have a dynamic IP wifi address (this prevents webhooks from connecting, causing disconnections. [More on this here under](https://help.zenhub.com/support/solutions/articles/43000010362-zenhub-board-cannot-be-loaded) `Your wifi settings use a dynamic IP`)

Thank you!
