### ISSUE TITLE
"All Repos" Seems to be Broken

### ISSUE THREAD

**Issue by dprior** [ZenHubIO/support#1592]
This morning members of my team have visibility to a random single digit number of repos. We have a total of 35 connected to ZenHub. Is this a known side effect to an update you guys did over the weekend?
![screen shot 2018-12-17 at 10 04 17 am](https://user-images.githubusercontent.com/4315923/50099424-b658fd00-01e3-11e9-92f5-e84da783749c.png)

**Comment by reedstrm** [comment]
+1 I'm in a completely different org than the person above, and had the same issue. I worked around it by opening github taba for every single repo, then hitting the zenhub app tab - it would then add _just that repo_ to my view of the board, if that repo was on that board.

**Comment by reedstrm** [comment]
Not sure if it's related, but I can't seem to _add_ additional repos to the boards.

**Comment by kendramoroz** [comment]
Hey everyone - to ensure proper triage of support versus features, please if you could please get in touch via support@zenhub.com with as much of the info below as possible, we can confirm the cause of any support-related issues and triage feature requests separately. This will ensure your support ticket gets triaged and responded to timely.

Here's the additional data that we need if you're experiencing Issues accessing ZenHub:

- Your GitHub organization name:
- The URL of the repo that this is occurring on, from the ZenHub Board:
- Your GitHub username:
- Are you working through the web app or extension?
- If extension, ensure you're on the latest number by forcing an update and see if this fixes the issue. You can force an update by turning on `developer mode` on the top right of manage extensions, and using the `update` button. If you're unsure, send through your extension version number.
- A screenshot of the console when your error is occurring (ideally in Chrome), alongside any failed network requests (to troubleshoot both of these and understand what screenshots will help us debug, [you can follow this guide here](https://help.zenhub.com/support/solutions/articles/43000457957-troubleshooting-in-zenhub-gathering-info-in-the-console-network-tab)):
- Confirm that you do not have any ad blockers or extension that otherwise block webhooks, like Ghostery (best to try ZenHub in a clean profile where there's no other extensions to rule out interference)
