### ISSUE TITLE
Timestamp returned from GitHub API is not updated when a ZenHub feature is updated

### ISSUE THREAD

**Issue by vila89** [ZenHubIO/support#1604]
:wave: When I make a ZenHub feature (Pipeline, Epics, Estimates, Release) change on the GitHub Issues screen, GitHub shows the activity or change on the UI screen. However, the "updated_at" field returned from GitHub API doesn't reflect the latest timestamp.

**Comment by kendramoroz** [comment]
Hey @vila89 Thanks for getting in touch! This repo is sunset (we're keeping it on to let people know where to get in touch as we transition). You can reach us at anytime via support@zenhub.com or view our resources page [here](https://help.zenhub.com/support/discussions) for other helpful touch points. 

With the specific issue you pointed out, because ZenHub metadata doesn't touch the GitHub updated API, we can't update the GitHub timestamp. The team has noted a feature request to add a last ZenHub update. Hope this clarifies things!
