### ISSUE TITLE
As a business user of Github, I want to be able to preview files that are uploaded

### ISSUE THREAD

**Issue by RickCogley** [ZenHubIO/support#176]
Business users can easily figure out how to use the kanban board. However, Github is naturally technical, and thus somewhat opaque to non-technical users. Even if HR documents or company policies are kept, the nature of Github will likely pose a bit of a barrier to adoption, for business users. 

Zenhub could create plugins to act as viewers for certain types of file uploaded to the repository. The idea behind such plugins (or additions to your existing code) would be to try to make it easier for users to get a quick preview of the file they are interested in.

If the file is covered (like XML or HTML or markdown for instance), the Zenhub utility could inject code that presents a file viewer popup, allowing a user to get an idea of the content.

**Comment by aupright** [comment]
Hey @RickCogley - interesting suggestion here! 

As more of a business user myself I've lived through a few of these problems and can see how GitHub's interface can pose a bit of a barrier to adoption. That being said, I'm not sure if the solution here is to simplify the process by integrating a file preview system (as per your suggestion) or to improve the on-boarding flow for new users to help them feel more comfortable in the interface.

Regardless, I think that this will provide some great fuel for an internal discussion amongst our product team. We're always looking to make the process easier and more intuitive for our users - if you think this is something that would help, we're definitely open to exploring it further and discussing about if/how we might integrate this into our product roadmap going forward.

I'll move this issue into the community backlog so that we can try and generate some more discussion around this user story! Thanks again for the comments.

**Comment by RickCogley** [comment]
Thanks @aupright. Indeed, better onboarding would be a solution in some ways. I can also play devil's advocate against myself, and say that "there's never any way a business user should be using Github". But in reality, there will always be managers involved in a project who are in charge of clearing blockages and getting money to flow, so, there will always be a need to accommodate to a certain extent. Especially if the idea is to use Github for all aspects of a project.

**Comment by azenMatt** [comment]
Hi @RickCogley - I am closing all the file upload related issues as we depreciated our file uploader today in favour of GitHubs
