### ISSUE TITLE
Toggle labels to reduce vertical space used

### ISSUE THREAD

**Issue by robinzimmermann** [ZenHubIO/support#183]
Labels are shown on the bottom of the cards, which is nice. But they can take up valuable vertical space. It would be beneficial to be able to toggle the display the of those labels for times you want to fit more issues on the screen.

We are reticent to use labels, even though we want to, because of the significant vertical space we would lose.

**Comment by robinzimmermann** [comment]
Right now we can work around it by adding a bookmarklet to the bookmark bar with this:

```javascript
javascript:(function(){$(".zh-issue-meta").toggle();})()
```

I set the label to "Toggle ZenHub Labels". Clicking it will alternatively hide and show the labels quickly.

It would be nice if this were in the tool itself, though.

**Comment by aupright** [comment]
Hey @robinzimmermann - thanks for posting this here as well!

We actually used to offer users the ability to switch between a normal view of the board (without labels) and an advanced view of the board (with labels). As most of our users preferred working in the advanced view, we ultimately decided to pull the feature and keep the real-estate open for future use. 

If you'd like to show your support, there's actually another open issue for discussion around this feature (see #116) - feel free to add a +1 there. I'll keep this issue open for now so that other users have a chance to see the bookmarklet that you created.

**Comment by Mottie** [comment]
I created a userscript that allows toggling of the issue meta data (labels). Check it out here: https://github.com/Mottie/ZenHub-userscripts#zenhub-toggle-meta

Click on the label icon to show or hide the pipeline meta data (labels & other data)

![zenhub-toggle-meta](https://cloud.githubusercontent.com/assets/136959/13901479/04dbfeb2-edf3-11e5-9e97-467fd929907c.gif)

**Comment by Mottie** [comment]
The latest update broke this userscript. Every card in a pipeline is now absolutely positioned with a fixed height 😢. So even with the meta data hidden, the cards remain the same height. I don't know if I'll update the script since it would require recalculating the height and position of every card.

**Comment by kendramoroz** [comment]
@robinzimmermann @Mottie Happy to announce that we've launched **Board View Settings** where you can now customize your board view! If you don't see the **View** button left of the repo filter, a quick re-install of the extension will bring you up to the latest version with this option. 

Look forward to hearing your feedback on the latest enhancements to the board 🎉 

![screen shot 2017-01-31 at 10 19 17 am](https://cloud.githubusercontent.com/assets/11036230/22478479/dc89c7c2-e79e-11e6-852c-496f8912fbaf.png)
