### ISSUE TITLE
Native github 'go to issues' keyboard shortcut bug

### ISSUE THREAD

**Issue by benjaminwood** [ZenHubIO/support#189]
When on the 'boards' page, pressing `g + i` doesn't take you to the normal github issues view like it should.

Cool product by the way.... I'm evaluating it for the first time right now.

**Comment by aupright** [comment]
Hey @benjaminwood, thanks for the comment!

I took a closer look into this one, and it appears as though pressing `g + i` still takes you to the issues view, however the view is hidden behind the boards. I'll issue this up internally so that we can look to create a fix for this. Thanks again for the feedback!

**Comment by azenMatt** [comment]
Hi @benjaminwood - this is now resolved in 2.5.16, which we just put live!

**Comment by benjaminwood** [comment]
Cool, thanks for the update.
