### ISSUE TITLE
Scrum Story Pointing System

### ISSUE THREAD

**Issue by alanjames1987** [ZenHubIO/support#190]
In scrum a team assigns points to a user story and usually use scales like tee-shirt sizes or the Fibonacci sequence.

Since using ZenHub I have been missing the ability to point stories with my team.

It would be great if this were added.

**Comment by aupright** [comment]
Hey @alanjames1987 thanks for the suggestion! I think there's quite a few other community members that would find that one helpful as well - myself included.

We currently have another open issue around time estimation that we're using to track all of the different suggestions around this feature. In order to avoid having multiple open discussions, I'm going to move the conversation over there so that we can continue things with the rest of the community. 

Feel free to show your support and add a +1 here: https://github.com/ZenHubIO/support/issues/69

Thanks again for the feedback!

**Comment by alanjames1987** [comment]
Awesome. I will follow that issue.
