### ISSUE TITLE
Clicking on issues

### ISSUE THREAD

**Issue by p-run** [ZenHubIO/support#194]
The clickable area on an issue (to open said issue in github) is 1) small, and 2) not visually marked in any way. This makes opening issues unnecessarily difficult.

Suggestion 1: make the entire issue description clickable. Right now clicking elsewhere on issue description does nothing.

Suggestion 2: indicate better when the cursor is over the clickable area, such as by underlining the description.

**Comment by aupright** [comment]
Hey @p-run, thanks for the feedback!

>Suggestion 2: indicate better when the cursor is over the clickable area, such as by underlining the description.

I like this suggestion as it's less likely to interfere with the click-able area for being able to drag and drop issues around the board. I'm moving this issue to our discussion pipeline in hope that a few other people will add their support and +1. As this should be a pretty simple addition to make, I'll issue it up internally as well so that we can look at building this out. Thanks again for the suggestions!

**Comment by alexchantastic** [comment]
I think a simple hover state on the issue title and number should suffice. Also, adding `display: block` to the `<a>` that links it to the issue so you don't get that nasty gap between lines which is sometimes annoying (and I personally misclick all the time).

**Comment by p-run** [comment]
I am not sure what interference you are referring to as issues can be dragged by grabbing them on links, at least on my machine.

**Comment by azenMatt** [comment]
Love this idea @p-run - in fact we have just implemented suggestion 1 as part of a refactor we are doing so you should see it on production very soon - cc @geoffrey :beers:

**Comment by geoffrey** [comment]
Hey @p-run, we just released ZenHub version `1.2.12`.

Now the entire issue card is clickable and will open a new tab for that issue.
Please update your extension and let us know what you think about it.

**Comment by azenMatt** [comment]
Closing as this is live :smile:
