### ISSUE TITLE
Bulk select/edit issues in board view

### ISSUE THREAD

**Issue by alexchantastic** [ZenHubIO/support#199]
It would be great to be able to bulk edit items in board view. The normal GitHub issue list view allows bulk selecting and editing of issues.

In my particular case, I sometimes need to move groups of issues in a certain pipeline from milestone to milestone. Since ZenHub pipelines aren't exposed in GitHub's normal bulk selection, I am unable to do so efficiently.

**Comment by p-run** [comment]
+1, we use milestone, assignee and label editing in bulk on a regular basis.

**Comment by aupright** [comment]
Hey @alexchantastic and @p-run, thanks for the comments!

There have been quite a few requests for this type of functionality from the community, and it's defiantly something that we're looking to explore going forward. There's actually another open issue on our support repo with quite a few comments and +1's already (see #118). It would be great if you could add your support there so that we can keep things centralized :smiley: 

Thanks again for the feedback!

**Comment by cemsbr** [comment]
I can't select closed issues. I want to add them to a release that I've just created.

**Comment by kendramoroz** [comment]
@cemsbr thanks for writing in! This is a known issue, tracked via: #999 - Feel free to follow along there for updates!
