### ISSUE TITLE
Issues in Issues List that have been +1'd once are not very visible

### ISSUE THREAD

**Issue by davidrans** [ZenHubIO/support#205]
This is a picture of two issues in GitHub's Issue List. The first issue **has not** been +1'd, and the second issue **has** been +1'd by another user. They are virtually indistinguishable at a glance:
![image](https://cloud.githubusercontent.com/assets/806152/6567299/9dd5a666-c682-11e4-9da1-973d374fdcf1.png)

**Comment by aupright** [comment]
Hi @davidrans thanks for the feedback on this one!

I've issued this one up internally so that the team can take a look at your feedback and think more around this. In the past, I know that we've considered making the +1's in the issue list more distinguishable by changing the colour to yellow - do you think that would be too stark of a change?

Does the rest of the community have any feedback on colour choice here?

**Comment by davidrans** [comment]
I think I should still be able to distinguish issues that have votes from issues *I've* voted on.  Maybe a subtler coloring?

**Comment by azenMatt** [comment]
we have three different colour effects here: 

grey boarder = no +1's 
black boarder = other people have +1'd 
yellow icon = user has +1'd 

But yes, I agree these are too subtle (especially the black and grey), re-design coming soon! 

![image](https://cloud.githubusercontent.com/assets/7584089/6759860/b82fca6a-cf00-11e4-9a69-1372212ba13a.png)

**Comment by rick-it-2004** [comment]
Hi Matt

How do I stop being spammed by all these emails? There isn't a link in the emails

  Regards Richard 


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Matt Butler <notifications@github.com> </div><div>Date:2015/03/20  7:57 PM  (GMT+00:00) </div><div>To: ZenHubIO/support <support@noreply.github.com> </div><div>Cc:  </div><div>Subject: Re: [support] Issues in Issues List that have been +1'd once are not
  very visible (#205) </div><div>
</div>we have three different colour effects here:

grey boarder = no +1's 
black boarder = other people have +1'd 
yellow icon = user has +1'd

But yes, I agree these are too subtle (especially the black and grey), re-design coming soon!

**Comment by azenMatt** [comment]
Hi @rick-it-2004 

As this is a GitHub repo, all the email notifications are based on your GitHub preferences. 

you can update your preferences here - https://github.com/settings/notifications and also here https://github.com/watching

Personally, I have GitHub set up so that I get emails for any issue I have been tagged in, and web notifications (https://github.com/notifications) for everything else. 

Feel free to email me at Support@zenhub.io if you need any further help with this :smile:

**Comment by azenMatt** [comment]
These are now clearer since we moved away from the yellow branding
