### ISSUE TITLE
Interop

### ISSUE THREAD

**Issue by jbenet** [ZenHubIO/support#213]
waffle.io is a similar product, it would be great to have interop for those users that prefer one or the other (or are totally _constrained_ to one or the other). I wonder if the pipelines of ZenHub could use labels like waffle.io -- that may be enough to have both work together.

**Comment by azenMatt** [comment]
Hi @jbenet - this is a feature on our radar! We are currently tracking this in issue #19 so i am going to close this issue to avoid duplicates. 

I believe you are correct that using these labels would mean you can switch between waffle and ZenHub. 

We initially wanted to avoid using labels as they were existing information in GitHub, so we felt that it made sense to keep them as functionality based information rather than progress information that the pipelines provide. But - it is a highly requested feature so we are having to re-evaluate our early assumptions that users would not want us hijacking their labels :grinning:

**Comment by jbenet** [comment]
> We are currently tracking this in issue #19 so i am going to close this issue to avoid duplicates.

ah sorry, didnt find it.

> we felt that it made sense to keep them as functionality based information

yeah... we wanted that too. I think in general large projects always end up overloading labels' use case (for better or for worse).

>  it is a highly requested feature so we are having to re-evaluate our early assumptions that users would not want us hijacking their labels

Yeah, hijacking labels seemed sketchy to us at first, but then we realized it's likely the best way to do it from an interop / usability / flexibility standpoint. It's also not so bad if the labels get prefixed with `"Progress: "` or something. (we'll give them all the same color)

(no need to respond to this msg)
