### ISSUE TITLE
Add options to make better use of available screen space.

### ISSUE THREAD

**Issue by Ferada** [ZenHubIO/support#227]
The current issue cells are relatively big, which means that with a lot of them screen space is wasted.

<del>One option I've seen elsewhere is to have a toggle for smaller rows (leaving out the tags and other superficial information).</del> [Already suggested here](https://github.com/ZenHubIO/support/issues/183).

Another one would be to have a full screen mode for boards, so that again more of the board is visible.

**Comment by aupright** [comment]
Hi @Ferada, thanks for the suggestion!

One of our roadmap goals for this coming quarter is to offer more functionality directly from the boards view of ZenHub. With that goal in mind, I think your suggestion here makes a lot of sense as a feature that we could explore going forward. Although, I'll close this issue in favour of the similar issues that are already open (see #183 and #116) I'll bring your idea around a 'full screen' view back to the team so that we can think on it more!  

Cheers :beers:
