### ISSUE TITLE
after deleting a custom estimate, it's still there in any other issues

### ISSUE THREAD

**Issue by JonathanMatthey** [ZenHubIO/support#237]
![image](https://cloud.githubusercontent.com/assets/548027/7686505/2843f72c-fd64-11e4-9efe-d83acbd8e2a6.png)

clicking the delete removes it once, but come back to the issue or any other issue and it's still there

- [ ] delete custom estimate for whole team / company globally

as requested by @adamck

**Comment by azenMatt** [comment]
Hi @JonathanMatthey 

To confirm, we have two different ways to remove estimates, 

The first, 'clear estimate' will just remove that value from being assigned to the current estimate 

![image](https://cloud.githubusercontent.com/assets/7584089/7731684/e61fffa2-fed6-11e4-8973-cb77b8f960da.png)

The second, the delete icon, will remove that estimate from being an option elsewhere in the same repo. 

![image](https://cloud.githubusercontent.com/assets/7584089/7731643/97e0987e-fed6-11e4-8481-d01332d21198.png)


Just so I understand the issue here, is the problem that the delete icon is not removing the estimate from the list of possible estimates? or that it is not removing it from issues that have already been assign that value?

**Comment by JonathanMatthey** [comment]
hi,

this gif should explain what's going on.

![](https://s3.amazonaws.com/f.cl.ly/items/3u462d1L0i3n1z2T0K3y/Screen%20Recording%202015-05-20%20at%2001.01%20PM.gif)

this is not CLEAR ESTIMATE, but clicking the Trash Icon.

what I'm trying to do is REMOVE 1e37 from the list of presets that show up.  I delete it, go to another issue, it's still there. no matter how many times i try deleting the preset, it won't delete itself.

does that make sense ?

**Comment by azenMatt** [comment]
Haha - ok I see what has happened here. If you put in a massive value, it switches it to scientific notation - which the delete functionality isn't working for. 

If you try this with a value like '20' you will be able to delete it without a problem. 

We will get a fix in which 1) allows you to delete these values 2) puts a limit on how big of a value you can enter. 

Thanks for spotting this edge case - an estimate of 1e+37 is a big piece of work!  :smile:
