### ISSUE TITLE
Track blocked & blocking

### ISSUE THREAD

**Issue by phemmer** [ZenHubIO/support#241]
It would be useful to relate blocking issues. For example, if a comment on an issue/PR contains `blocks #123`, `blocking #123`, etc, add something in the sidebar of both the issue making the comment, and the issue being commented on (# 123) showing the blocked/blocking relation between the two. (also scan for `blocked by #456`).
When the blocking issue is closed, the sidebar should indicate that the block is cleared, by removing from the sidebar, greying out, etc.

Could also have direct entry into the sidebar instead of (or in addition to) comment scanning.

Might also be useful to handle `closes #789` (PRs), `dup #789`, `closed by #789`, etc, and even plain references (everything that contains an issue number but no identifiable reason) in the sidebar.

This would greatly help issues with a long history, and prevent having to scan through them trying to find the state.

**Comment by aupright** [comment]
Hey @phemmer, thanks for the suggestion!

We've been thinking around this problem ourselves over the past few weeks—I think we all agree that this would be a welcome addition to the product. I'll bring your suggestions here back to the rest of the team so that we can iterate on them a bit further and see where they fit in our roadmap. 

I can see that your suggestion has already received a few votes from the rest of the community, so I'll move it to the discussion column for some more feedback!

**Comment by smiller171** [comment]
should also have insight into things like `fixes #123`

**Comment by nickbuddendotcom** [comment]
+1

**Comment by kendramoroz** [comment]
👋  Doing some clean up of our community Board and wanted to share that adding Issue Dependencies in ZenHub has been live for quite a few months now! For those interested here in checking it out if you haven't yet discovered it, you can learn more here: https://www.zenhub.com/guides/issue-dependencies
