### ISSUE TITLE
Improve handling of Milestone renames

### ISSUE THREAD

**Issue by jirihelmich** [ZenHubIO/support#244]
When I rename a milestone, the plugin gets completely confused. It shows 2 entries in the board milestone list, one with the previous name, one with the new one. If I click the old one, it goes to the new one, if I click the new one, it goes to the new one as well.

Some issues are moreover lost, because they are still linked with the old one in ZenHub, but if I want to display it, ZenHub shows me the new one.

**Comment by jossmac** [comment]
We're having the same issue here, see screenshot:
![image](https://cloud.githubusercontent.com/assets/2730833/7806719/a7ef57a0-03c7-11e5-80fd-cd513d708973.png)

**Comment by JedWatson** [comment]
+1, we just experienced this and it's really bad, feels like you've lost your data & makes it hard to trust the board is showing you everything it should be.

**Comment by BorisBozic** [comment]
+1

**Comment by brianfleming** [comment]
I experienced this same thing, see #239 and it was some number of hours (at least 4) when it cleared itself up and the duplicate milestone was gone and the issues were in the correct milestone list.

**Comment by jirihelmich** [comment]
Yes, it cleared itself during the night. However, if we have a meeting and rename a milestone, we cannot wait 4 hours to be able to continue using the tool.

**Comment by brianfleming** [comment]
agreed @jirihelmich , the lag was disconcerting. just wanted to add more information to the issue for zenhub and anyone who comes across the same problem, not excuse it.

**Comment by aupright** [comment]
Thanks @jirihelmich for issuing this up, and thanks everyone for the comments here. 

We're currently looking into this error ourselves and are working on a solution. Given the amount of feedback in such a short time period, this one is definitely a high priority for us. I'll keep everyone here updated as we get closer to releasing a fix!

**Comment by jirihelmich** [comment]
Thank you!

**Comment by wmbutler** [comment]
The same thing happened to me, but all I did was change the due date on the milestone.

**Comment by JedWatson** [comment]
Thanks @aupright, much appreciated!

**Comment by charlsyd** [comment]
Hi guys - just wanted to report that we're having this issue too. Very frustrating, but glad to hear it's being worked on. 

( You should put out some warning or email regarding this issue. :+1: )

Cheers

**Comment by tUrG0n** [comment]
Yes, same issue here :/
ETA on a fix?

**Comment by aupright** [comment]
Hi everyone, thanks for all of your patience here!

We're just finishing up a final code review and are hoping to go live with a fix sometime in the coming week. As soon as we release the update, I'll post another message here to let everyone know. 

Thanks again for all of your support :smile:

**Comment by azenMatt** [comment]
Hi all, 

Thank you for your patience with us getting this one fixed, we pushed out a preliminary fix for this last night based on a new polling system and it is working well :+1: 

**What does this fix do?** 

This fix is going to help keep the board consistent against some of the edge cases that we had been seeing on milestone updates - and allow an manual refresh to resolve any other issues. 

**What won't this fix?** 

Right now, this milestone renames will still take some time to filter though (but the old milestone name can still be used to get an accurate picture of the board - rather than seeing duplicates as above) 

The reason for this is that GitHub does not treat milestone renames as an 'update' when we send them an API call to ask for any updates to the issue list. 

So to get the latest milestone name, either 1) the board cache needs to expire or 2) an issue needs to be added to a milestone (which will cause the user to see two milestones in the dropdown) - followed by a manual refresh. 

**What are we going to do next?** 

We understand that this is not a completed solution and will be continuing to work on a full fix that handles milestone renames as seamlessly as we do an issue re-name. However we wanted to get the above change live as soon as possible so that you could at least 1) trust that you are seeing all the issues 2) be able to fix any duplication via a manual refresh. 

I'l keep this issue open to update in the future once we have a full fix here. But to set expectations, due to the frequency of milestone renames and the above work-around, we see this as a medium term priority and do have some more urgent changes we want to push live first! Please let me know if you disagree and if this issue is still causing a big problem in your use of ZenHub.

**Comment by rashagen** [comment]
@azenMatt for our team this issue has been a real pain and would like to ask you to reconsider the down-prioritisation or suggest a way of manually removing the duplicate

**Comment by azenMatt** [comment]
understood and agreed @rashagen 

Does 

>to get the latest milestone name, either 1) the board cache needs to expire or 2) an issue needs to be added to a milestone (which will cause the user to see two milestones in the dropdown) - followed by a manual refresh.

work as a manual method for you? 

In terms of the down prioritization of this, since writing that in June, it has been working its way to the top of the backlog so we should get some movement here soon

**Comment by rashagen** [comment]
@azenMatt great news that it's bubbling back up the backlog list ;)

Is there a way of manually forcing the board cache to expire? That would be helpful.

**Comment by azenMatt** [comment]
> Is there a way of manually forcing the board cache to expire? That would be helpful.

Not right now, so we are reliant on: 

> an issue needs to be added to a milestone (which will cause the user to see two milestones in the dropdown) - followed by a manual refresh.

**Comment by azenMatt** [comment]
Hi Everyone, 

Good news! We have just release a new process that provides an updated milestone cache - so this problem should now be resolved for good :smile: 

If you rename / change dates on a milestone, the ZenHub board will detect this when it loads and update all the applicable data. 

What this won't do - is detect the change in real time and update the board (for example how pipeline changes work), but it does mean that a simple refresh will bring an already loaded board into sync with a milestone that has been updated in a different window / by someone else. And that on opening, a board will always be in sync. 


For those also following along with the same issue happening to labels - the fix is very similar, so we are working on that now and will have that issue fixed soon :+1:
