### ISSUE TITLE
Ability to show only PR's on board

### ISSUE THREAD

**Issue by ajwhite** [ZenHubIO/support#251]
There's currently two checkboxes

- View pull requests
- View closed issues

But it would be great if we could also toggle between open issues and really narrow down to the capability of:
- Showing PRs
- Showing open issues
- Showing closed issues

We use the Boards to also pipeline PR's through their lifecycle (acceptance testing, code review, etc). Would be beneficial

**Comment by aupright** [comment]
Hey @ajwhite thanks for the suggestion!

Most of the feedback that we've had thus far from teams has been around removing PRs from the board to help focus on issues. If this is something that would be helpful for your workflow however, there's a good chance that it would be helpful for a few more teams as well. I'll move this one to the discussion pipeline so that we can try and get more feedback and votes!

**Comment by ajwhite** [comment]
Yeah that would be rough, as we use the pipelines for tracking progress of the PR's as well (acceptance test : arrow_right: code review :arrow_right: end to end test :arrow_right: done)

**Comment by jstruzik** [comment]
I'd vote to have an option to hide/show PRs. After all, PRs are technically issues.

**Comment by ajwhite** [comment]
>removing PRs from the board to help focus on issues

I just want to reiterate the importance of PR's in the board is for our team. It would be a lot less of a "breaking change" if users could opt in to show PR's, as you have now. Perhaps instead of removing it, it could by default hide PR's, while still allowing us to opt-in.

![screen shot 2015-06-23 at 10 44 33 am](https://cloud.githubusercontent.com/assets/656630/8308813/f9068824-1994-11e5-8323-b489f5ed5803.png)

**Comment by ajwhite** [comment]
This has been resolved with the new toggle buttons

![Uploading Screen Shot 2015-07-29 at 1.01.46 PM.png…]()

Thanks guys, this is extremely helpful to us!

**Comment by sxgao3001** [comment]
Glad we could help!
