### ISSUE TITLE
Closed milestone is listed in Milestone filter

### ISSUE THREAD

**Issue by jirihelmich** [ZenHubIO/support#253]
Is that a feature or a bug? I guess that a closed milestone should not be visible. We use milestones as weekly sprints and we will soon end up having a long list of milestones there.

**Comment by aupright** [comment]
Hi @jirihelmich, thanks for reaching out!

We keep closed milestones on the burndown chart page so that teams can refer back and use the information from previous sprints to better plan upcoming releases. Going forward, I can see how the milestone filter might start to get a bit busy if you are following a weekly sprint cycle.

I'll loop back with the rest of the team here so that we can discuss this in more detail and put together a game plan going forward. Thanks again for the feedback!

**Comment by jirihelmich** [comment]
2 days later - it disappeared. I'm happy, but from what you described, that's a bug? :-)
