### ISSUE TITLE
One issue does not show up on board

### ISSUE THREAD

**Issue by torkiljohnsen** [ZenHubIO/support#260]
I have double and triple checked that the issue has the correct milestone, but it does not appear in the board overview. The issue is closed and has no estimate.

I reopened the issue, switched minestone a couple of times, then closed the issue again, and now it appears on the board again.

Kind of annoying, especially this when the boss steps into the office and wonders what you've been up to, and the board shows too little in the "closed" lane :)

**Comment by azenMatt** [comment]
Hi @torkiljohnsen - This is likely due to the number of closed issues that we show on the board - in order to keep performance high, we only fetch the last 50 closed issues from a repo. So if you filter down into a milestone - you will often not see any closed issues. 

We experimented with ways to update this - but as most GitHub projects have lots of closed issues, the API calls required were too expensive against performance, so we settled on what we thought was a sensible limit.

If this issue was with a recently closed issue, please let me know and I can re-open and further investigate!
