### ISSUE TITLE
Disable issue popup. Revert to new tab

### ISSUE THREAD

**Issue by MrHubble** [ZenHubIO/support#266]
Is there anyway to revert to having issues appear in a new tab rather than a modal/popup?

**Comment by azenMatt** [comment]
Hi @MrHubble - if you would like to open the issue in a new tab, rather than left click the issue, you can either cmd/ctrl + click or middle button mouse click. 

This should give you the option of either in-board view or new tab view depending on what the next action you wish to take it. 

#262 details a known issue with the middle button on windows 8.1 - if you are using this, you can expect a fix out in the next couple of days. I will update #262 once live! 

Thanks for your feedback!
