### ISSUE TITLE
Allow file uploads to use GitHub Large File Support

### ISSUE THREAD

**Issue by IDisposable** [ZenHubIO/support#273]
I need to be sure that my entire project's assets are linked to the GitHub account so we can easily transfer the final work-product to other companies when a private project is completed.

With the upcoming GHLFS, would love the file uploader of ZenHub to use that as the storage method for the files instead of a S3 bucket we cannot control/audit/transfer.

**Comment by aupright** [comment]
Thanks for the suggestion here @IDisposable - it looks like your comment has already received a few more +1's from others in the community as well. In terms of file storage, we're only using our own s3 bucket for file types that GitHub's native file uploader doesn't currently support. For all image files, we still rely on GitHub's file uploader and storage methods. 

Although there are a few other high priority items on our near-term product roadmap, I'll keep this issue open so that we can continue collecting feedback from the rest of the community. Thanks again for the suggestion and taking some time to reach out!

**Comment by azenMatt** [comment]
We are keeping an eye on the developments with the GH LFS - and will make sure we incorporate this into ZenHub file uploads in a way that makes sense!
