### ISSUE TITLE
Remove weekends from burndown chart

### ISSUE THREAD

**Issue by lexsf** [ZenHubIO/support#276]
Love the burndown charts, but we don't count weekends in our burndown and the current chart does.

Would love flexible days to count towards the burndown.

**Comment by Groostav** [comment]
Make toggle-able please!

Lots of my team work remotely on weekends, some iterations have actually had the majority of their work done on the weekends (god I feel bad saying that).

Weekends on burndown still add plenty of value for us!

**Comment by azenMatt** [comment]
@lexsf @Groostav - thanks for the feedback from different view points here. 

If we implement changes here - we will make sure that it is based on a toggle so that work that does occur at the weekend is captured.  

Moving into the discussion pipeline to get input from the community as to if the ability to toggle between displaying weekends or not will be useful - please +1! :smile:

**Comment by arkarkark** [comment]
or perhaps just make the target line flat during the weekend days?

**Comment by aminer-looker** [comment]
+1

**Comment by jbsulli** [comment]
I would definitely like to have it flat for weekends. So you could still make progress on weekends if you wanted to catch up. Hiding weekend days wouldn't show what happened.

**Comment by nunoh** [comment]
We use Zenhub for both managing and planning our iterations. Since we only count weekdays and do two-week iterations, needless to say how quite of a bummer this is. Well, for us, it basically means, that the estimated line is always wrong! This is a much missed feature in our team. Simply the feature we miss the more in Zenhub compared to other platforms.

**Comment by azenMatt** [comment]
Weekends are now shown on the burndown chart! 

![image](https://cloud.githubusercontent.com/assets/7584089/15000584/adc357ee-1145-11e6-8655-b4d54ce020c1.png)

Enjoy the extra time off 😀 

Live in v2.16.40

**Comment by nunoh** [comment]
Wow, that was quick! Thanks so much. Already using it! 😃

**Comment by Uduse** [comment]
My company works six days a week. Is there a way to show a graph like that?

**Comment by valadas** [comment]
Development is not my full time job, so I develop a lot more on weekends ;) A setting for working days would be nice.

**Comment by SlightlyCyborg** [comment]
Ok. So this may have fixed the burndown chart for the guy above, but it messed it up for the three of us at the bottom who do work on weekends.

**Comment by dmrkv** [comment]
Sorry, how to turn on showing the weekends?
Because right now it shows just straight line, non-flat at weekends, weekends are like regular working days.
