### ISSUE TITLE
Add 'No Pipeline' akin to 'No Milestone'

### ISSUE THREAD

**Issue by Groostav** [ZenHubIO/support#277]
We've always run a physical board very similar to the board you guys have. One annoying difference is that for us the board only represents things that are currently slated for this sprint. We've got 5 (fairly typical) columns, starting at `Pending` and moving next to `In-Dev` and eventually into `accepted`.

The problem I want addressed is that by default all new issues are given the default pipeline, which is `Pending`. This is annoying since despite our regular backlog grooming we still have around hundreds of issues that are not going to be checked out. This floods the `pending` pipeline with information that's useless to the current sprint.

if I could make a story out of this:

> as an unsophisticated git-issues user (eg BA, or [our CEO](http://www.sfu.ca/mechatronics/people/faculty/gary_wang.html)) , I would like to be able to see a high level overview of the current development sprint --without having to apply features like milestone-filters and tag-filters-- so that I'm better able to gague developer progress.

You're filters make it fairly easy to address this, but its not ideal. 

The default behavior of github for milestones is to create a pseudo-milestone called `No Milestone` and simply append everything to that. I would really appreciate a similar behavior for pipelines.

Similarly, you could give me the ability to do it myself: If I can rename the default `backlog` (in our case `pending`) pipeline to `No PIpeline`, and then deselect some kind of option to say `show by default`, such that the first time a user views our boards they wouldn't see that pipeline, that would be a perfectly acceptable alternative.

Thanks for the great product!

-Geoff

**Comment by aupright** [comment]
Hey Geoff, thanks for the detailed write up here!

We're planning on introducing a 'collapsing and expanding' pipeline feature soon that will give you the ability to manually do this yourself. As you suggested above, you can  rename the first pipeline of your workflow `no pipeline` (or something similar) and then collapse the pipeline so that you will only see the different pipelines associated with your sprints. When planning your next sprint, you can then expand the first pipeline within your workflow and pull new issues from that pipeline into the sprint.

Keep an eye on #122 and #163 for updates here!
