### ISSUE TITLE
Board does NOT update label colour/name changes

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#279]
When I update label name or color, it is not reflected on the board, but it is reflected in the ticket itself. I have to remove the label and then add it again for the board to reflect the new label name or color.

**Comment by aupright** [comment]
Hey @jefforshalick I just touched base with the rest of the team on this one, and it looks like the issue here is that we don't currently fire an 'issue update' event to GitHub when the colour or name of a label is updated. As we take a closer look into this one internally, a quick fix here would be to remove and add the label as you had above, or add and remove a comment in the issue to refresh the issue cache. 

I'll move this one to our Known Issues pipeline so that we can update on it going forward!

**Comment by azenMatt** [comment]
Hi @jefforshalick 

If you can update to version 2.15.93, we now have an updated check that will keep all your labels in sync :grinning: 

This means all labels will be correct when a board is first loaded, and if a change happens to a label elsewhere, it will be updated on the board within ~10 seconds.

Please try it out and let me know if you have any problems!

**Comment by jefforshalick** [comment]
Thanks @azenMatt !
