### ISSUE TITLE
Add Blocked / Ready icons on Pipeline dashboard

### ISSUE THREAD

**Issue by EdgeCasey** [ZenHubIO/support#282]
Would be nice to have an indicator that allows user to easily identify if issue is blocked or ready to move to next stage. See Huboard for reference

**Comment by aupright** [comment]
Thanks for another suggestion here @caseykoppes! 

I think there's a strong use case for adding this type of feature into ZenHub. Although a lot of teams are already doing this with GitHub labels, I can see how adding a more prominent indicator would ensure that nothing is missed here if an issue already has quite a few labels attached to it. I'll move this one into the discussion pipeline so that we can try and get a few more +1's from the rest of the community as well!

**Comment by clionaderoiste** [comment]
+a

**Comment by signedav** [comment]
Would be amazing.

**Comment by marioba** [comment]
Would be super great!

**Comment by azenMatt** [comment]
You can now use ZenHub dependencies to easily see in the board view which issue are blocked - and by what
