### ISSUE TITLE
Add a search filter for board view

### ISSUE THREAD

**Issue by kyspy** [ZenHubIO/support#285]
Please add the ability to filter the board by a search term or custom filter, much like waffle.io. It's hard to sort the board by search term to see if an issue already exists.

**Comment by OronNadiv** [comment]
@kyspy since ZH loads all the issues right on startup, you can use your browser's native search (command-F in chrome) to search for a specific issue.

**Comment by kyspy** [comment]
@OronNadiv Agreed as an acceptable workaround, however, this is not as simple/ easy/ convenient as the search that would filter out the cards that are not included in your search. I'm finding that I really miss that functionality.

**Comment by aupright** [comment]
Thanks for the suggestion @kyspy (and thanks for jumping in here @OronNadiv)!

You'll both be happy to know that we're currently working on a search feature to help filter issues on the board. Although the native 'command-f' function provides a temporary work-around, we're hoping to create a much better user experience here in terms of filtering out non-relavent information. I'll keep this issue open as a place to centralize the discussion on our search feature, and provide new updates as we get closer to launching. 

Thanks again for the feedback :beers:

**Comment by kyspy** [comment]
@aupright Great to hear! Thanks and I look forward to more updates.

**Comment by jckime** [comment]
@aupright @azenMatt Any requests/thoughts on when I perform the search it just opens up a new "temporary pipeline" with all those issues in it.  So don't filter the board, but show all the results in a pipeline that I could then move to a some place on the board and then the board would reflect my desire.  I feel like PivotalTracker was really good at this and would love that functionality.

**Comment by azenMatt** [comment]
Hi @jckime - that is an interesting idea. Our rational for having them appear in pipeline was so that you can also get the 'status' information that the pipeline gives you. From this filtered view you can also still move the issue around to a different pipeline if the status has changed. 

Happy to be persuaded that a separate pipeline would be better though! What sort of use case do you see this as being more useful during? 

(I will close this issue as the original feature has been delivered, but lets keep discussing and we can open a new issue after)

-------

@kyspy - I should have updated this issue a while back as we have had this search functionality for a while! This searches against - Issue title, Issue number, Labels, Milestones and assignees

![image](https://cloud.githubusercontent.com/assets/7584089/9950028/9a2819ca-5d6a-11e5-9cd0-90359d845c8d.png)

**Comment by jckime** [comment]
@azenMatt The main use case is that when I search for an issue that is in my backlog and it filters down all the boards, that doesn't give me context for where that thing sits in priority in that pipeline.  So to me, the search as it is currently implemented doesn't help me anymore than a ctrl+f does.  In fact, I probably use the ctrl+f more often since it still gives me the ability to see the context of where the issue sits in the pipeline.  When I have a backlog that is 80 issues deep, that is important to me to know where it sits in priority.  

What I proposed would also help with seeing all the issues labeled with a certain feature name in one temporary pipeline so I can more easily see all the those things and then place them next to each other in priority in the backlog pipeline.  By filtering it down, they are already next to each other and thus it isn't really effective moving them.

**Comment by azenMatt** [comment]
Understood - thanks for the explanation. 

I have opened a new issue here - #380 - to keep track of this

As a brief aside, I completely agree that we need to be able to better communicate this information (priority) in several places. At the moment, it is only really clear in the unfiltered board view. It is an area we are actively looking to improve.
