### ISSUE TITLE
Multi select and issue highlight in board view

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#287]
It would be very helpful to have the ability to multi select. This could be used to mass move, mass assign, and mass label.

And issue highlight would just show a highlight of some kind around an issue after viewing the issue or moving it because I sometimes lose issues on the board.

**Comment by aupright** [comment]
Hey @jefforshalick,

We've actually had a few other users reach out with a similar suggestion around being able to bulk manage and move issues from the board. In order to keep things centralized (and focused), I'm going to move this discussion over to https://github.com/ZenHubIO/support/issues/118. Please show your support and add a +1 there!
