### ISSUE TITLE
Show Ticket References/Linkages on board

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#294]
When organizing issues or working on a group of them, it would be nice to be able to easily see where issues are that I referenced in the one selected. It could show other tickets with lines (like a spider web with the selected issue as the central node) or jsut highlight them in some way. So, there would have to be a selection state on issues and it would then take a double click to open the issue modal over the board.

A way to avoid having to have the selection state would be to just list the referenced issue numbers in the issue container itself. Maybe it could be after the name in blue text or something so that when you click on the referenced issue in the parent issue, it opens the ticket number that you clicked on.

This could also go cross-repo since you now offer the ability to show multiple repos on one board.

This feature could also go further and have an option in the menu on an issue to select all referenced tickets that appear on the board. This would make it easy to multi select specific issues and bring them together in a new pipeline.

**Comment by aupright** [comment]
Hey @jefforshalick, interesting suggestion here!

Depending on how this feature is set up, I could also see it being a really intuitive way to show the hierarchy between issues (ex. epics, stories, tasks)—a broader feature that quite a few teams have asked for. I'll move the conversation here into our discussion pipeline so that we can try and get some more votes on this one a feedback on how this could be best implemented!

**Comment by kendramoroz** [comment]
👋  @jefforshalick closing this to track in https://github.com/ZenHubIO/support/issues/1184 which will take the current Dependency feature in ZenHub and add the blocking/blocked by relationships to the Board view. Let us know if you have any questions in the mean time!

**Comment by jefforshalick** [comment]
Thanks @kendramoroz !
