### ISSUE TITLE
Sort Issues by +1s

### ISSUE THREAD

**Issue by englercj** [ZenHubIO/support#303]
After #302 is implemented, the next logical step is then be able to sort issues by the importance the community has placed on that issue. In that way I can prioritize my backlog based on community feedback, without them having to know about or install ZenHub.

**Comment by aupright** [comment]
Thanks for issuing this one up too @englercj! I'm going to move this one into the community icebox as something to look at after we get some more feedback on #302. If we decide to move forward with your initial suggestion, I'll make sure that we include this issue here in the discussion of requirements :beers:

**Comment by azenMatt** [comment]
We depreciated the +1 functionality in favour of GitHub reactions today, so i am going to be closing the +1 related issues. 

It seems like GitHub have a few tricks up their sleeves for reactions so hopefully we will see this from them soon! Once the API for reactions is live, we can look to implement reaction based functionality on the board.
