### ISSUE TITLE
Toggle show all

### ISSUE THREAD

**Issue by slajax** [ZenHubIO/support#305]
Once I toggle my 25 repos on using the "show all" button, I generally have to click at least 25 times in order to hide them all again.

I would suggest enabling a listener that will change said button to "hide all" once there is more then one repo is selected.

The outcome is that the user should be able to easily toggle between global view and a clean palette that can be leveraged for faceted search.

**Comment by aupright** [comment]
Completely agree with this one @slajax - although I must admit that 25 repos is a bit of an edge case when it comes to multi-repo boards :wink: . Regardless, I can see where this would have a strong use case even for disconnecting a smaller number of repos. 

I'll bring this one up internally so that we can see where it fits in our roadmap, and move this issue to the community backlog to keep you updated!

**Comment by slajax** [comment]
Yes, our SOA means we're definitely shipping a lot of repos, but thats why ZH makes so much sense for us. Checkout #311 for another edge case that I'd be happy to test a solution for! I appreciate the update @aupright.

**Comment by mattyjones** [comment]
@slajax  I am contemplating boards with 50+ repos so you are certainly not alone in the usefulness of this feature

**Comment by slajax** [comment]
@mattyjones :+1: - feel free to ping me if there are other large repo challenges you are facing. You are the only other person I know of using at this scale.

**Comment by azenMatt** [comment]
Hi @mattyjones @slajax - this one is live just in time for the weekend! 

Version 2.5.9 now lets you 'show one' if you have all your repos selected

**Comment by mattyjones** [comment]
@azenMatt  Massive +1
