### ISSUE TITLE
Closed milestones remain in milestone filter

### ISSUE THREAD

**Issue by roberthoner** [ZenHubIO/support#343]
We use milestones to track our versions/releases, so each cycle has a new milestone. Once we're done with a release we close the milestone associated with it. However, these milestones still show up in the ZenHub filter dropdown.

Preferably only the open milestones would show up here.

**Comment by aupright** [comment]
Hi @roberthoner thanks for the message - would you be able to clarify whether you are referring the the dropdown filter in the boards tab, or the dropdown filter in the burndown charts tab? 

The expected behaviour is that only `open` milestones are visible from the boards view, but that both `open` and `closed` milestones are visible for the burndown charts. The intention here is to allow team to reference past sprints for the purpose of improving planning and resource allocation going forward :smiley:

**Comment by roberthoner** [comment]
Hey @aupright, just seeing your reply. I'm referring to on the boards tab.

Looking at it today, it seems our milestone filter list has been update. It includes much fewer closed milestones but a couple still remain.

**Comment by alexmattos** [comment]
We still have this and have had for a few weeks - any ideas. It only appears to be to related to one of our repos.

**Comment by azenMatt** [comment]
It seems will still have some issues with milestone updates not making it through to the issue cache. 

We have some refactoring lined up for how this works - so expect this to become much more robust during Q1!

**Comment by azenMatt** [comment]
We have made several updates now to our milestone cache - so these issues should all now be resolved. Please let me know if you are still having issues!
