### ISSUE TITLE
Cannot scroll down to last item in milestone filter

### ISSUE THREAD

**Issue by CarlMalartre** [ZenHubIO/support#353]
On my Win10 Dell notebook with a resolution of 1920x1080 and with Google Chrome, the milestone filter is clipped and I cannot scroll down to the last milestone. Screenshot

https://screenshots.scolab.com/Public/Jing/CM/2015-08-19_1053zenhub.png

Screen size is 150%:
https://screenshots.scolab.com/Public/Jing/CM/2015-08-19_1054zenhub.png

**Comment by aupright** [comment]
Hey @CarlMalartre thank for issuing this one up!

I'll ping the rest of the team internally so that we can look at adjusting scrolling on the filters for larger screen resolutions. While I know that this isn't a permanent solution, does zooming out on your browser (to something less than 100%) allow you to scroll to the bottom?

**Comment by CarlMalartre** [comment]
It seems to work now.

Screenshot, same screen, newer Google Chrome:
https://screenshots.scolab.com/Public/Jing/CM/2015-09-22_1128.png

**Comment by aupright** [comment]
Thanks for the follow up @CarlMalartre - great to hear this is now working! I'm going to close this one out for now, if there's anything else that I can help with, please let me know :beers:
