### ISSUE TITLE
zenhub sidebar features missing if PR opened directly in files changed mode

### ISSUE THREAD

**Issue by phemmer** [ZenHubIO/support#376]
Say you get a notification of a comment on a line of code in a PR. If you visit the link, it takes you to the PR directly into the "Files Changed" tab. If you then switch to the "Conversation" tab, the zenhub sidebar features (pipeline & estimate) are missing.

You can also duplicate this by refreshing the browser while on the "files changed" tab.

&nbsp;

I think this might be new behavior. This has been driving me absolutely crazy for the last week or so, and I don't recall seeing the issue prior to that.

**Comment by aupright** [comment]
Hey @phemmer I apologize for the late reply here—this was a known issue at the time that you posted and has since been fixed in a recent updated. Can you confirm that you're no longer seeing this error in the "files changed" tab?

**Comment by phemmer** [comment]
No, I can't confirm, sorry. This issue is still present.

**Comment by aupright** [comment]
Thanks for the follow up @phemmer, I brought this back to the team so that we could put a quick fix in place here to address this. On my end, both the pipeline selector and estimate selector are now visible when switching from the "file changes" to "conversation" tabs in a pull request! 

Would you be able to confirm this on your side?

**Comment by phemmer** [comment]
Yes, this does appear to be working now. Thanks

**Comment by aupright** [comment]
Great to hear @phemmer!

Closing this one out :smiley:
