### ISSUE TITLE
Option to add label when moved around board

### ISSUE THREAD

**Issue by dustinblackman** [ZenHubIO/support#384]
For those who don't use Zenhub, it would be nice if we could enable an option that will add labels to issue as they're moved around the board so facing public can see.

**Comment by aupright** [comment]
Hey @dustinblackman thanks for the suggestion!

We've had a few other users reach out about this one as well, and are currently prioritizing this feature to tackle in our roadmap going forward! I'm going to close this one out so that we can keep the discussion centralized in #46. It would be great if you could add your comments and +1 there :smiley:
