### ISSUE TITLE
show full title and all labels in expanded pipeline columns

### ISSUE THREAD

**Issue by haoliu119** [ZenHubIO/support#408]
I notice that once I expand a pipeline width to show more than one column of issues, long issue titles get truncated and not all labels are visible on the issue. It would be nice if the waterfall/Instagram layout can be applied to the multi-column pipeline so each issue can still show all the info.

**Comment by azenMatt** [comment]
Hi @haoliu119 

When we were creating this functionality we orginally wanted to show all the information - but it causes a UX nightmare! If the cards are not the same hight - the interface is almost impossible to use as you lose all sense of priority. If you force cards to be the same height as the largest card - you can end up seeing less cards than in a non expanded pipeline! 

lets open this one up to community +1's - to see if we want to revisit the design of these. 

I will add, that for the purpose of searching the board, all labels and title content is used, even if they are not shown.

**Comment by haoliu119** [comment]
thanks @azenMatt , we'll let the community decide

**Comment by smiller171** [comment]
yeah, I would certainly want this. One thing you could do is crid it in rows, so that whatever two cards are side-by-side inherit the size of the larger of the two cards, without making all cards in the pipe take that larger size.

**Comment by azenMatt** [comment]
> One thing you could do is crid it in rows, so that whatever two cards are side-by-side inherit the size of the larger of the two cards, without making all cards in the pipe take that larger size.

We did try this, but we had problems with the rendering of cards when a pipeline had a large number of issues in it - and when re-ordering a card, every one of them had to be updated. 

But please keep +1ing and we can take another swing at it!

**Comment by ilyapalkin** [comment]
+1

How to vote for this issue?

**Comment by smiller171** [comment]
@ilyapalkin Use the new built in reactions. The little smiley in the top right of any comment. It will show up like the thumbs up I just put on your comment.

**Comment by cbeams** [comment]
At this point, I think I'd prefer to deal with varying card heights in expanded columns in order to see all labels, and have +1'd to reflect. Specifically, @smiller171's suggestion makes sense to me:

> One thing you could do is grid it in rows, so that whatever two cards are side-by-side inherit the size of the larger of the two cards, without making all cards in the pipe take that larger size.

As a near-term solution, perhaps you could simply show all labels in a "hover" when mousing over the ellipsis.

Another thing that would help here is if ZenHub's search box included labels in its results. I've just added a dedicated issue (#695) about this.

**Comment by azenMatt** [comment]
This is being taken care of as part of the current board refactor. 

Due to the increases in performance we can deal with multiple card heights 🎆 

This means cards will adapt to the largest care in their row, like: 

![image](https://cloud.githubusercontent.com/assets/7584089/16818625/98db3f14-48fd-11e6-86d2-4b83a2162306.png)


We are in the final push for getting this live!

**Comment by azenMatt** [comment]
and released 😄 

If you can update to v2.21.1 the expanded pipelines will now grow issue cards to fit the biggest card on a given row.
