### ISSUE TITLE
Sharing of To-Do lists

### ISSUE THREAD

**Issue by jlee462** [ZenHubIO/support#409]
I love the new To-Do list feature.  If we could share those To-Do lists, then I could use them as planned/upcoming task lists for my developers.  That would make the To-Do's very powerful.

**Comment by azenMatt** [comment]
Thanks for the feedback @jlee462 

I'm glad to hear you like the To-Do lists! I can see how being able to share these would be useful. We have lots of other ideas to improve these as well - and will make sure we include sharing in these discussion, so keep the ideas coming and stay tuned for a V2 :smile:

**Comment by jlee462** [comment]
Do you guys have any kind of guesstimated  time-line or target on when you
would like to push a version  2?   I'm very excited about the todos
feature.

**Comment by azenMatt** [comment]
To be completely honest with you - it depends on the reaction of the ZenHub community, if the todos are popular we can justify doing it sooner! So tell your friends and hopefully it will be very soon! :grinning: 

Right now, we are working on some performance improvements across the whole of ZenHub while the feature settles in. I should have a better idea in the next couple of weeks once more feedback has come in on timelines and changes for V2!

**Comment by Mottie** [comment]
Is there a way to turn off the pulsing dot?

**Comment by cristinasantamarina** [comment]
@Mottie just click on it and then on the Got It! button

**Comment by Mottie** [comment]
Derp! LOL thanks!

**Comment by n8harmon** [comment]
Our organization is new to Zenhub.  I have begun using the To-Do list feature, and would love to see this enhancement available to use, so that we could share To-Do's across our organization.  It would also be nice if any issues or PR review assignments also showed up in the ToDo inbox.  It looks like this request is a couple years old now, do you know if it will be moving up in priority anytime in the near future?

**Comment by kendramoroz** [comment]
Hey all - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
