### ISSUE TITLE
Sorting by date for items in the board

### ISSUE THREAD

**Issue by dok** [ZenHubIO/support#410]
I would love to sort items by date. Often times, I would be unable to find issues I have created because of the sheer number of issues in a pipeline. Sorting by date would greatly improve my workflow.

Thanks!

**Comment by aupright** [comment]
Hey @dok thanks for the suggestion!

We've definitely been thinking about this type of "sort by" functionality as part of a v2 iteration for our boards. I'm going to close this issue here, but will make sure that this gets documented internally so that we can involve it in our discussions going forward. Thanks again!
