### ISSUE TITLE
Sorting: I want to be able to sort the pipelines in my boards by date, label, etc. 

### ISSUE THREAD

**Issue by ErinConnery** [ZenHubIO/support#417]
I see no way to do this currently. This would help me organize as I scan our pipelines for certain tickets or groups of tickets. 

<img width="1072" alt="screen shot 2015-10-21 at 1 39 03 pm" src="https://cloud.githubusercontent.com/assets/7231454/10649462/2ab0748a-77f9-11e5-98fc-f5883e632253.png">

**Comment by justinbeal** [comment]
This sounds close to https://github.com/ZenHubIO/support/issues/400 . We use labels a lot and spend a decent amount of time manually sorting to group issues.

**Comment by aupright** [comment]
Hey @ErinConnery thanks for the suggestion—there's quite a bit of similarity here to #410 as well! 

As I mentioned in that thread, this is definitely something that we're interested in exploring going forward in a v2 of our boards. I'm going to close this one out, but will make sure that this is documented internally so that we can revisit your feedback when we begin building out the requirements for this functionality! 

Thanks again for the suggestion :beers:
