### ISSUE TITLE
Adding Non-Issue Tasks to To-Do Lists

### ISSUE THREAD

**Issue by tim-cyte** [ZenHubIO/support#421]
I think the To Do lists are a great addition and will definitely help our team's workflow.  One thing I would like to see on them is the ability to add a task that isn't a Github Issue.  If we could add items like "Call Mark regarding lunch." then I'd be able to use Zenhub as my complete daily task manager.  This may be beyond the scope of what you were envisioning the ToDo list to do...  but I think it would truly allow me to drop my external sticky notes app.

Thanks for the great software.

**Comment by azenMatt** [comment]
Thanks for the feedback @tim-cyte 

It is totally not beyond the scope - and is something that I wish I could do everyday :smile: 

Watch this space!

**Comment by kendramoroz** [comment]
Hey @tim-cyte  - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
