### ISSUE TITLE
Show +1 / Vote Counts in Board View

### ISSUE THREAD

**Issue by haoliu119** [ZenHubIO/support#462]
It would be nice to see the +1 / vote icon on the items in the board view.

**Comment by aupright** [comment]
Hey @haoliu119 thanks for the feedback - keep it coming!

I'm adding the 'board' label here for us to explore this as part of a planned v2 iteration on our boards. There are a number of 'sort-by' suggestions that we've been receiving along with feedback on other fields that people would like to see aggregated on the boards (ex. issue progress). I'm going to move this one to the community backlog so that we can re-visit it when we dive deeper into this feature :smiley:

**Comment by azenMatt** [comment]
We depreciated the +1 functionality in favour of GitHub reactions today, so i am going to be closing the +1 related issues. 

It seems like GitHub have a few tricks up their sleeves for reactions so hopefully we will see this from them soon! Once the API for reactions is live, we can look to implement reaction based functionality on the board.

**Comment by sganslandt** [comment]
> It seems like GitHub have a few tricks up their sleeves for reactions so hopefully we will see this from them soon! Once the API for reactions is live, we can look to implement reaction based functionality on the board.

Sounds amazing, was just going to open an issue about just that, but if it's already in your roadmap, maybe it's not needed?
