### ISSUE TITLE
Uploaded Files in Private Repositories can be Accessed by Anyone

### ISSUE THREAD

**Issue by illfang** [ZenHubIO/support#479]
If a file is attached to an issue of a private repository, it can be accessed even by users without permission for this repository.

This is not expected and I think either access control has to be implemented or a clear warning should be visible to the user before uploading a file to public in a private repository.

**Comment by aupright** [comment]
Hey @illfang thanks for the feedback here!

We actually follow the exact same permissions structure that GitHub does with respect to the files that you and your team upload through ZenHub. Although files are accessible to users without permissions for the repository, they *have* to be provided with the direct s3 link to that file. These links are not indexed for search purposes, and are otherwise not visible unless directly shared with other members of your team.

While this is the exact same system that GitHub uses, I'll bring your feedback here to the rest of the team to see where we can make this more clear for our users. Thanks again for the feedback :smiley:
