### ISSUE TITLE
Provide ability to apply different filters per linked repository

### ISSUE THREAD

**Issue by rmacklin** [ZenHubIO/support#483]
As I mentioned in https://github.com/ZenHubIO/support/issues/139#issuecomment-158267295, linking a large shared repository and a small isolated repository does not work well because we cannot filter the repositories differently:

> But the problem is: you can't specify different filter constraints per repository. I'd need to be able to filter by just my team's issues in our big shared repository while not filtering anything out of my team's small repository. This isn't currently possible.

I realize this could complicate the UI. I think a workable solution would be to show an "Advanced..." button next to the existing filters when there are multiple repos selected. Clicking that could expand the filters to show a row of filter options for each visible repository.

Please let me know if this is something you guys can do. We're struggling to adopt ZenHub because we cannot filter issues from our big shared repository with different constraints from our smaller team-specific repository.

**Comment by aupright** [comment]
Hey @rmacklin thanks for the follow up here—appreciate you expanding on this use case!

As your feedback here looks to be quite similar to what you've posted in #139 I'm going to close this particular issue out so that we can focus our discussion in one central place. If you think this issue here is separate enough to remain open, let me know and I can move it back into our discussion column.

>Please let me know if this is something you guys can do. We're struggling to adopt ZenHub because we cannot filter issues from our big shared repository with different constraints from our smaller team-specific repository.

While we are looking into the different ways that we might be able to support a multi-board structure for a particular repo, we want to provide the best user experience possible here and ensure that the interface doesn't become overly complicated. Having said that, we don't want to over-commit on this functionality until we have a workable solution that meets everyone's needs :smiley:

**Comment by rmacklin** [comment]
Hi @aupright, thanks for getting back to me.

> If you think this issue here is separate enough to remain open, let me know and I can move it back into our discussion column

I do think this is a separate issue from #139. The functionality requested here does not require multiple boards. It would still just be one board for a group of linked repos, but each repo would be individually filterable. In #139 the request is for multiple boards per repo or per group of repos. (That request would also benefit from the repos being individually filterable, but I view that request as more about adding the additional "team" layer in between repos and boards, which enables having multiple boards per repo/group of repos.)

Did I make it any clearer? Do you see what I'm saying about how these _are_ separate (and how this request doesn't require multiple boards)?

**Comment by aupright** [comment]
Thanks for the clarification here @rmacklin!

While we do support the ability to select and apply a filter a subset of the repos that you have attached to a multi-repo board, the functionality you're requesting here would involve allowing users to apply different filters on a individual/per repo basis. 

Let's move this one to the discussion column to see if we can get some more feedback on whether others in the community would find this helpful as well! :beers:

**Comment by kendramoroz** [comment]
Will be connected to #139 🎉 closing in favor of tracking progress towards launch in the main issue.
