### ISSUE TITLE
Add todo by mistake

### ISSUE THREAD

**Issue by Jeffiy** [ZenHubIO/support#484]
I add a todo by mistake, and I want to delete it, how can I do this?

**Comment by azenMatt** [comment]
Hi @Jeffiy - the best way to remove a todo is to mark it as complete - either by hitting the todo button in the issue, or via the check box on the todo page.

In order to keep the todo system simple and light weight, we decided to only have one action at each point. By hitting complete, it will not show up as a todo, and you can re-add it at any time
