### ISSUE TITLE
Collapse GitHub headers

### ISSUE THREAD

**Issue by jublo** [ZenHubIO/support#487]
The headers take up much space. I should be able to collapse them. See here:

![image](https://cloud.githubusercontent.com/assets/6348321/11453477/112c5822-960c-11e5-8135-08e2af335c11.png)

**Comment by aupright** [comment]
Thanks for the suggestion @jublo - definitely see how having a 'full screen' view could be beneficial for those team planning meetings, or even when working individually! 

We actually have another issue open here in our support repo for this feature (see https://github.com/ZenHubIO/support/issues/98) so I'm going to close this one out in order to centralize the discussion there. Thanks again :beers:
