### ISSUE TITLE
Request for To Do list free text field

### ISSUE THREAD

**Issue by chrissimpkins** [ZenHubIO/support#488]
First, thanks for this fantastic tool! The ability to work within the Github API/workflow/site works very well.  We recently began using this across our organization projects and all involved have really enjoyed it.

I love the To Do list concept and simple approach to attach an IR/PR thread to the list.  My request is for the ability to annotate these to do items with additional text for my own future reference as the IR/PR title does not necessarily convey the "to do" action item that prompted the addition to the list.  This could be as simple as a free text field associated with the to do list item where I could link a specific thread message URL or jot a short note to myself.  I would favor this approach to cluttering threads with checklists that are intended for my own work.

CC: @tim-cyte ~ extension to the request in #421

**Comment by jublo** [comment]
+1

**Comment by azenMatt** [comment]
love the train of thought @chrissimpkins - sounds very useful! 

we will look into this for further iterations of the todos

**Comment by chrissimpkins** [comment]
thanks @azenMatt!

**Comment by FezVrasta** [comment]
+1

**Comment by kendramoroz** [comment]
Hey all - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
