### ISSUE TITLE
File browser / file deletion in ZenHub Dashboard

### ISSUE THREAD

**Issue by aaronwest** [ZenHubIO/support#490]
I think it'd be useful if ZenHub created a simple file browser in the ZenHub Dashboard. Currently, there's no way to manage, look up, or delete files uploaded through the ZenHub file uploader. It'd be great if the ZH Dashboard could list all the files uploaded to the various repos and give the option to delete files.

It's possible for users to upload sensitive files on accident. I know the files are using the same GitHub security policies, that files have a hashed URL, that they aren't indexed by search engines, that password-protected files are supported, etc. but the files can still be browsed/downloaded with zero security if the link is known or given out. Plus, in the event someone uploads a file by accident, there's no recourse other than engaging ZenHub support directly.

I don't think anything super fancy would be needed here either. Something simple which iterates all the repos where:
1. a ZenHub board exists for the organization
2. a file was uploaded using the ZenHub uploader
3. show the link to the file and have it be clickable so it can be previewed
4. include a delete option

**Comment by aupright** [comment]
Thanks for the feedback here @aaronwest - we've definitely thought of better file management as a necessary addition to ZenHub going forward (especially for deleting or removing files).

For transparency, one of the things that we're being mindful of here is to try and avoid overlap with GitHub's feature set around file uploads (and expansion of supported file types). As an MVP here I think the four points you mentioned would be really interesting to look at further. I'm moving this one to the community backlog so that we can re-visit it going forward :beers:

**Comment by popmonkey** [comment]
i accidentally dropped a file on the "Click and drag files here" that has sensitive information it it.  github uploads are behind an authentication wall and will return a 404 if you don't have access, this is not the case with Zenhub.  obscurity is not good enough.
