### ISSUE TITLE
No or less obtrusive "Uploaded using ZenHub.io"

### ISSUE THREAD

**Issue by wvengen** [ZenHubIO/support#493]
When uploading files using ZenHub, this message is added. While I understand that it gives ZenHub exposure, I find it somewhat disturbing in the flow of reading a comment thread.

Suggestion: remove the message, or replace it with a non-obtrusive image right after or before the link (e.g. a somewhat grayed Z icon). For example:

![mockup-zenhub](https://cloud.githubusercontent.com/assets/503804/11587897/164763a4-9a7d-11e5-9abc-30ea8c66c9cd.png)

Thanks for considering!

**Comment by kevinSuttle** [comment]
:+1:

**Comment by aupright** [comment]
Thanks for the suggestion @wvengen - moving this one to the discussion pipeline to see if we can get more feedback on whether other users would prefer a different approach here as well. 

Thanks again for the feedback - keep it coming :smiley:

**Comment by shmooth** [comment]
:+1:

**Comment by azenMatt** [comment]
Hi all, 

A quick update on this one, we are currently looking into removing the file upload section in general - which will solve this problem! 

As GitHub now offer file uploads, it makes sense for teams to use the native GitHub uploader rather than the ZenHub uploader. 

GitHub still has a couple of file types not supported - so we are just confirming that removing the ZH upload won't have any negative impact on teams using those. It is likely we will phase the functionality out by moving the ZH icon to the new 'markdown bar' before we remove it completely.

**Comment by azenMatt** [comment]
and the file uploader is gone :smile:
