### ISSUE TITLE
Optimize use of screen real estate for projector display

### ISSUE THREAD

**Issue by matthewlmcclure** [ZenHubIO/support#511]
My team often displays ZenHub boards on a projector. The GitHub page header takes a large portion of the screen real estate. It would be better if ZenHub could hide the GitHub page header.

<img width="1552" alt="screen shot 2015-12-11 at 10 42 16" src="https://cloud.githubusercontent.com/assets/470362/11758315/7095836c-a037-11e5-8922-042ee1142465.png">

Secondly, we often click through to an issue on the projector and scroll down to the most recent comments. The modal header shows the issue ID, but not the title. It would be better if ZenHub could show the issue title also.

<img width="1552" alt="screen shot 2015-12-11 at 18 45 44" src="https://cloud.githubusercontent.com/assets/470362/11758320/74e22394-a037-11e5-9e7b-8535b09f5955.png">

**Comment by aupright** [comment]
Thanks for the feedback @matthewlmcclure!

We've actually received similar feedback before around having a full screen view for ZenHub (see https://github.com/ZenHubIO/support/issues/98). You can also find a bookmarklet that one of our former engineers put together that offers a solution here. In order to try and keep feedback centralized, I'm going to close this issue here and move the discussion to #98 :smiley: 

In terms of you suggestion to add an issue title to the modal, I'll make sure to document that one internally as something we can add going forward!
