### ISSUE TITLE
Bug: On Boards, when I click issue to get modal, contents never load - just waits forever

### ISSUE THREAD

**Issue by stephenakearns** [ZenHubIO/support#520]
Example: 

![image](https://cloud.githubusercontent.com/assets/13372164/11851577/f29da87a-a3f8-11e5-8759-361f74a7571e.png)

Environment: Chrome Version 47.0.2526.106 (64-bit) on Mac OSX Yosemite 10.10.5 on Macbook

**Comment by azenMatt** [comment]
Hi @stephenakearns - would you be able to update to v2.13.17? that will fix this issue for you!

**Comment by FirecatSue** [comment]
@azenMatt I'm using v2.13.17 and still having the "hung up" artifact @stephenakearns mentioned earlier. Advice?

**Comment by evfishr** [comment]
@azenMatt unfortunately we're still experiencing this. Are you saying we need to re-install the add-on?

**Comment by azenMatt** [comment]
It might be a refresh issue where ZenHub needs to pick up the new extension - does performing a manual refresh of the page help here? 

If not, would you be able to send through a screenshot of any errors in your dev console (view -> developer -> javascript console -> errors) that comeup whilst this is trying to load? That will help us troubleshoot further

**Comment by evfishr** [comment]
Here is the error our team is getting, hope this is helpful!
![screen shot 2015-12-16 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/10353530/11854783/101d8e68-a3fb-11e5-83b5-edcaae2260cf.png)

**Comment by evfishr** [comment]
It only works again if you re-install the add on...does everyone on our team need to do this or will there be a hotfix that is backwards compatible?

**Comment by azenMatt** [comment]
very strange, you shouldn't need to completely re-install. Just a full refresh should do it. 

You have to refresh the page with all the new extensions, otherwise the browser will upgrade the extension but continue to still uses the old extension script.

We are looking into this but can't find any additional issues - we should have another new version coming out shortly that will help to 'flush' this though. 

Is it happening for everyone on your team, or just a subset?

**Comment by evfishr** [comment]
it's happening to the full team. What do you mean by:
`You have to refresh the page with all the new extensions, otherwise the browser will upgrade the extension but continue to still uses the old extension script.`?

It's possible this is what happened & not the client side and the extension update are out of sync. we'll look forward to your next version release and hope that clears this up, or advise people to delete the extension and re-install

**Comment by azenMatt** [comment]
> You have to refresh the page with all the new extensions, otherwise the browser will upgrade the extension but continue to still uses the old extension script.

The update process for Chrome goes something like... 

1) Every 5 hours check for new updates 
2) If a new update is found, update in the back ground
3) If the extension is in use, continue to use the old version 
4) When a new session of the extension is triggered, load the new version 

Due to steps 3 and 4, you can end up in the situation where the chrome://extension page shows a newer version than you are actually using. 

This is fine for new feature releases / general maintenance - but isn't acceptable to us for critical bug-fixes. We are working on a new process for this so that we can notify you when a critical update (like the bug in this issue) is available - giving you the option to update the extension and refresh the page to ensure the latest version is downloaded and put into use. 

Please let me know if any of your team are still struggling with this problem and we can look into it further.
