### ISSUE TITLE
Issues Page - show story points

### ISSUE THREAD

**Issue by stephenakearns** [ZenHubIO/support#524]
We are using milestones to track epics (so the burndown is an epic burndown) which means I don't have a good sprint burndown :-( - if I want to measure throughput for a sprint, I have to go to the issues page, filter by date and individually inspect each issue for story points. (uggh - horribly manual). One small improvement would be to show story points in the issues view. (ideal solution: allow issues to be attached to multiple milestones so I can use burndown for both epic and sprints)

**Comment by azenMatt** [comment]
Hi @stephenakearns 

thanks for the feedback, we should have several updates coming soon that will help you out. 

The first is to introduce the concept of epics into ZenHub. 

The second is to improve the burndown page so that you can cut data in several ways - allowing you to get burndown information across several different ways of organizing issues rather than just milestones. 

Updating the issue page to show this information is also on our radar for a future release but has not made it into a release bucket yet. (but it is something we want to do!) 

Please let me know if you would like to discuss using epics in GitHub more as we are currently gathering user feedback on this so your thoughts would be very helpful! You can email me at matt@zenhub.io and we can find a time (the same goes for anyone else reading this that wants to talk epics or ZenHub!)

**Comment by stephenakearns** [comment]
definitely would be interested in discussing epics. 

copying a few folks who have had convos about same topic

thx

-----Original Message-----

**Comment by azenMatt** [comment]
Hi @stephenakearns - hopefully you have seen that the issue page now has both estimates and pipelines on it - which should make your filtering much easier!
