### ISSUE TITLE
First pipeline - Drag-to-reorder out of position

### ISSUE THREAD

**Issue by dmartinzar** [ZenHubIO/support#537]
Sometimes when an issue is reordered, it will jump 1 or more places to the left (or up) instead of landing where you dropped it. In the gif below I only managed to reproduce a jump of 1 position, but in our private work repository with 20x the number of issues we've seen moves of 5-10 positions or more.

![5col2leftbug](https://cloud.githubusercontent.com/assets/912952/12131646/3361a1c2-b3da-11e5-9b48-45a67f176c3a.gif)

Some notes:
- It always seems to jump behind rather than forward.
- There is some magic point (around 90 issues down) in our giant Backlog bucket where the problem becomes 100% reproducible and the jumps are drastic. When reordering the first 90 issues they generally land where we want them to, but sometimes the left-by-1 bug still occurs.
- It does not seem to be affected by filtering. The problem happens with or without an assignee filter. I find that when I look at my own 45 issues in Backlog, those that are below the 90 issue mark in the _unfiltered_ view will exhibit the issue, but those that are above it will not.

Under the covers I suspect this is two different issues. One has to do with swapping an issue with its immediate predecessor and the other has the do with data corruption at some point in the total ordering of our Backlog issues.

**Comment by dmartinzar** [comment]
Forgot to mention, this is using version 2.13.27 on Chrome.

**Comment by dmartinzar** [comment]
We solved the re-order issue by creating a "New Issues" pipeline and making "Backlog" our second pipeline. This split the existing "Backlog" tickets into two categories, some that were actually marked as "Backlog" and some that had no pipeline set and were automatically moved to "New Issues" when we created it. After individually dragging every issue to "Backlog", the problem went away.

We believe the issue occurs when you have a large number of tickets placed in the pipeline by default mixed in with tickets that have that pipeline explicitly set.

**Comment by azenMatt** [comment]
Nice spot @dmartinzar 



> We believe the issue occurs when you have a large number of tickets placed in the pipeline by default mixed in with tickets that have that pipeline explicitly set.

this is dead on - the first pipeline line is essentially 'everything that has been placed in the first pipeline' + 'everything that doesn't have a pipeline' which is causing this weird behaviour. 

We are going to refactor how this behaves to make sure the experience is exactly the same as all the other pipelines.

**Comment by stevage** [comment]
New user here. The current behaviour scared the crap out of me when I first witnessed it. Issues randomly jumping between unrelated pipelines just because I re-arranged their order? Total WTF - couldn't believe that a bug this severe could be in production:

![screenshot 2016-06-08 10 36 54](https://cloud.githubusercontent.com/assets/678344/15882689/98408440-2d84-11e6-905e-74184d90ab72.png)

![screenshot 2016-06-08 10 37 04](https://cloud.githubusercontent.com/assets/678344/15882694/a0543456-2d84-11e6-977c-012cd098ca17.png)


If for some reason you can't fix this quickly, I really think you should flag this to new users. The introductory text gives a very strong impression that the pipeline called "New issues" behaves specially (ie, receiving new, un-pipelined issues), whereas what should be communicated is that the *leftmost pipeline* behaves specially.

Now that I understand what's going on, it's manageable for us, but encountering this thing was nearly enough to make me immediately abandon Zenhub for our whole project.

**Comment by tejacques** [comment]
Reiterating the above sentiment -- definitely shocked that flipping the pipelines makes issues jump around in pipelines. It seems like a fix would be to specifically assign the "New Issue" pipeline to any new, uncategorized issue.

**Comment by azenMatt** [comment]
@stevage @tejacques - 100% agree with you, we should be able to have this fixed soon

**Comment by adamdry** [comment]
+1 Please fix, thanks.

**Comment by adamreisnz** [comment]
+1 I hope that the "soon" from July is "very soon" now 😄

**Comment by gilesbutler** [comment]
So does "fixed soon" mean a year later 😂 this still doesn't work properly. Given that it hasn't been fixed I think we'll use another tool!

**Comment by kendramoroz** [comment]
@gilesbutler thanks for patiently waiting while we work on this one! We've been diligently prepping for the launch of #156 which has meant the first pipeline functionality hasn't yet been launched but rest-assured it's coming 🎉  - We'll post updates here when more information becomes available on this functionality.

**Comment by azenMatt** [comment]
And this one is finally fixed and working as expected! 🍾
