### ISSUE TITLE
Allow to completely remove TODO's

### ISSUE THREAD

**Issue by mkurz** [ZenHubIO/support#542]
There is no way to completly remove a TODO.
You can just check it so it moves in the "Recently Completed" category.
I want a TODO to be completely gone, like it never existed.

**Comment by mkurz** [comment]
I know TODOs completely disappear when it (the issue or pull request) gets closed or merged. But I want to completely remove it even if it is still open.

**Comment by azenMatt** [comment]
Thanks for the feedback @mkurz 

At the moment we are working on the assumption that as the completed list is private to you - adding it to completion is the same as removing it. 

I appreciate that in reality a difference exists between removing it due to 'I'm not going to do this' and 'I just finished this' but for our V1 of this, to see how useful a GitHub based TODO list would be - we wanted to keep the UX as simple as possible. 

As we build out the TODO functionality and make it a more full featured TODO list (for example, custom notes and tasks) we will make sure this gets covered

**Comment by mkurz** [comment]
@azenMatt Thanks for your reply on this.

**Comment by shadowwalkersb** [comment]
:+1: for this feature. Another usecase is when a TODO item is added mistakenly. Now, I am stuck with items that I added when I was exploring this feature.

**Comment by kendramoroz** [comment]
Hey all - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
