### ISSUE TITLE
Some deleted milestones are still visible in the dropdown on the boards view

### ISSUE THREAD

**Issue by chris-fuller** [ZenHubIO/support#544]
@aupright We have deleted all milestones but there are still 4 milestones in the dropdown on the boards view. Please advise. Thx!

Related issue: https://github.com/ZenHubIO/support/issues/343

**Comment by aupright** [comment]
Hey @chris-fuller thanks for the shout out here—happy to help!

Have you gone through the outlined process of manually updating an issue attached to those milestones? This is necessary in order to force a refresh of the issue cache - which will simultaneously update the milestone to it's current state in ZenHub. 

In addressing some of the technical debt we've accrued over the past quarter, this is definitely something that we're hoping to come back to and develop a more robust solution around. Happy to continue troubleshooting on this thread here :beers:

**Comment by chris-fuller** [comment]
@aupright Sorry for being a n00b on this. But since we deleted the milestones, there are no longer any issues attached to the milestones. So we are not able to know which issues to update. Unless I am missing something. Can you please clarify a little further for us? Thanks so much!

**Comment by aupright** [comment]
Hey @chris-fuller not a problem :smile: 

If you filter those milestones on the board, you should be able to issues that are still attached (hence, which issues to update). Even if you delete a milestone, you should still be able to see a history of all assigned milestones when you scroll through an issue. If it works better, feel free to email me at aaron@zenhub.io and we can set up a time to go over things in person :+1:

**Comment by chris-fuller** [comment]
Hi @aupright. Ok, thanks for that clarification. Understood. Would definitely love a fix in the code to address this. As I'm not sure manually updating issues is a viable option. Meaning too many issues to manually update one at a time. And not wanting to notify participants for every one of these manual changes. If you have advice on either of those points, please let us know. Thanks again!

**Comment by aupright** [comment]
Hey @chris-fuller - completely agree here, and to be transparent, this is a focus for us going forward. As Matt mentioned in #343 this is definitely something that is bubbling up in priority :+1: Thanks again for the feedback here!
