### ISSUE TITLE
Don't assume I am always using github whenever I use Firefox

### ISSUE THREAD

**Issue by karlcz** [ZenHubIO/support#558]
The ZenHub extension for Firefox opens a tab and tries to get me to login and authorize access to GitHub every time I start Firefox.
- I do not retain cookies across browser restarts
- I do not visit GitHub every time I use Firefox
- I do not sign in to GitHub every time I visit GitHub
- I do not remain signed in with GitHub when not actively working on my repos

I can understand and tolerate #498 due to my discarding cookies.  But, I do not think it is appropriate for the extension to act like Firefox is a dedicated GitHub and ZenHub client. It should stay quiet and out of the way until I try to use its features...

**Comment by azenMatt** [comment]
All very valid points @karlcz 

We will get them all fixed :+1:

**Comment by wvengen** [comment]
Also applies to the Chrome extension.

**Comment by azenMatt** [comment]
The latest version - 2.16.49 - contains a fix for this. 

We believe the problem was cause by ZH trying to sign in when an update was detected. As we often release multiple times a day - this can happen a lot! 

It should now leave you alone when it updates in the background. 

Im going to close this issue by if you keep getting it please comment here and I will reopen it - just in case there are some other edge cases causing this
