### ISSUE TITLE
Move milestone selection above pipeline selection

### ISSUE THREAD

**Issue by Groostav** [ZenHubIO/support#577]
Hey guys,

This is a very minor but very annoying issue: Because zenhub makes the vertical layout of an issue's catagory pane (the thing on the right of each issue for milestone selection, tag selection, etc, with a `div` ID `partial-discussion-sidebar`) larger, when we go to set a milestone on _most_ of our monitors the milestone menu is longer than the page, causing some scroll bar confusion.

With Zenhub on firefox on my 1680X1050 monitor:
![1099 on firefox zenhub](https://cloud.githubusercontent.com/assets/1680611/12875542/1c3ccf9e-cda2-11e5-87c2-c743727e8a43.png)

with IE (no zenhub): 
![1099 on ie](https://cloud.githubusercontent.com/assets/1680611/12875541/1c3b0cb8-cda2-11e5-9404-c899bf5a2ad9.png)

Notice that if I wanted to tag the issue as `Iteration 76` I would first have to scroll down in the milestones context-menu, then in the again on the browser page as a whole.

I believe this is simply fixed by swapping the milestones item with the pipeline item, such that milestones is first and pipelines is third. Alternatively, if you want to keep githubs own ordering, then you could make miletones last and this would still not be an issue, since we have fewer pipe lines than anything else.

_Also, to defend my team, our process is such that issues don't get marked as closed until they are released, which is why we have so many overdue milestones._

**Comment by azenMatt** [comment]
Hi @Groostav 

I understand your pain point here. To prove some context on why we decided to put the pipeline first, it was because we believed this made the most sense from a hierarchy perspective. That every issue has a sense of progress attached to it - denoted by which pipeline it is in. Whereas not every issue has a milestone (or estimate / assignee etc). 

In terms of changing these positions, I am open to the idea if it is what the ZenHub community would prefer - so lets see if we can get some +1's against this issue :smile:
