### ISSUE TITLE
Jira bidirectional sync

### ISSUE THREAD

**Issue by dmjio** [ZenHubIO/support#579]
Is it possible to have bidirectional synching with jira and zenhub, where issues and milestones in zenhub become user stories / tasks in jira? 

Ideally any change in either system would be reflected in an equivalent way in the other.

**Comment by azenMatt** [comment]
Hi @dmjio - i'l leave this one open for the community to '+1' to see how useful it would be for everyone. 

Ideally, ZenHub should completely replace Jira :grinning: but I know that we still have a couple of features to catch up on before that will work for all teams!

**Comment by dmjio** [comment]
@azenMatt 
> Ideally, ZenHub should completely replace Jira :grinning: 

Agreed!, old habits die hard I guess

**Comment by solarch** [comment]
That is when you are in a mono environment.  When you work in environments that include multiple development companies across different countries, then sometimes, a group vote trumps (pls excuse the expression) your choice, which in the case of myself is definitely Jira.  So, my company does all of its work in Jira with epics, issues, sub-tasks and then summarizes them in ZenHub for the broader group.  We would love to have this be sync'd instead of manual.

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
