### ISSUE TITLE
Extend file upload to wiki pages

### ISSUE THREAD

**Issue by acidix** [ZenHubIO/support#59]
It would be great to have a possibility to upload files to S3 from the wiki page editor to *attach* files to wiki pages.

**Comment by basilweibel** [comment]
+1

**Comment by refried** [comment]
How many votes does this feature request need?  I'm assuming it's less effort (and therefore needs fewer votes) than "safari plugin", but I don't know.

**Comment by lbergelson** [comment]
This would be extremely helpful.

**Comment by azenMatt** [comment]
I think it is best to close this one, we have depreciated our file-upload functionality from the issue system due to the improved file uploads that GitHub have been rolling out. GitHub extending these to the wiki would be the best solution, https://github.com/isaacs/github/issues/192 is tracking a similar issue to this.
