### ISSUE TITLE
Group Issues (Sort Pipelines) by Assignee

### ISSUE THREAD

**Issue by adamkrellenstein** [ZenHubIO/support#609]
Priority doesn't make much sense across individuals...

**Comment by azenMatt** [comment]
Seems like a good idea to me, lets see how many :+1: reactions we can get :smile:

**Comment by Mottie** [comment]
I have a userscript that will allow [sorting of ZenHub issues](https://github.com/Mottie/ZenHub-userscripts) by selected sets of data:

![zenhub-sort-issues](https://cloud.githubusercontent.com/assets/136959/14061332/ec60109a-f34b-11e5-8ae8-118ab64a45a8.gif)

**Comment by azenMatt** [comment]
This is awesome @Mottie :smile:

**Comment by Mottie** [comment]
Oh well, the latest update broke both of my userscripts. Every card in a pipeline is now absolutely positioned with a fixed height 😢. So after sorting there are big gaps and hidden text (overflow is hidden) if the card becomes shorter. I don't know if I'll update the script since it would require recalculating the height and position of every card.

**Comment by azenMatt** [comment]
😢  sorry about that @Mottie  

This remains one of the most emailed feature request I get - we are looking at implementing this into the next couple of sprints here so we should be able to support it natively in the near future

**Comment by azenMatt** [comment]
This feature is now in progress based on the following designs:

![image](https://cloud.githubusercontent.com/assets/7584089/18768418/e1d73858-80d9-11e6-85e1-5b4e1ded344f.png)

We are looking to have this live during October :)

**Comment by azenMatt** [comment]
This is now live on v2.24.26 - which is being pushed out to everyone at the moment, providing the following options - 

![image](https://cloud.githubusercontent.com/assets/7584089/19952906/e9acdabc-a125-11e6-90a2-c9ca2f8a8b54.png)

We would like to keep adding to this, so please let me know what else would be useful!

**Comment by cbeams** [comment]
I think this change may have introduced a bug. I am unable to move issues within a pipeline to manually order them at all. The best I can do is move something into a pipeline in the first position. From there, I cannot move the issue anywhere else in the pipeline, nor can I move any other issue in the pipeline relative to the others that are already there.

**Comment by azenMatt** [comment]
Is this while the pipeline is sorted? or unsorted?

**Comment by cbeams** [comment]
Hm. I don't think I had sorted the column, but in any case, I am now once again able to manually sort cards within the column. I don't know what changed that made that possible.

A few usability issues in any case:

1. When the column is expanded beyond one row, the sort arrows disappear. This appears to just be an oversight in implementation.

2. I was confused by the sorting option in the first place. I was afraid that by clicking on any given sorting option, I would forever lose my manual sorting. This is why I'm pretty sure I hadn't sorted the column—because I was afraid to do so! One way to solve this issue would be to include "Manual" as an explicit (and default) sort option, and show it as already checked when people first click the sort arrows. I'm not sure that will completely resolve the concern that sorting will destroy any previous manual ordering, but it makes it more likely folks will try it at least.

3. I'm not sure that pushing the column expand / collapse controls down into the settings wheel is a good idea. I already find these hard enough to use, because I usually have to click them several times each. What I really want is to grab the side of the column with my mouse and stretch it. In any case, if I want to expand a given column let's say from one row wide to three rows wide, I now have to click four times to do it: settings wheel->Expand->settings wheel->expand. That's two more clicks than were necessary before.

**Comment by Mottie** [comment]
> please let me know what else would be useful!

Sorting by issue number would be nice!

**Comment by azenMatt** [comment]
Thanks for the great feedback @cbeams, responses to each point:



> When the column is expanded beyond one row, the sort arrows disappear. This appears to just be an oversight in implementation.

This was actually done on purpose to keep the implementation cost down, allow us to ship the feature sooner and see if people actually wanted to use it. 



> I was confused by the sorting option in the first place. I was afraid that by clicking on any given sorting option, I would forever lose my manual sorting. This is why I'm pretty sure I hadn't sorted the column—because I was afraid to do so! One way to solve this issue would be to include "Manual" as an explicit (and default) sort option, and show it as already checked when people first click the sort arrows. I'm not sure that will completely resolve the concern that sorting will destroy any previous manual ordering, but it makes it more likely folks will try it at least.

That is a great point - and should be a simple change. I'l see if we an get this one into an upcoming sprint. 



> I'm not sure that pushing the column expand / collapse controls down into the settings wheel is a good idea. I already find these hard enough to use, because I usually have to click them several times each. What I really want is to grab the side of the column with my mouse and stretch it. In any case, if I want to expand a given column let's say from one row wide to three rows wide, I now have to click four times to do it: settings wheel->Expand->settings wheel->expand. That's two more clicks than were necessary before.

Yes - and this was a bit of a test to see what is more useful to 'hide' in the cog. To try and make this easier we just shipped a change that makes sure expand/collapse comes back if sort is not available (so if the pipeline is fully collapses or great than 1 width. 

> What I really want is to grab the side of the column with my mouse and stretch it. 

This would be the best solution!

**Comment by azenMatt** [comment]
Hey @Mottie 👋 

yes on Issue number! 

A follow up question - what is useful here the issue number itself or that date it was created? 

As for a single repo, issue number == date created. But if you have multiple repos merged together, that isn't the case

**Comment by Mottie** [comment]
Yeah, date created would be the best. If you do that, then a sort of last updated would also be a nice addition.

**Comment by azenMatt** [comment]
> One way to solve this issue would be to include "Manual" as an explicit (and default) sort option, and show it as already checked when people first click the sort arrows. I'm not sure that will completely resolve the concern that sorting will destroy any previous manual ordering, but it makes it more likely folks will try it at least.

We just merged this in - it will be very interesting to see how it changes the usage numbers! 



> Yeah, date created would be the best. If you do that, then a sort of last updated would also be a nice addition.

That makes sense :)

**Comment by azenMatt** [comment]
> Yeah, date created would be the best. If you do that, then a sort of last updated would also be a nice addition.

This just went live in v2.24.36 :)

**Comment by adambuczynski** [comment]
> I'm not sure that pushing the column expand / collapse controls down into the settings wheel is a good idea. I already find these hard enough to use, because I usually have to click them several times each

A big +1 for this. Coming from Waffle, I've grown very attached to being able to collapse/re-open columns with a single click.

I think manually making them wider/smaller will be annoying when you invariably end up with a different width for each column, but moving the collapse button out of the cog wheel and having it quickly accessible just as the expand button would be great.
