### ISSUE TITLE
UI Freezes due to large amount of repos

### ISSUE THREAD

**Issue by slajax** [ZenHubIO/support#614]
I'm not sure if this is due to a recent release but when we load all our repos (28) - the UI freezes complete and we have to kill the chrome tab. 

Because the loaded repos are saved and reloaded per repo, it means you cannot use the ZH interface as any attempt to go to the repo automatically loads all 28 repos and freezes the interface.

We're trying to do some hackery with logging out, editing the URL and tricking it to update the cache to only load one repo at a time, but it would be better if it just didn't freeze in the first place when a large amount of repos are loaded at a given time.

**Comment by azenMatt** [comment]
Hi @slajax 

It does look like we recently introduced a performance bug, this was part of the recent release we did to improve the closed issue pipeline and try to ensure that it showed more information. 

The unintended consequence here, is that it is now loading 100 issues per connected repository - which for large groups of connected repositories is a problem. In your case, this means that you potentially have 2.8k issues trying to load into a single pipeline. 


We are already working on a performance refactor, which should be live in the next 2 weeks - this is aimed at making sure repositories of 1000's of issues behave just a well as a repository of 100 issues. 


While this is being worked on, we have identified two short term fixes that will enable normal use to continue. 

1) We are going to change the behaviour of the 'hide closed issues' button so that it remembers it in your browser cache - this means you can get improved performance be removing this whole pipeline (without it coming back when you reload). 


2) We are going to limit the initial load of closed issues to 100 issues - from the 'main' repo of a multi-repo board. Where the 'main' repo is the repository that you entered by. You will still have the option to see more closed issues by clicking the 'load more' button at the bottom of the closed issue pipeline. In the short term, this will still load 100 issues per repository (which will reintroduce the performance issues). In the long term, we will work out the best way to load more issues without introducing performance problems - we will base this on performance benchmarks once the refactor is live. 



We are aiming to get 1 and 2 live as soon as possible (best case scenario today, worst case scenario tomorrow) 

I will keep you updated

**Comment by slajax** [comment]
@azenMatt first thanks for looking into this so quickly. Those both sound like good short term solutions for us.

Would it also be possible to purge my current stored "auto" settings? That I can turn on the minimum repos that I require as my default is all 28, which obviously compounds the issue exponentially.

**Comment by azenMatt** [comment]
> Would it also be possible to purge my current stored "auto" settings? That I can turn on the minimum repos that I require as my default is all 28, which obviously compounds the issue exponentially.

These settings are all stored in your browser local storage, so you could either 

1) clear your browser cache 
2) you can run `localStorage.removeItem('ZH_BOARD_SETTINGS')` into the developer console

![image](https://cloud.githubusercontent.com/assets/7584089/13832222/4c2e200a-eb97-11e5-8b0a-5d4d2c0dde5e.png)



Another solution that might help if you have access to the URL, is to add the string `&showClosed=false` to the end of it, which will hide the closed issue pipeline

**Comment by slajax** [comment]
Ah right on, I looked to see if it was a cookie, but should have checked LS. I'll clear it now. 

Thanks!

**Comment by azenMatt** [comment]
We just pushed out the new version - 2.15.79 - that has both of those changes in it. From my testing it feels a lot fast. 

Would you be able to update and see if this works better for you?

**Comment by azenMatt** [comment]
Let me know if you would like me to re-open this. 

Further performance improvements are coming over the next two weeks
