### ISSUE TITLE
ZenHub board not showing

### ISSUE THREAD

**Issue by hindle** [ZenHubIO/support#628]
When I go to the board view, I'm just getting a white screen:
<img width="1440" alt="screen shot 2016-03-22 at 09 04 04" src="https://cloud.githubusercontent.com/assets/610816/13946525/0d39b74a-f00d-11e5-920e-36dc9860b4a0.png">

**Comment by yachafd** [comment]
I had the same issue. Try updating the plugin, it worked for me

**Comment by driesvints** [comment]
Same here. Running 2.15.85

**Comment by cesards** [comment]
+1

**Comment by mikeyhogarth** [comment]
+1

**Comment by laffy** [comment]
+1

**Comment by laurencesmithever** [comment]
+1

**Comment by benpholmes** [comment]
+1

**Comment by hindle** [comment]
Reinstalling the extension seemed to work

**Comment by mikeyhogarth** [comment]
Also managed to get this working by uninstalling / reinstalling. 

menu -> settings -> extensions, find zenhub, click the bin, go here https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/related and reinstall

**Comment by driesvints** [comment]
Even better solution => Go to [Extensions](chrome://extensions/), Enable developer mode & click on "update extensions now".

**Comment by azenMatt** [comment]
Hi all, thank you for the assistance with this. You are right that an update is required due to breaking change that occurred during Mondays GitHub outage that required us to push a new version. 

Anything past v 2.15.86 will contain the fix. 

I appreciate everyones frustration here and wanted to let you all know that we are working on a better way to get the extension to update / communicate to you that an update is required in case issues like this happen again. 

We had a new version live within moments of the problem being detected, but due to the nature of being an extension, it can take up to 24 hours for Chrome/Firefox to provide the update to you. Which results in a much longer downtime that needed.
