### ISSUE TITLE
Clear out New Issues pipeline

### ISSUE THREAD

**Issue by alloy** [ZenHubIO/support#642]
We just started using ZenHub, which means we have a few hundred issues in the ‘New Issues’ pipeline. We have added an ‘Icebox’ pipeline, where I would like to have all these issues that existed before the use of ZenHub, but am wondering what the simplest way would be for me to do that.

I saw the feature described in #118, but that still requires me to manually select _all_ the issues, which is painstakingly enough by itself, but I also quite quickly accidentally clicked outside an issue card which removed the previous selection.

I was unable to find any ways to make modifications through the API.

The simplest option I can think of is to _rename_ the current ‘New Issues’ pipeline to ‘Icebox’ and create a new ‘New Issues’ pipeline. However, I’m afraid that this might break the behaviour where newly filed issues show up in the expected pipeline.

So concrete, my questions are:

* Is the behaviour of newly filed issues showing up in the ‘New Issues’ pipeline purely based on the pipeline’s name and thus can I name another pipeline ‘New Issues’ and have new issues show up there instead?
* Or is there another way to easily move all those issues out of ‘New Issues’?

**Comment by azenMatt** [comment]
Hi @alloy 

The behaviour here is based not on the pipeline name, but on its position. 

Essentially, the pipeline which sits on the furthest left acts as the 'default' pipeline. Any Issues you create that do not have a pipeline specified during creation, will go to the furthest left. 

We called this 'New Issues' to give a sense that this was a pipeline where things sit awaiting triage, rather than a longterm home. 


Unfortunately, the best solution I can offer here to get everything out, is the one in #118, the most practical way to do this would be to go 'full screen' (the button next to the repo selector on the far left) and expand the pipeline several times (via the button at the top of each pipeline next to the cog). This should at least make it easier to select an move a page of issues at a time without clicking off as they will appear in a more grid like fashion! 

On this subject, all pipelines are currently draggable - except for the first pipeline due to some of the backend logic that needs a refactor. This is on our backlog, but will not be soon enough to help you here I am afraid! 

Please let me know if there is anything else i can help with!

**Comment by alloy** [comment]
> the most practical way to do this would be to go 'full screen' (the button next to the repo selector on the far left) and expand the pipeline several times (via the button at the top of each pipeline next to the cog). This should at least make it easier to select an move a page of issues at a time without clicking off as they will appear in a more grid like fashion!

Ah didn’t think of that one, thanks! Will try to make do with this.
