### ISSUE TITLE
Show only Epics button

### ISSUE THREAD

**Issue by alexmattos** [ZenHubIO/support#660]
Hi,

Epics are fantastic functionality (so much so that I am considering stopping my Aha! subscription). There are a few additional things I'd like to be able to do with them

1. Only show the issues from 1 Epic - I can do this with the 'Epic' label and then click "Filter by this epic' which then doesn't show anything because I still have the Epic label filter on.

2. An Epic view - only show the epics - again I can do this with the Epic label filter but perhaps have a separate button like the one for 'Pull requests' or closed issues.

Not showstoppers at all but suggestions.

**Comment by azenMatt** [comment]
Hi @alexmattos - i'm glad to hear that you are finding these useful



> Only show the issues from 1 Epic - I can do this with the 'Epic' label and then click "Filter by this epic' which then doesn't show anything because I still have the Epic label filter on.

You should be able to clear these filters separately, so clicking the 'x' next to the label filter will leave the board still filtered by the Epic. This is more clicks than I would like ideally (filter by label, filter by epic, unfilter by label...)  - but it should accomplish the desired outcome? 

 

> An Epic view - only show the epics - again I can do this with the Epic label filter but perhaps have a separate button like the one for 'Pull requests' or closed issues.

Yes, we have been playing with this idea. We really want to avoid adding unnecessary complexity, which is why we opted to re-use the existing label feature. But happy to reconsider this if lots of people will find it useful to be able to easily dive into a highlevel 'roadmap' view that just contains Epics.

**Comment by alexmattos** [comment]
Yes - definitely a roadmap view would be very helpful. I can live with the multiple clicks.

Also - when an epic is assigned a milestone it would be really helpful if all the issues inside it were also assigned that milestone.

**Comment by azenMatt** [comment]
Hi @alexmattos - we just added in some additional filtering for epics which should help your initial use case:

![image](https://cloud.githubusercontent.com/assets/7584089/19776998/1e9b2526-9c2b-11e6-85f4-b36066ae8897.png)


Using this new drop down you can show just epics as well as easily filter on a single one

for 

>Also - when an epic is assigned a milestone it would be really helpful if all the issues inside it were also assigned that milestone.

We have a multi-select / multi-action release coming up in November that will really help here!
