### ISSUE TITLE
Todo List Dashboard

### ISSUE THREAD

**Issue by sandwedg** [ZenHubIO/support#662]
In order to help manage our teams we would really like the ability to see all of the Todo Lists of our team in one view.

**Comment by azenMatt** [comment]
Thanks for the feedback @sandwedg - I can see how this would be very useful, I have added this to discussion pipeline to get further feedback from the ZenHub community

**Comment by kendramoroz** [comment]
Hey all - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
