### ISSUE TITLE
Time tracking or cost for cost analysis

### ISSUE THREAD

**Issue by hanoii** [ZenHubIO/support#670]
I am seriously digging ZenHub, however, time tracking/cost, or at least a way to add that information to an issue would be a great addition to an already great tool. It's been discussed on other issues but I think from different approach.

I like the agile decision of using story points for estimation. However, there should also be another entry point for cost. I am using the term cost because it could be more abstract. This could be a figure of time, money, energy, coffee mugs. It really doesn't matter how you call it but a figure that's tied to a user (not globally to an issue) would allow you to see how's your cost performing.

The way I see this being very useful, and I know PM become very personal, is as follows:

You would have the option to add/edit an entry to an issue, something in the line of:

"hanoii worked 30 <placeholder unit> on this issue"

This would be stored and showed similar to when you moved an issue from one board to another, with a dollar sign  or something.

Each person can add more time to is as they work. This will ensure we have both a figure and a date associated with that entry. I don't think this is editable, well, I guess you can do whatever you want on the interface, but I am unsure if how you inject the "pipeline move" log entry is custom or within the api definition. But if edition/remove of such an entry without being a comment is not possible, I would then simply allow for a negative value, which could be even better.

With this information, a lot of things can be done, but the immediate one that you get is the possibility of putting a cost curve on top of the burndown chart you already have, giving a nice contrast on how issues completion, with their storypoints are translated to costs.

**Comment by molant** [comment]
I think that [scrum for trello](https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje) has this feature or very similar. You have estimate points and then you have consumed points (which can be greater than the estimate). This is also good for updating the burdown. Right now it seems to only be updated when a task is closed :(

**Comment by da4089** [comment]
I would like to have some means of tracking hours worked on issues (as a consultant, I need to track that to charge my clients).  I like the idea of having the "cost" metric be unit-less, so it could be used for hours or story points or whatever.

There are several different GitHub plugins that do this with special syntax in commit messages or issue comments, but it'd be nice if it was integrated within ZenHub.

**Comment by NoopDog** [comment]
Try Harvest, there are many many use cases that have to do with time
tracking and billing and harvest mixes ok with GH and ZH.

Works for us.

Your results may vary.

D

------------------------------
Dave Rogers
Partner, Clever Canary
646-286-5371
http://clevercanary.com

@CleverCanary
@_DaveRogers
https://www.linkedin.com/pub/dave-rogers/0/90/92


On Sep 9, 2016, at 7:14 PM, David Arnold <notifications@github.com> wrote:

I would like to have some means of tracking hours worked on issues (as a
consultant, I need to track that to charge my clients). I like the idea of
having the "cost" metric be unit-less, so it could be used for hours or
story points or whatever.

There are several different GitHub plugins that do this with special syntax
in commit messages or issue comments, but it'd be nice if it was integrated
within ZenHub.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZenHubIO/support/issues/670#issuecomment-246065941>,
or mute
the thread

**Comment by tj** [comment]
It would be cool if point estimates were a slider or something, then you could at least pretend they're hourly estimates. I find since they're arbitrary it's a little hard to gauge what you may have left

**Comment by iam-merlin** [comment]
In fact, just the ability or a best practice for coding zenhub extension (for Chrome for example) will be really nice...

This can be done using "chrome.runtime.sendMessage" (for Chrome extension), we will be able to hook this event and extend zenhub with for example a timetracking button...

**Comment by jschreck** [comment]
@NoopDog - Harvest is what we use across all our tools. Unfortunately there isn't a way to [easily] integrate it with Zenhub or Github, unless I'm missing something. Do you have any suggestions?

**Comment by kendramoroz** [comment]
Hey everyone, I'm working on cleaning up our support community, consolidating time tracking into a single issue for better tracking. If you're still interested in tracking updates, please subscribe to https://github.com/ZenHubIO/support/issues/218!
