### ISSUE TITLE
Add ability to filter issues by multiple epics

### ISSUE THREAD

**Issue by dan-greff** [ZenHubIO/support#680]
It would be nice to have a view of all issues related to multiple epics.  I tried to hack the view by specifying multiple Epic issue numbers in the url but that didn't work.

**Comment by azenMatt** [comment]
Thanks @dan-greff - we will see what we can do here, agreed that this would be useful!

**Comment by Anvil102** [comment]
+1

**Comment by azenMatt** [comment]
Hi @dan-greff @Anvil102 

We just added a new drop down to the board specifically for epics - this will allow you to select and view multiple epics on the board:

![image](https://cloud.githubusercontent.com/assets/7584089/19776660/d2b778f4-9c29-11e6-948c-103fb75efda7.png)

Let me know if this doesn't help solve the root cause here :)

**Comment by Anvil102** [comment]
Thanks @azenMatt! I'll play with it and let you know. So far it shows a lot of promise!
