### ISSUE TITLE
Add ability to show all issues that are not in an epic

### ISSUE THREAD

**Issue by alexmattos** [ZenHubIO/support#682]
It would be useful to be able show issues that are not assigned to an epic - as we can do with issues that have no milestone.

**Comment by alexmattos** [comment]
how do I build a negated filter - like the filter for issues that are assigned to no-one or not in a milestone?

**Comment by azenMatt** [comment]
Thanks for the feedback @alexmattos - currently this is not possible, we will take a look into how we could offer this

**Comment by fotoflo** [comment]
how to vote?... this gets a vote!

**Comment by azenMatt** [comment]
@fotoflo - adding a 👍  reaction to the opening post is the best way :)

**Comment by cbeams** [comment]
The implementation of this feature as well as #742 would represent a big leap in usability of epics. I've voted for each—just want to point out here that I frequently think of and wish for these two features at the same time while managing my boards.

**Comment by azenMatt** [comment]
thoughts on the following as the implementation detail for this - 

![image](https://cloud.githubusercontent.com/assets/7584089/19199920/45e684aa-8c7b-11e6-97ad-3b7815936527.png)

We add a new filter at the top, which is just for finding epics. This always contains two 'special' fields in addition to each epic:

1) Show all Epics 
2) Show all Epics and sub-tasks

Using the 'not' filter functionality, you can filter on `not:show all epics and sub tasks` which will limit the board to everything not in an epic?

**Comment by cbeams** [comment]
Sounds good Matt. As a convenience, however—and for symmetry with the Milestones menu—why not have an 'Issues without an epic' menu item at top, which can simply map to the `not:` expression you mentioned, and in doing so help educate users about its existence?

As an aside, have you considered the simpler `-` operator instead of `not:`? Aside from being less verbose, it is also what GitHub uses in its own issues query language. Ideally ZenHub QL (if you will) should be a superset of GitHub Issues QL; barring that it should at least be syntactically similar where there is no compelling reason to diverge.

**Comment by azenMatt** [comment]
> why not have an 'Issues without an epic' menu item at top,

Thats a great point, 'show all epics and sub-tasks' is very wordy - I think `Issues without an epic` would work better 



> have you considered the simpler `-` operator instead of `not:`? Aside from being less verbose, it is also what GitHub uses in its own issues query language. Ideally ZenHub QL (if you will) should be a superset of GitHub Issues QL; barring that it should at least be syntactically similar where there is no compelling reason to diverge.

This is also a great point! we could probably look to include both so that as a user you can decide if you want to us `-` or `not`. 

The reason that we went with 'not' here for the initial change, was that lots of teams use ZenHub to bring less technical / non-development team members into GitHub. One of the big problems I have observed is that these users struggle to find what they need in GitHub due to the way all of the search screens are set up for users who have mastered the GitHub keywords. 

I wanted to make it a bit more user friendly for this use case. 

A great example of this is how Slack does it vs GitHub. 

Here is the GitHub search box when the user selects it:

![image](https://cloud.githubusercontent.com/assets/7584089/19204029/5bf1efe6-8c8f-11e6-94a3-02614151d1ed.png)

vs slack:

![image](https://cloud.githubusercontent.com/assets/7584089/19204054/81adc0a2-8c8f-11e6-8026-fd05775940cb.png)


They both have powerful search, but one is much easier for non-technical users than the other. 

The ZenHub search still has a way to go - but ideally it will have the power of the GitHub search, with the usability of the Slack search :)

**Comment by azenMatt** [comment]
i'm a bit late to the party updating this one, but this feature went live a short while ago:

![image](https://cloud.githubusercontent.com/assets/7584089/19984868/69e36050-a1cd-11e6-81ec-4149b37a3e77.png)

😀

**Comment by cbeams** [comment]
This is fantastic! Just played around with it for five minutes and am very happy with what I see. Thanks!
