### ISSUE TITLE
Post-processing of pull requests

### ISSUE THREAD

**Issue by bmuschko** [ZenHubIO/support#688]
The project I am working on created a [board for tracking pull requests](https://github.com/gradle/gradle#boards?repos=302322). We'd like to be able to have one or many columns for tracking actions required after a pull request has been merged. Currently, a merged pull request shows up in the "Closed" column. The UI doesn't allow for adding columns for tracking work after a PR ends up showing up in the "Closed" column. It would be very beneficial to our project to track post-merge work. 

Examples:
- Has the PR been reviewed by a peer.
- Is the PR critical for inclusion for the release.
- Is the PR properly documented before a release can be cut.

**Comment by eskatos** [comment]
Related to #233

**Comment by azenMatt** [comment]
Hi @bmuschko - your use case makes a lot of sense. I have added your comment to #233 so that we can concentrate the information in a single issue. 

Currently we are keeping all closed issues/PR's in the closed pipeline, but with enough support in #233 we can start looking into allowing closed issues to live elsewhere in the flow

**Comment by kendramoroz** [comment]
Doing some clean-up on the support board and noticed the duplicate here to #233 @eskatos and @bmuschko please +1/comment on #233 to continue following the conversation or reach out to the support team at any time for an update!

🚀  happy new year
