### ISSUE TITLE
Long and annoying discussion feed

### ISSUE THREAD

**Issue by csaintc** [ZenHubIO/support#703]
Hey guys,

We're interested in ZenHub, but the discussion feeds are really long and annoying, and I don't really see the value added in them. Is there a way for me to cut down on chattyness in the discussion feeds?

Image of what I'm talking about attached:

![image](https://cloud.githubusercontent.com/assets/907929/14862044/5c590cac-0c75-11e6-93bf-842756dc3c2c.png)

**Comment by Mottie** [comment]
I have a userscript that will allow you to hide specific entries, all "+1" entries or ZenHub pipeline changes.

Get more details here: [GitHub-issue-comments](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-issue-comments)

**Comment by azenMatt** [comment]
Hi @csaintc - thanks for the comment. We are currently looking into ways to better group these changes. So that you have the benefit of an audit trail of events - without the long period of action notifications. 

In the meantime, hopefully that plugin for @Mottie will be useful

For what it is worth, we find this to be much less of an issue in 'day-to-day' development as the changes tend to be further spread out than in the example you posted.
