### ISSUE TITLE
No keyboard shortcut for New Issue

### ISSUE THREAD

**Issue by stewhouston** [ZenHubIO/support#708]
There doesn't seem to be a keyboard shortcut to bring up the New Issue overlay when on the Boards page. Can this please be bound to 'n' or '+' or something of that nature? The button is terribly far from the page content and makes adding new tasks cumbersome.

Mega bonus points if it would be possible to quickly create a new issue by right clicking in a pipeline and/or adding a a New Issue option to the Gear/Settings dialog menu.

**Comment by azenMatt** [comment]
A shortcut for this sounds like a good idea to me :)

**Comment by gbourel** [comment]
:+1:

**Comment by kendramoroz** [comment]
Hey @junketjim we've just launched a suite of new Keyboard shortcuts (there's 35!), including `n` `i` to create new Issues 🎉  

You can review the full list here: https://www.zenhub.com/guides/keyboard-shortcuts
As well as access shortcuts at anytime by heading to the `Settings` dropdown on the Board (or hitting `z` `s` in the web app)

![screen shot 2017-10-13 at 4 20 51 pm](https://user-images.githubusercontent.com/11036230/31569809-cb309c1e-b032-11e7-89a0-47565dc1221d.png)

Let us know what you think!

**Comment by a-laughlin** [comment]
Thanks for adding these ZenHub team!  Really appreciate them and look forward to the speed increase familiarity brings!

Also some feedback:

### Shortcut Menu

Learning them feels a bit frustrating.  I'm finding that I forget either the shortcut, or what I'm trying to do, or both.  I think it's the memory load imposed by the shortcut interaction flow:

1. Remember the set of actions I'm trying do.
1. Remember the UI representing where I want to do them.
1. Figure out how to get to shortcuts.
1. Read the shortcut categories.  Determine which applies.
1. Read each shortcut. Determine which applies.
1. Remember the action the shortcut does.
1. Remember the shortcut letter for that mode.
1. Remember the shortcut letter for that action.
1. Remember which letters are supposed to map to the mode I want.
1. Remember each of the modes.
1. Remember the descriptions of each mode.
1. Start navigating back, through modes.
1. On each mode, recall the possible modes, recall the mode descriptions, recall the mode I want, decide whether each mode passed fits the description.
If it does:
1. Recall the shortcut letter for that mode.
1. Recall the letter for the action I want.
1. Recall the action I wanted to do.
1. Type the shortcut letters.
1. Recall the set of actions I intended.
1. Continue working.

That's more than most people's working memory can keep up with, especially if my work involved a long sequence of actions before trying to use a shortcut.

May I suggest a shortcuts bar, toggleable with the commonly used `cmd + /`, that shows only the shortcuts for the mode you're currently in?  That lets users learn more efficiently and effectively while retaining context to get stuff done.

With a shortcuts bar toggled on, the sequence is:
1. Remember the set of actions I'm trying do.
1. Glance up to see possible shortcuts
1. Decide if a shortcut applies
1. Type the shortcut letters
1. Recall the set of actions I intended.
1. Continue working.

No need to retain mental maps of state, mode descriptions, mode-to-key mappings, etc.  Much faster to learn and use.

### Shortcut Letters
Using the same shortcuts in different modes (e.g, `b+l`), prevents muscle memory from applying, which means higher ongoing cognitive load.  Different keys for each mode are easier to learn, and much faster to use with experience.

Also, some UI indication of mode would be helpful.  Given distinct letters for different modes, a simple `b` somewhere in the UI can indicate the first letter for the mode, making recall easier once the shortcut keys for that mode are partially learned.

### Shortcut Error Feedback
Using shortcuts in the wrong mode gives no feedback.  That slows learning because my brain can't determine if its memory of the shortcut is wrong, the mode is wrong, there's a github problem, a user problem, a ZenHub bug, or what.  Incorrect shortcuts attempted should have an error message confirming that it's a valid shortcut, this is the incorrect mode, and explaining the correct mode it should be used in.  That way my brain can confirm it learned the shortcut correctly, but still needs to learn the modes better.

### Summary

Hopefully this feedback helps.  All products are works in progress.  These shortcuts are fantastic step toward making us all more efficient and effective.  Appreciate you all and am grateful for your work!
