### ISSUE TITLE
Feature Requests / Issues that I have with Zenhub

### ISSUE THREAD

**Issue by nijikokun** [ZenHubIO/support#736]
I'm a huge lover of Trello, and I so want Zenhub to be a better Trello but it just isn't. It really isn't, I try deluding myself to it but I end up going back to Trello.

I'm not trying to rail on you guys, these are just the things that really push me (and company) away from Zenhub and back into Trello's arms.

**Integration issues**

1. Better icons
2. Ability to disable burndown tab, never used it
3. Ability to disable the todo feature

**Deadlines**

The scrum "estimate" field in issues doesn't give urgency and priority like a good date and time does.

**Epics**

I'd just like to start off that it is a great idea.

But it was poorly implemented, it is like a miniature milestone, but it really isn't, the issues can't be moved around, prioritized, and they get lost in a slew of comments on the issue.

Should be more like a milestone that you can attach issues to across boards, and separated into it's own tab, where it shows a board like representation of an epic (you can select which epic beforehand). This would allow to move your issues around in the pipeline within that epic, and show progress / priority / deadlines (as mentioned above).

This would allow issues to stay clean and focused, while the epic grows and is easy to manage.

**Comment by eddiethefoot** [comment]
How about a little empathy? :)
Your feedback is needlessly emotional. ZenHub isn't looking to ruin your day and I'm sure they are actively looking to best competing products out there. Just because it's not there right now it doesn't mean they're not on the way there.

That being said, to your points - 

> The scrum "estimate" field in issues doesn't give urgency and priority like a good date and time does.
It's not supposed to. If you're familiar with agile methodology, estimation in points is supposed to be a team-specific measurement of a task's complexity. It's NOT supposed to create a sense of urgency and priority. Prioritization of cards, and timeboxes are supposed to. And if your team has to rely on a date to get a sense of urgency and priority, you might have underlying issues that no tool will ever fix.

> But it was poorly implemented, it is like a miniature milestone, but it really isn't, the issues can't be moved around, prioritized, and they get lost in a slew of comments on the issue.

I think it was implemented just fine. I think the UX around creating and managing epics could use some work, but conceptually the way ZenHub approached this issue is sound in my opinion. Whenever speaking of epics, milestones, tasks, and sub-tasks, one has to understand that the difference between them is in quantity, and not so much quality. Some epics can be small sub-tasks for some people (or teams), and vice versa. Epics in ZenHub seem to be treated as "larger" issues, and they CAN be moved up and down your workflow accordingly as issues belonging to that epic are completed.

**Comment by nijikokun** [comment]
Woah, what is with the personal attacks here? Why are you being so aggressive?

**Comment by nijikokun** [comment]
I'm closing this in favor of a private discussion with zenhub.

**Comment by eddiethefoot** [comment]
...personal attacks? Alright there XD
Also, I'm not part of the ZenHub team. I'm just a new user of the platform, and a long-time user of Trello.

**Comment by nijikokun** [comment]
Yeah, I can tell.

**Comment by azenMatt** [comment]
Hi @nijikokun @eddiethefoot 

I'm Matt from the ZenHub team, 

Thank you both for your comments, @nijikokun - I do really appreciate you taking the time to provide this feedback as it is very useful for us to continue to work on and improve ZenHub for everyone. 

Please feel free to email me - Matt@ZenHub.io - if you would like to continue the discussion.
