### ISSUE TITLE
ToDo List needs a "Back" Button

### ISSUE THREAD

**Issue by Anvil102** [ZenHubIO/support#752]
##### User Story

As a user, when I navigate to my ToDo list in ZH I should have the option to navigate back to my last GH page without having to use my browser's back button. If I navigate from board --> ToDo then the ToDo page should offer a "back to [XYZ] board" button. If I navigate from milestones --> ToDo then the ToDo button should offer a "back to [repo name] milestones" button. ...and so on.

**Comment by Mottie** [comment]
You can click the "ToDo" link a second time to take you back... but it won't ever take you back to a boards view.

**Comment by Anvil102** [comment]
Good point. Thanks for noting that. But it doesn't quite fully get to the described feature above, which I think would have some merit in implementing at some point in the future.

**Comment by azenMatt** [comment]
Thanks @Anvil102 , @Mottie - agreed this needs a better back button 👍

**Comment by kendramoroz** [comment]
Hey all - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
