### ISSUE TITLE
Assignee board filter not working properly with multiple assignees

### ISSUE THREAD

**Issue by josescgar** [ZenHubIO/support#765]
If a ticket is assigned to more than one person, let's say person A and then person B, the following happens when filtering by assignee in the boards view:

- If I select **only person B**, the ticket is **not shown**
- If I select **only person A**, ticket is **shown**
- If I select **both person A and B**, ticket is **not shown**

**Comment by controlz** [comment]
+1 This is very important to my team. GitHub released multiple assignees to issues on May 27.
https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

That update was a long time desired for my team so we were thrilled to see it finally hit!  Problem is now in ZenHub Boards, team members are not seeing issues they are assigned too when filtering by themselves (due to the scenario @josescgar explained above). It's causing people to miss tasks.

Please consider upping the priority to conform to GitHub's available features. The image of the assignee can still show one if too complicated to show many, but the filters definitely need to show any issues the user is assigned too, even if another is also assigned.

Thanks.

**Comment by controlz** [comment]
Sorry didn't see a related issue for this in the community backlog pipeline.
Related to #758

**Comment by azenMatt** [comment]
Thanks @controlz - I appreciate that is really painful 

We just discussed this and have re-prioritized the problem. The team will be starting on it tomorrow morning so we should have this out for everyone soon

**Comment by rkurbatov** [comment]
Would be nice to fix that, our productivity suffers from that issue. Thanks.

**Comment by controlz** [comment]
That's great news! Thanks @azenMatt, appreciated.

**Comment by azenMatt** [comment]
Hi @controlz @rkurbatov @josescgar - this is now live on version 2.19.1 

two people will now show on a card like so: 

![image](https://cloud.githubusercontent.com/assets/7584089/16625003/c02a7ad6-4357-11e6-8056-931b89d11ec7.png)


and 3 or more as: 

![image](https://cloud.githubusercontent.com/assets/7584089/16625053/ecbe0efa-4357-11e6-86ad-f7392dc1b0d8.png)


Usernames for the assignees will show up on hover

This also means the filtering works such that:

- If I select **only person B**, the ticket is **shown**
- If I select **only person A**, ticket is **shown**
- If I select **both person A and B**, ticket is **shown**

Let me know if you have any questions / comments!

**Comment by controlz** [comment]
That is so wonderful.
Looks/works Great. Nice job ZenHub! :smiley: 

Thanks @azenMatt.

**Comment by rkurbatov** [comment]
Thank you!

**Comment by josescgar** [comment]
Thank you very much @azenMatt
