### ISSUE TITLE
ZenHub Appeal

### ISSUE THREAD

**Issue by mpaler** [ZenHubIO/support#768]
Dearest ZenHub Team:

Whether it's "auto-following" GitHub labels, setting pipeline via commit messages, or using webhooks or other API related functions, it's clear there is something missing with ZenHub: _people need to control how and where issues move within the pipeline_.

This need has been expressed by your user base for over two years! Over and over the communication from ZenHub on this feature is pretty vague. 

So here's the appeal: In the spirit of transparency and planning, can you give us some guidance as to if and how you plan to address this? 

### [use label for Board's pipeline management](https://github.com/ZenHubIO/support/issues/19)
**Issue #19 Opened Nov 20, 2013 - #4 in Most Upvotes**

"As a new user that is evaluating this versus what we currently use heavily (Huboard), a key feature I need is a configurable workflow. I do like the workflow/pipelilne associated with labels, since we do have many teammembers that use CLI heavily and pull in pipeline issues based on the particular tag." [JeffLowe commented on Nov 21, 2013](https://github.com/ZenHubIO/support/issues/19#issuecomment-29021441)

"One of the reasons I like this suggestion, #19 to link certain labels to the pipelines, is that it would allow Github users who don't have zenhub.io installed to see where the ticket is in development.

Ideally all the users would just install zenhub and see the nifty pipelines in all their splendor, but not everyone uses chrome, etc. and some of the users barely have a Github account, etc." [wc8 commented on Jan 10, 2014](https://github.com/ZenHubIO/support/issues/19#issuecomment-32054963)

"the labels-as-pipelines (or pipelines-as-labels) feature does have several important benefits and that's why we're working to find a way to implement it that preserves our clean and easy UX." [roham commented on Nov 6, 2014](https://github.com/ZenHubIO/support/issues/19#issuecomment-62052078)

"We're evaluating ZenHub as a replacement for Waffle.io at Docker, and this is a pretty important thing for us. It's so people who haven't got ZenHub installed can see what an issue's status is and update it without the Chrome extension." [on Aug 11, 2015](https://github.com/ZenHubIO/support/issues/19#issuecomment-129801687)

"you will be pleased to hear that we officially do have this on our roadmap as part of a piece of work to improve how the ZenHub board data can be visualized and manipulated. _No firm implementation date at this point_ - we will keep you updated" [azenMatt commented on Aug 14, 2015](https://github.com/ZenHubIO/support/issues/19#issuecomment-131264118)

"This is what doesn't allow me to use ZenHub at the moment. For me this feature is really important, not only to migrate from other service (HuBoard for some repos, Waffle.io for others), but also to be able to communicate the issues state to the team members that don't use ZenHub (which unlike other services doesn't provide a web-interface without installing any plugins)." [laughedelic commented on Mar 10](https://github.com/ZenHubIO/support/issues/19#issuecomment-195116806)

### [Programmatically changing pipeline](https://github.com/ZenHubIO/support/issues/58)
**Issue #58 - Opened Mar 5, 2015 - #7 Most Upvotes**

"Bump. This is one of the very few hangups holding us from adopting zenhub for our organization." [tylerwhipple commented on Sep 30, 2014](https://github.com/ZenHubIO/support/issues/58#issuecomment-57359856)

"With an API, we could completely automate these. Anytime someone is assigned to an issue we move it to in progress, anytime someone opens a PR that references an issue we move it to testing / code review, closed is closed etc..." - [Jul 24, 2015](https://github.com/ZenHubIO/support/issues/172#issuecomment-124793231)

"this would be awesome to be able to sync for example state information between zenhubs pipelines and github labels. as it is now, you'd go blind in terms of state of you eventually get rid of zenhub, which is currently a blocker for getting on board zenhub to start with." [Sep 14, 2015](https://github.com/ZenHubIO/support/issues/172#issuecomment-140048610)

"Looks good but I'd really like to be able move issues across boards using this API if possible. It's a missing piece at the moment in our automated issue management and assignment." -- [Jan 19, 2016](https://github.com/ZenHubIO/support/issues/172#issuecomment-172829410)

### [Closing an issue should not simply move it to "Closed" pipeline](https://github.com/ZenHubIO/support/issues/233)
**#233 opened on May 15, 2015, 16 Upvotes**

**Related**
* [Post-processing of pull requests](https://github.com/ZenHubIO/support/issues/688)
* [ZenHub Public API](https://github.com/ZenHubIO/support/issues/172)
* [How I can move issue between pipelines using API?](https://github.com/ZenHubIO/support/issues/554)
* [Add issue pipeline changes to API](https://github.com/ZenHubIO/API/issues/20)

**Comment by azenMatt** [comment]
Hi @mpaler 

Thank you for taking the time to put this together. I really do appreciate the time you have taken to do so. 

As more and more users begin to rely on ZenHub to improve their GitHub workflows, it is clear that I need to find a better way to start communicating a Public Roadmap. This is going to take some time to put together, but I will get us to the point where we can use this repo to better communicate what is currently happening with the project. 

While that is worked on, I can share our current plans here and provide some feedback on the issues that you have highlighted. 

One point I do what to pre-face this with, not as an excuse for in-action, but to provide some context. Is that we are currently a small team - 4 developers work on ZenHub. Everyone of them is working exceedingly hard to ship improvements to the product. But we need to do more... we are currently hiring and this seems like a great place to make a plug for that! So please send anyone you know that would be a good fit here - https://angel.co/zenhub/jobs ! 

So what are we working on at the moment.... 

**Performance**
This is our number 1 issue. ZenHub is two years old and when we first built it we vastly underestimated the number of issues and number of joint-repos that users would want to work over. This means that for many ZenHub users the performance is really unacceptable. This is the number one complaint that hits my inbox.

We have spent much of the last few months trying to fix this issue. Initially thinking that we could do so by fixing the current code, the technical debt proved too high. Hopefully you have seen some performance improvements recently from the work we have done, but it isn't enough. Once we came to this conclusion, we had no other option than to re-write the board logic using everything we have learnt over the past couple of years. We performed some quick experiments and came to the conclusion that moving to react would yield both the performance and simplicity improvements we were looking for. This has now been the focus of the team since. 

As you know, it is very tough to put a timeline on a refactor, but we are looking to have this live before the end of June. This will allow us to get back to shipping new improvements for the project. 

**Board Improvements**
Once we have the refactored board live, we will be able to start making improvements to it again. Over the past 6 months, we have been very hesitant to do this due to the growing tech debt in this area. The big next steps are: 

- Multi assignee support (to bring us inline with GitHub) 
- Pipeline filtering ( order by assignee, created date, estimation etc, etc)
- And / OR / Not filtering support (for example, show me everything that does not have the label 'Bug')

The last two here are highly requested user features. 

**Make the tool easier for developers** 
This is a theme of work to make tracking work through pipelines as simple as possible. The first stage here is to provide a mapping between Issues and PRs. This also includes changes such as creating a default pipeline for PRs (so they can, for example, always go straight to code review) 

The programmatically change pipeline issue is connect to this, it is a much larger problem to tackle. But is certainly in the direction we want the tool to be moving. 

**Reporting**
We also need to build out the PM focused requirements around reports. This includes

- Changes to the burndown report, in particular 
   - Ability to define which pipeline causes the 'burndown'
   - Ability to show/hide PRs
   - Better support for Epics 
   - Provide functionality for teams who are not using estimate values
   - Filter by label
- Cumulative flow diagrams 
- Velocity tracking 
- Data exporting 

**Better multi-repo support** 
Working over multiple repos is something that most of our users do. The current experience for working with Multi-repo milestones / labels / estimates is poor.

**Epics**
Since the launch of epics we have had loads of great feedback, I am currently collating this so that we can do a v2 release and improve the experience. 


**How users can access ZenHub** 
Reduce the reliance of ZenHub on Chrome and Firefox 

- Safari
- Mobile support
- Web app 

Each of these is a massive change, we need to prioritize the three and get them all shipped. 

**API** 
Write access for the API 


So I am sure you will agree - lots to do! But each of these things are going to be amazing 👍 

-------------------------------

To answer the individual issues you have raised: 

https://github.com/ZenHubIO/support/issues/19 - use labels for board pipeline management 

This is a really tough issue to prioritize. On an idealistic level, we wanted to keep labels as a separate entity so that we don't overload them. I find labels really useful and know a lot of users do to. In early experiments with doing this change, it became really hard to find the progress of an issue when it was buried in a number of labels. This also increased friction with changing the pipeline - which ultimately made ZenHub less useful. 

My user research has found that this is mostly requested by new teams, when following up with users who have requested this, after using ZenHub for some time most (but not all!) agree that separation of pipelines and labels is a better experience. 

Making this change is not something we are planning to do at the moment. 

https://github.com/ZenHubIO/support/issues/58 - programatically changing pipeline 

Certainly a 'want to do' We just need time to get it done :) 

https://github.com/ZenHubIO/support/issues/233 - closing an issue should not move it to the closed pipeline

 Ideally we would be able to do this. But looking at the list of high priorities above, to be honest with you, I can't see it getting done in the near future as the workaround of not closing the issue exists. The release coming to link Issues and PRs without having to use keywords like 'closes' should help here. 


---------------

That turned into a bit of an essay... so thank you if you made it all the way to the end! I hope it was helpful

Happy to answer any other questions you have, either here or if you email me at support@zenhub.io - we can jump on a call.

**Comment by mpaler** [comment]
AzenMatt,

Thanks for the thoughtful and detailed reply. Very helpful. As a relative newcomer to ZenHub it's nice to hear about your team size and challenges. I can _definitely_ appreciate the problems of a major refactor with a small team. Been there, done that -- however never with a large technically savvy, demanding userbase breathing down my neck (Mine were internal "customers"). Kudo's to you and your team -- it's a fabulous product and hopefully the active GH forums and impassioned posts by users like me only encourage you to press on. Hopefully, once you deploy the refactor, you can take a week or two to enjoy your achievement!! It's important to celebrate those occasionally.

So just to confirm, if I'm reading you correctly, is sounds like the most promising avenue for robust user control of the pipeline will be write access for the API? Is #172 the best place to follow along on that? Please keep us apprised on that.

Thanks again -- an likewise, please feel to hit me up paler at civicsolar dot com if you'd like to connect on any of this.

**Comment by jasonjohnsonSA** [comment]
Thank you for the clarity and transparency.

**Comment by azenMatt** [comment]
Thanks @mpaler @jasonjohnsonSA 


> So just to confirm, if I'm reading you correctly, is sounds like the most promising avenue for robust user control of the pipeline will be write access for the API? Is #172 the best place to follow along on that? Can you estimate any timelines around the API? Please keep us apprised on that.

Yes, 172 is the best place for this. The team discussed this today and we are going to see if we can start providing support for the easier write access pieces (pipeline and estimates) sooner rather than later. I will update that issue once we start.

I will keep you updated on our progress in this repo and work towards it being a more open communication of our current roadmap.
