### ISSUE TITLE
Show issues in Epic as a simple list vs. a grid

### ISSUE THREAD

**Issue by mpaler** [ZenHubIO/support#781]
When viewing an Epic, does anyone else find the grid view of issues difficult to determine issue priority? Does anybody else think it would be better as a simple list? Simple fix for a quick win?

For example change this:

![improving purchasing workflows issue 160 civicsolar salesforce](https://cloud.githubusercontent.com/assets/352390/15979009/6432afdc-2f16-11e6-813d-6d13e35130cd.jpeg)

To this:

![issues civicsolar salesforce](https://cloud.githubusercontent.com/assets/352390/15979010/64330d10-2f16-11e6-95d9-e7414b7a80d4.jpeg)

Related to #715, a list format would be a nice foundation for making issues draggable/reorderable.

**Comment by mogul** [comment]
I find that on a laptop-sized screen, the amount of text being crammed into the two-column view makes a lot of it be cut off with "...", making it difficult to distinguish between a lot of similarly-named issues in the same epic. Using a single column would widen out the space and address that problem.

**Comment by azenMatt** [comment]
Agreed that this needs to become a more user friendly interface 

cc @brianleung11-3 who has been looking at this recently

**Comment by mpaler** [comment]
@azenMatt @brianleung11-3 unfortunately, this continues to bite us over here. Any update on this enhancement? Seems like it should be a relatively simple fix..for a pretty big usability win.

**Comment by brianleung11-3** [comment]
Thanks for the feedback @mpaler. We're prototyping with the single column design as suggested above including a way to prioritize issues right on the epic issue page. Stay tuned!

**Comment by mpaler** [comment]
@brianleung11-3 Killer!! Looking forward to the enhancement. Will make working with Epics way easier. Thanks for the update.

**Comment by thisisfranciswu** [comment]
I second @mogul's title legibility concerns. A list view would reveal more of the title. Also, **a list view would easily permit the display the full title instead of truncating it**. I'm assuming truncating the title was a solution for resolving grid alignment issues.

**Comment by mpaler** [comment]
@brianleung11-3 This issue continues to bite us! Any update on when this improvement will ship?

**Comment by brianleung11-3** [comment]
We hope to have the improvements by mid November. Thanks for being patient with us.

**Comment by mogul** [comment]
I appreciate that you're doing a lot more than is strictly necessary (prioritizing within the epic view sounds great), but meanwhile this continues to bite us... Lists in epics are pretty useless to us now. Exhibit A: 
![image](https://cloud.githubusercontent.com/assets/47762/21568098/6ec8009c-ce66-11e6-9f5b-09a3370f906f.png)

(You can [see this example live](https://github.com/18F/cg-product/issues/63).)

To find out which story any of those might be, you need to open the link in a new tab, switch to that tab, and probably switch back again. (If you click to open it right in the epic, and the epic itself was opened from the board, then you're going to lose the board view in the background and have to reload it, which can take aaaaages and totally break flow when it happens multiple times during planning activity.)

So, any updates on this one? As an interim relief, could you at least **include the full issue title as a span title**? For example:

```html
<span title="This is the full long issue title for a story in the epic">This is the full long...</span>
````

That would at least alleviate the pain for all of us here while you ship the new feature.

**Comment by azenMatt** [comment]
ouch - agreed that one is painful @mogul! 

The updates we were looking at doing for the prioritization on this page are going to take longer than we initially thought. We are instead going to do as you have suggested and push out a more simple update to transform the grid to a list, something like .... 

![image](https://cloud.githubusercontent.com/assets/7584089/20777203/4dacb7e4-b71a-11e6-8732-36e7445da26a.png)

moving this one into 'in progress'

**Comment by mogul** [comment]
That looks like a huge interim improvement; really looking forward to this! 👍

**Comment by mogul** [comment]
This interim version isn't imminent, by chance, is it? We have a major quarterly planning meeting happening this coming week and this would go a long way in reducing friction. **Even if it lacked any of the estimate information at the right, it would be hugely useful!**

**Background (aka More Information Than You Require)**: 

We'll be doing a [two-day exercise](http://scaledagileframework.com/pi-planning/) on Tuesday and Wednesday where we'll be reviewing and adding to the stories under of a bunch of existing Epics, then doing MoSCoW prioritization on the list of stories in each. 

The usual way we do this is to incur the overhead of creating corrals and post-its at the top of [our planning board in Mural](http://mur.al/mDz906Qj) (that's the one from last quarter) to represent epics and stories already in GitHub, then work with them there as a group. We do this because it's so cumbersome to work with epic content in ZenHub, and we do this even though we know we'll just have to reconcile all the stories back into ZenHub epics and stories after we're all done planning.

If we had your interim list available, it's much more likely that we'd be looking at the ZenHub epic as a visual-aid/scratch-pad during these conversations and not have to manually round-trip information out and back in.

**Comment by azenMatt** [comment]
Thanks for the extra info here @mogul - this change is being worked on at the moment, but il be honest it is very unlikely that it will be live by Tuesday. It will likely be 1-2 more weeks before it is available in production.

**Comment by mogul** [comment]
Worth a shot. ¯\_(ツ)_/¯ Thanks for listening!

**Comment by azenMatt** [comment]
Hi @mogul - if you update your extension you should see the new Epic issues list -

![image](https://cloud.githubusercontent.com/assets/7584089/22300094/05f8a6da-e2ec-11e6-8472-48b64fef0b4d.png)

I think it still needs a little more polish - but should be much more helpful that the old version! 

Let me know what you think!

**Comment by mogul** [comment]
It's a huge improvement, thanks! (And so happy we could supply you with screenshot material.)
