### ISSUE TITLE
Total story points of epic ticket does not take in to account story points of all sub tickets.

### ISSUE THREAD

**Issue by akruijff** [ZenHubIO/support#804]
Given an epic ticket with a sub epic ticket with a regular ticket (epic -> sub epic -> regular)
Then the story points of the regular ticket is not used to count the main epic.

![zenhub-bug1](https://cloud.githubusercontent.com/assets/1003936/16396235/163ff0fe-3cbe-11e6-8b38-1abb6f446513.png)

**Comment by azenMatt** [comment]
Hi @akruijff - we are looking into providing automatic story points for epics based on the total number of issues inside an epic - I will keep you updated

**Comment by ethangeyer** [comment]
@azenMatt - would that also work to let the specific story points assigned to the children epics (which in turn are reflective of their issues) to be aggregated if they happen to exist?

**Comment by Anvil102** [comment]
+1 to this. It would be quite useful to have a separate "Epic Total Estimate" section in the sidebar that is separate from the "Estimate" and automatically tallies all nested issues and "sub-epics" inside an epic. It would be even better if this "Epic Total Estimate" was displayed as split value of "remaining to be done" / "total" so we had a rough read of how much of the epic was left to complete.

**Comment by KoltonG** [comment]
@azenMatt Just an update on this issue, I am seeing that in the new Release feature the Epics that have estimated Story points show up with "Not Estimated". Is there a fix regarding this or should we not include Epics in Releases?

**Comment by azenMatt** [comment]
Hi @KoltonG - the way this currently works is that Epics in releases only count the 'high level' epic itself. If you would like all the issues inside the epic to be in the release - then these items would need to also be added to the release. 

As i'm writing this, i'm think it would be useful for you to see an 'epic points' total for all issues that are in the release rather than the total for the epic? 

so for example if you have: 

Epic A 
  Issue 1
  Issue 2
  Issue 3 
  Issue 4 

and Release X contains 

Epic A
  Issue 2
  Issue 3

You would want to see Epic as having a value 'Epic Points' that is the sum of Issues 2+3 ?
