### ISSUE TITLE
Can no longer scroll on Zenhub board [ Solved - Chrome update required]

### ISSUE THREAD

**Issue by gautamrao11** [ZenHubIO/support#835]

**Comment by azenMatt** [comment]
Hi @gautamrao11 - as covered over email, this is caused by a compatibility issues with some older versions of chrome. 

If you have this issue please update chrome and everything will start to work again.

I'm going to leave this issue open for a few days so anyone else coming in here can find the solution. 😄

**Comment by unnu** [comment]
What version of chrome fixes the problem? Chrome says, I'm on the newest version, but the bug still exists for me.

Chrome: Version 47.0.2526.106 (64-bit) on OSX 10.11.3
ZenHub Chrome Extension: Version 2.21.1

**Comment by unnu** [comment]
Ok. Just ignore my comment above. I'm on an outdated chrome version, but chrome says it's the newest. Strange. Whatever.

**Comment by azenMatt** [comment]
We just fixed the backwards compatibility issue with Chrome, as of version v2.21.2 of ZenHub, you can run older versions of Chrome if you wish :)
