### ISSUE TITLE
Automatically mark TODOs as done when the issues are closed

### ISSUE THREAD

**Issue by emschwartz** [ZenHubIO/support#853]
The TODO list is useful to see what issues you have marked that still need to be done. However, it would be better if it would automatically remove TODOs when the corresponding issue has been closed/merged. If this isn't the desired behavior in all use cases, a configurable option might be the best approach.

**Comment by kendramoroz** [comment]
Hey @emschwartz - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
