### ISSUE TITLE
`#todo` anchor links break inside of repositories

### ISSUE THREAD

**Issue by leesharma** [ZenHubIO/support#874]
## System Details
- **ZenHub Version:** 2.23.21
- **Browser:** Firefox 47.0.1
- **OS:** OS X 10.11.5
## Current Behavior

If I try to visit a link within a repository that ends in `#todo`, the page will jump to the correct anchor, then jump up and disable scrolling (arrow keys still work).
#### Demo

![weird_todo_behavior](https://cloud.githubusercontent.com/assets/814638/18041410/742653ea-6d86-11e6-82e9-2bc74573fb3f.gif)

_To see it in action: https://github.com/leesharma/rescuetime#todo_

This is a problem because "TODO" is a common README section name. Since GitHub automatically links headers, trying to follow a link to any TODO section will result in the page freezing up until the user manually removes `#todo` from the URL.

This only occurs when I have ZenHub enabled. I assume it has something to do with how your ToDo lists are implemented.
## Desired Behavior

When I follow a link that includes an anchor link to `#todo`, then the page should jump to the TODO anchor. No further jumping should occur, and scrolling should not be disabled. In general, if an anchor exists on a page, I would first expect the link to work.

If I go to `#todo` from the main GitHub page, then I should be brought to my To Do list.

**Comment by azenMatt** [comment]
Thanks for reporting this @leesharma - you are right that this is connected to how we navigate to the ToDo page. 

We will take a looking into a better method to resolved this problem

**Comment by kendramoroz** [comment]
Hey @leesharma  - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
