### ISSUE TITLE
Migration of sub tickets when converting epic to normal ticket

### ISSUE THREAD

**Issue by akruijff** [ZenHubIO/support#882]
As a developer/planner, I want to assign an epic ticket to another epic ticket when a converting epic ticket to normal ticket and migrate all sub tickets to the new destination ticket so that migration takes less manual work. When an epic ticket is (already) part of another epic ticket then I want this to be the default.

**Comment by azenMatt** [comment]
Hi @akruijff 

A bit of a work around here, but once - https://github.com/ZenHubIO/support/issues/832#issuecomment-249014855  - 
![image](https://cloud.githubusercontent.com/assets/7584089/19420624/06ee27aa-93a4-11e6-9c94-da1ce9c8aa03.png)

goes live in the next ~3 weeks, it will be much easier to batch select and move issue into an Epic. 

Once live we can look into the other changes here you have suggested. We probably wouldn't want to make this migration the default behaviour as lots of teams add epics to other epics for the purpose of nesting rather than migration. But i'm sure we can find a way to make this simple to do for the use case where it is wanted

**Comment by akruijff** [comment]
Nice work!
