### ISSUE TITLE
How will projects affect or integrate with Zenhub?

### ISSUE THREAD

**Issue by goanpeca** [ZenHubIO/support#897]
https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by cbeams** [comment]
@goanpeca, see https://www.zenhub.com/blog/dispatches-from-github-universe/.

**Comment by azenMatt** [comment]
and of course we are interested in getting everyones feedback on projects once you have had a chance to play with them! 

The GH team are still rolling out the API so we will be able to keep building on top of it based on everyones feedback

**Comment by lanceplaine** [comment]
Is it possible to build the same "Boards" features on top of the "Projects" tabs?
  - Create a new issue (via a modal) directly from the Projects section
  - View issues (via a modal) directly from the Projects section
  - Being able to change the assigned "Project" of an issue directly from the issue itself

**Comment by azenMatt** [comment]
> Is it possible to build the same "Boards" features on top of the "Projects" tabs?

Right now we are not looking to build anything inside the projects tab as I would expect the UI to be in a state of flux while they nail down the experience. Integrating via the API is the preferred (and recommended!) method at the moment

**Comment by MrLoh** [comment]
it would be really cool if the github projects could somehow sync with zenhub boards. The current itegration seems pretty useless, I don't wanna move tasks around in two places. But adding modals and burn down charts to the project tabs would be really nice.

**Comment by adamreisnz** [comment]
Now that Zenhub has decided not to integrate with Projects, which I think makes sense, is it possible to hide the Project selector? It is quite high up the list and when using Zenhub, pretty much useless.

If hiding it is too much, is it possible to move it to the bottom of the list using CSS overrides?

![image](https://cloud.githubusercontent.com/assets/490562/21069449/d8e1f27c-bede-11e6-915b-bb7abd7b31eb.png)

**Comment by azenMatt** [comment]
Hiding it does seem a bit too much, 

Putting it to the bottom is possible, but would make the load look a little 'jankier' as the normal side bar would need to load first, then once this has rendered, ZenHub would have to re-arrange it. 

Its for this reason we have so far tried only to 'expand' the side bar by injecting inside it rather than re-arrange it

**Comment by azenMatt** [comment]
But i could certainly be persuaded! 😆

**Comment by adamreisnz** [comment]
Hehe, ok I'll try ;)

I think the fact that items are inserted already makes it look somewhat 'janky', because things are moved down. So personally I think that rearranging one more item won't make that much of a difference, as long as it all happens at the same time.

And the benefit it yields, moving the item most Zenhub users probably won't use, plus easier access to the other items in return I think would outweigh the minor aesthetic negative. After all, we're after productivity here! 🚀

**Comment by cbeams** [comment]
I wouldn't want to see any part of the native GitHub UI removed by ZenHub without my explicit request. If removing the projects menu were an opt-in, per-user setting, that would be fine. Otherwise, it's just not realistic to assume that every ZenHub user does not want to see GitHub projects. I know this is the case because my team uses both in a couple select cases, and it would be a bad thing if ZenHub hid that information from us.

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
