### ISSUE TITLE
Sign in now to use ZenHub

### ISSUE THREAD

**Issue by Wellbeloved** [ZenHubIO/support#906]
Hi, I have not been able to access the boards this morning. Everything fine on log in but when I go to the boards I get 
<img width="229" alt="screen shot 2016-09-27 at 10 40 39" src="https://cloud.githubusercontent.com/assets/16798643/18868100/e3b542e6-849e-11e6-981b-58c0176fb70e.png">

Any ideas?

**Comment by azenMatt** [comment]
Hi @Wellbeloved 

Can you try and access a board and share any errors that show up in the browsers development console?

**Comment by NobbZ** [comment]
Since I am having a similar issue right now and cannot access boards or reports on my repository, I do provide what I get in my chromes JS-console:

```plain
frameworks-5b06b44….js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENTZ @ frameworks-5b06b44….js:6i @ frameworks-5b06b44….js:6te.D @ frameworks-5b06b44….js:6Ln.send @ frameworks-5b06b44….js:6n.(anonymous function) @ frameworks-5b06b44….js:6Un.v @ frameworks-5b06b44….js:6Un.D @ frameworks-5b06b44….js:6Bn @ frameworks-5b06b44….js:6r @ frameworks-5b06b44….js:6u @ github-62aec7f….js:2(anonymous function) @ github-62aec7f….js:2
collector.githubapp.com/github/page_view?dimensions[page]=https%3A%2F%2Fgit…8bcf3d6ff91e4056d078fbcd974476d0122&dimensions[cid]=645348145.1478903865:1 GET https://collector.githubapp.com/github/page_view?dimensions[page]=https%3A%…128bcf3d6ff91e4056d078fbcd974476d0122&dimensions[cid]=645348145.1478903865 net::ERR_BLOCKED_BY_CLIENT
github-62aec7f….js:2 OPTIONS https://api.github.com/_private/browser/stats net::ERR_BLOCKED_BY_CLIENTo @ github-62aec7f….js:2
pulls:1 Uncaught (in promise) TypeError: Failed to fetch
main.js:41 auth:error:not_authed
main.js:41 auth:error:not_authed
```

When loading any github page, I do see everythin of this up to and including the first `main.js:41 auth:error:not_authed`, from then on I will get another one of these for every time I do either click on "sign in now" or try to access a Zenhub feature from github.

Accessing my Account page from zenhub.com works fine though.

Also I tried to log in via the Chrome-Plugin before finding this issue, I was redirected to a github page which told me, that I need to re-authenticate zenhub because of "an abnormal number of requests to my account". I re-authenticated it, but it still does not work.

**Comment by azenMatt** [comment]
Hi - we found some potential causes for this which we are releasing at the moment. 

If the issue is still occurring, can you email us at support@zenhub.com and we will get it fixed for you 👍
