### ISSUE TITLE
Implement move issue for epics

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#913]
Repro steps:
1. Open a non-epic card, notice that the Move Issue button is present as expected
2. Open an epic card, notice that the Move Issue button appears and then rapidly disappears

**Comment by azenMatt** [comment]
Hi @cbeams - I agree the flicker here is a bug :) 

We didn't add the move functionality to the epic due to the increase in scope this would have required to also move over all the child issues of the epic. 

We do want to revisit the move issue functionality in the future to both 1) improve the core functionality to also bring over meta-date 2) include epics

**Comment by cbeams** [comment]
I see, thanks for clarifying, @azenMatt. /cc @eriwen

**Comment by cbeams** [comment]
Feel free to rename this issue, then Matt, either to have it cover the epic-moving feature, or to constrain it just to the flicker bug.

**Comment by kendramoroz** [comment]
closing in favor of it's duplicate, #730! Subscribe there for updates :)
