### ISSUE TITLE
Ability to filter the board by issues that I participate in

### ISSUE THREAD

**Issue by RobertPeetsalu** [ZenHubIO/support#914]
It's a little neat feature in Trello that I instantly started missing in ZenHub - a way to filter issues on the board by participants so that I would only see issues which I'm a participant in

**Comment by azenMatt** [comment]
Thanks for the suggestion @RobertPeetsalu - I think that makes a lot of sense from a functionality point of view. 

If everyone could add 👍  to the opening comment if they would find it useful, it will help us to prioritize

**Comment by RobertPeetsalu** [comment]
Till this is implemented I use a workaround - I go to the Github Issues tab and use this filter in the search bar: "is:open involves:RobertPeetsalu"

**Comment by azenMatt** [comment]
that would work - ideally we would add those advanced filter words to the board search box

**Comment by kendramoroz** [comment]
@nickykrause, dropping your comments here as mentioned in #1033 

---

Here is something I want to do in ZenHub, but which I am not sure how to do. Maybe I just don't see how to do it, or maybe it isn't possible - I'm not sure. (I'm sort of a ZenHub newbie.)

Anyway, here it is:

> Show me not only the issues that are assigned to me, but also those in which I am `participating`

I am not sure exactly how GitHub defines "participants," but I can see that it appears as meta data on issues. Seems to add me as a participant once I comment.

In a similar vein, I want to be able to say

> Show me not only the issues to which I am assigned, but also those in which I am mentioned. 

I use ZenHub to track issues that I am responsible for (assigned), but part of what I am responsible for is responding to other people's work (through mentions/participation), and I sometimes find myself losing track of those kinds of tasks because the only record of them is in my carefully-filtered email (which means I have to go to two places to look for work I need to do -- my email list of mentions + ZenHub to see issues assigned to me).

**Comment by kendramoroz** [comment]
Closing in favor of #1023, to track subscribe to/participations in a central location! Please subscribe there if this is still of interest to you :)
