### ISSUE TITLE
Todo "nav-bar" button is not an anchor

### ISSUE THREAD

**Issue by smondet** [ZenHubIO/support#934]
The `ToDo` next to the Gist one is not a `<a ... > ... </a>`:

![image](https://cloud.githubusercontent.com/assets/617111/19603048/a8a1f888-977d-11e6-8769-50ce9f7c80b0.png)

This doesn't play well with Vimium (and I guess with other keyboard-based browsing, or accessibility tools):

![image](https://cloud.githubusercontent.com/assets/617111/19603101/e3a59818-977d-11e6-9bec-f840de52d447.png)

**Comment by kendramoroz** [comment]
Hey @smondet - Kendra here from the ZenHub Team. I wanted to share the latest news from the ZenHub team to keep our community updated on the status of ToDo's and ToDo enhancements.

As we focus on team collaboration, we're focused on improving feature experiences that help teams collaborate, remove blockers, and keep teams moving forward effectively - ToDo has been a long-standing ZenHub feature that we've seen community members pick up and use across ZenHub since it's launch, but hasn't received the widespread adoption as other Board and Report workflows we've launched over the years. 

To continue focusing on features and enhancements where we've seen widespread community adoption and support, we've decided to deprecate the ToDo feature as of October 5th to focus on improving the core ZenHub experience. 

If you have any questions don't hesitate to reach out via support@zenhub.com and let the team know how we can help.
