### ISSUE TITLE
Is there any way to disable shortcuts?

### ISSUE THREAD

**Issue by naderman** [ZenHubIO/support#963]
I constantly end up opening the boards page by accidentally hitting the b character on my keyboard. Even worse, because of the way ZenHub opens that page, the browser back button, doesn't actually take me back to the page i was just looking at. I have to remove the anchor from the URL in the browser bar and hit enter to get to the page I was trying to read when I hit "b". Please provide some mechanism to disable shortcuts, and fix the back button.

**Comment by kendramoroz** [comment]
Hey @naderman Kendra here from the ZenHub team 👋  Thanks for the feedback on the shortcuts, I've passed this as an enhancement to our team. There's no current way to disable shortcuts, but I've bumped this over to the community icebox for votes. If others are finding similar trouble with the b shortcut, please 👍  the original comment! 

Happy new year 🚀

**Comment by jemc** [comment]
This constantly bugs me as well - I use the space bar to scroll down a page, and I often accidentally hit the "b" key and get whisked away from whatever I was trying to look at.

To make matters worse, the "Boards" page is so slow to load that I have to wait a significant amount of time before I can "go back".

I came here looking for a way to disable keyboard shortcuts, but at this point since there is no way to do so, I think I'm just going to disable the ZenHub plugin entirely, and only enable it when I need ZenHub features :frowning_face:.

**Comment by naderman** [comment]
How many votes are enough for this to finally get fixed? :(

**Comment by wjzhengsh** [comment]
I'm used to coding in GitHub web page and letters `b` `d` `f` are frequently used ones.  This default hotkey function stops me time to time, and it's really a very bad experience.

**Comment by bradical** [comment]
Also, doesn't `b` take you to the `blame` view in Github by default? Not sure if that's what's implied here but it would be nice if I get to blame with the `b` key without having to alter the URL. Thanks!

**Comment by naderman** [comment]
Please will you fix this already, it's just one simple option and it's the most frustrating part of my entire work day, waiting ages for a board to load some 50 times per day when all I wanted to do was view an issue.

**Comment by kendramoroz** [comment]
t@naderman thanks for raising the Issue again - we're going to be looking to introduce a solution here over the next few sprints—we'll post another update shortly!

**Comment by kendramoroz** [comment]
Hey all 👋  We've just launched our shortcut improvements 🎉 
While there's no direct disable option, we've improved the interaction with shortcuts to include the use of 2 keyboard strokes to tackle the original issue of accidental keyboard strokes that were taking you away from work in progress. We hope this solves the original pain point and helps you navigate using intentional shortcuts!

You can check out the complete suite of new shortcuts here: https://www.zenhub.com/guides/keyboard-shortcuts

Let us know what you think ✨
