### ISSUE TITLE
No way to navigate to the "Boards" tab from the "Pull Requests" or "Issues" views

### ISSUE THREAD

**Issue by tmthyjames** [ZenHubIO/support#983]
From the "Boards" tab, If I click on "ToDo" I get directed to the "ToDo" view. If I click it again, I get directed to the "Boards" tab. But if I click "ToDo" then from the "ToDo" view I click "Pull requests" or "Issues", in those views there's no button to get back to the "Boards" view.

**Comment by azenMatt** [comment]
Hi @tmthyjames - is this because of the level that the 'pull requests' and 'issues' pages exist? 

 https://github.com/pulls lives at the top level of GitHub and looks at all issues. 

Where as the board lives at repo level, so to get to an entry point for it, you need to go back to the repo level? 


-----

Although I agree at a high level that the ToDo page needs a better method for getting back to a repo level

**Comment by azenMatt** [comment]
closing this one as ToDo is being depreciated over the next couple of weeks
