### ISSUE TITLE
Load more issues link not working

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#988]
I'm trying to use the button "load more issues", e.g.:

![image](https://cloud.githubusercontent.com/assets/490562/21258761/5d141dfa-c3e3-11e6-83ae-fccd24148d0d.png)

but it doesn't seem to work. No additional issues are loaded, yet there are a bunch more issues in that milestone in the closed column.

Is this functionality not working or am I missing something?

**Comment by azenMatt** [comment]
Hi @adamreisnz - we had some issues with this earlier in the week that have now been resolved. 

However - it may look like none are loading depending on where the issues are in the closed issue pool. 

This is because we can't send any parameters to GitHub when loading the closed issues. So when you hit 'load more issues' we grab the next 50 from GitHub - without being able to include any filters you have applied. 

So if you have a milestone filter it may look like nothing is loading - but this is only because those 50 issues we did load don't contain any in this milestone. 

Due to the vast number of closed issues that most repos have - we can't just load them all as it would be too many requests (some repos have tens of thousands of closed issues) - and we have no way off knowing when all the issues matching the filter states have been discovered. 

I hope this helps provide more context around how this works - please let me know if you have any other questions on it!

**Comment by adamreisnz** [comment]
Gotcha, that could have been what's going on. Would it be possible to show some kind of spinner on the button to at least show that *something* is going on? It looks like the button is simply not working in this case.

A potentially "smarter" solution could be to load 50 more issues, check if *any of them* actually match the *current filters*, and if not, load 50 more and repeat, until at least one more issue is found that matches the filter, or limited to say 5-10 requests.

That way, the user would always get what they expect to achieve, e.g. more issues to show up in the `Closed` column, unless there simply aren't more.
