### ISSUE TITLE
Add newly created issues to the top of the Backlog pipeline

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#992]
I have many issues in my backlog. Currently, when I create a new issue for the backlog, it seems to be placed at some random location in the middle between all my other issues. I couldn't find a logic behind it.

Can we have newly created issues automatically placed at the top of the Backlog pipeline, so we can easily find them if needed?

Alternatively, I wouldn't mind them going to the bottom either if most people prefer that, but it should be either top or bottom, not randomly in the middle somewhere, because that makes them really hard to find.

**Comment by azenMatt** [comment]
Hi @adamreisnz 

This is a known issue connected to #537 - based on how the application is architected so that the furthest left pipeline is 'everything not in a pipeline'. This is an unfortunate piece of tech debt that we really need to get fixed as part of our Q1 roadmap. 

Once fixed, it will behave the same as the other pipelines - so that issues transferred in go to the bottom (unless otherwise specified) 

i'l close this issue and keep posting updates in #537 if you would like to subscribe to that for updates.

**Comment by adamreisnz** [comment]
@azenMatt thanks for the clarification, much appreciated. I'll subscribe to #537 instead!
